// flow-typed signature: 71523bd1172bb141483de5e1251823ba
// flow-typed version: <<STUB>>/file-loader_v^0.11.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'file-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'file-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'file-loader/index' {
  declare module.exports: $Exports<'file-loader'>;
}
declare module 'file-loader/index.js' {
  declare module.exports: $Exports<'file-loader'>;
}
