// flow-typed signature: 6d44589a55c3b3bbbc19c15a324b20d5
// flow-typed version: <<STUB>>/tern_v^0.21.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tern'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tern' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tern/doc/demo/demo' {
  declare module.exports: any;
}

declare module 'tern/doc/demo/polyfill' {
  declare module.exports: any;
}

declare module 'tern/doc/demo/underscore' {
  declare module.exports: any;
}

declare module 'tern/lib/comment' {
  declare module.exports: any;
}

declare module 'tern/lib/condense' {
  declare module.exports: any;
}

declare module 'tern/lib/def' {
  declare module.exports: any;
}

declare module 'tern/lib/infer' {
  declare module.exports: any;
}

declare module 'tern/lib/signal' {
  declare module.exports: any;
}

declare module 'tern/lib/tern' {
  declare module.exports: any;
}

declare module 'tern/plugin/angular' {
  declare module.exports: any;
}

declare module 'tern/plugin/commonjs' {
  declare module.exports: any;
}

declare module 'tern/plugin/complete_strings' {
  declare module.exports: any;
}

declare module 'tern/plugin/doc_comment' {
  declare module.exports: any;
}

declare module 'tern/plugin/es_modules' {
  declare module.exports: any;
}

declare module 'tern/plugin/modules' {
  declare module.exports: any;
}

declare module 'tern/plugin/node' {
  declare module.exports: any;
}

declare module 'tern/plugin/node_resolve' {
  declare module.exports: any;
}

declare module 'tern/plugin/requirejs' {
  declare module.exports: any;
}

declare module 'tern/plugin/webpack' {
  declare module.exports: any;
}

declare module 'tern/test/cases/angular/config' {
  declare module.exports: any;
}

declare module 'tern/test/cases/angular/filters' {
  declare module.exports: any;
}

declare module 'tern/test/cases/angular/main' {
  declare module.exports: any;
}

declare module 'tern/test/cases/angular_service' {
  declare module.exports: any;
}

declare module 'tern/test/cases/arguments' {
  declare module.exports: any;
}

declare module 'tern/test/cases/array_holes' {
  declare module.exports: any;
}

declare module 'tern/test/cases/arrow' {
  declare module.exports: any;
}

declare module 'tern/test/cases/autothis' {
  declare module.exports: any;
}

declare module 'tern/test/cases/bind' {
  declare module.exports: any;
}

declare module 'tern/test/cases/block_scope' {
  declare module.exports: any;
}

declare module 'tern/test/cases/blowup' {
  declare module.exports: any;
}

declare module 'tern/test/cases/browser' {
  declare module.exports: any;
}

declare module 'tern/test/cases/builtins' {
  declare module.exports: any;
}

declare module 'tern/test/cases/catch_error' {
  declare module.exports: any;
}

declare module 'tern/test/cases/cautiouspropagation' {
  declare module.exports: any;
}

declare module 'tern/test/cases/class' {
  declare module.exports: any;
}

declare module 'tern/test/cases/complete_strings' {
  declare module.exports: any;
}

declare module 'tern/test/cases/computedprop' {
  declare module.exports: any;
}

declare module 'tern/test/cases/contextcomplete' {
  declare module.exports: any;
}

declare module 'tern/test/cases/copyprops' {
  declare module.exports: any;
}

declare module 'tern/test/cases/ctorpattern' {
  declare module.exports: any;
}

declare module 'tern/test/cases/def_type_string' {
  declare module.exports: any;
}

declare module 'tern/test/cases/defineProperty' {
  declare module.exports: any;
}

declare module 'tern/test/cases/destructure' {
  declare module.exports: any;
}

declare module 'tern/test/cases/docstrings' {
  declare module.exports: any;
}

declare module 'tern/test/cases/effects' {
  declare module.exports: any;
}

declare module 'tern/test/cases/empty_overridden_prop' {
  declare module.exports: any;
}

declare module 'tern/test/cases/es6-features' {
  declare module.exports: any;
}

declare module 'tern/test/cases/es_modules/blah' {
  declare module.exports: any;
}

declare module 'tern/test/cases/es_modules/foo' {
  declare module.exports: any;
}

declare module 'tern/test/cases/es_modules/main' {
  declare module.exports: any;
}

declare module 'tern/test/cases/es_modules/reexp' {
  declare module.exports: any;
}

declare module 'tern/test/cases/extends' {
  declare module.exports: any;
}

declare module 'tern/test/cases/finddef' {
  declare module.exports: any;
}

declare module 'tern/test/cases/findref' {
  declare module.exports: any;
}

declare module 'tern/test/cases/fn_arguments' {
  declare module.exports: any;
}

declare module 'tern/test/cases/for_of' {
  declare module.exports: any;
}

declare module 'tern/test/cases/generator' {
  declare module.exports: any;
}

declare module 'tern/test/cases/generic_each' {
  declare module.exports: any;
}

declare module 'tern/test/cases/getter' {
  declare module.exports: any;
}

declare module 'tern/test/cases/global_this' {
  declare module.exports: any;
}

declare module 'tern/test/cases/hint-objlit' {
  declare module.exports: any;
}

declare module 'tern/test/cases/hint_browser' {
  declare module.exports: any;
}

declare module 'tern/test/cases/hint_ecma5' {
  declare module.exports: any;
}

declare module 'tern/test/cases/hint_simple' {
  declare module.exports: any;
}

declare module 'tern/test/cases/in_comment' {
  declare module.exports: any;
}

declare module 'tern/test/cases/indirect_class' {
  declare module.exports: any;
}

declare module 'tern/test/cases/infinite-expansion' {
  declare module.exports: any;
}

declare module 'tern/test/cases/jquery_event' {
  declare module.exports: any;
}

declare module 'tern/test/cases/jsdoc' {
  declare module.exports: any;
}

declare module 'tern/test/cases/map' {
  declare module.exports: any;
}

declare module 'tern/test/cases/merge' {
  declare module.exports: any;
}

declare module 'tern/test/cases/mixin' {
  declare module.exports: any;
}

declare module 'tern/test/cases/new_array' {
  declare module.exports: any;
}

declare module 'tern/test/cases/new_to_prototype' {
  declare module.exports: any;
}

declare module 'tern/test/cases/node/dir/index' {
  declare module.exports: any;
}

declare module 'tern/test/cases/node/dir/lib/other' {
  declare module.exports: any;
}

declare module 'tern/test/cases/node/dir/lib/relative' {
  declare module.exports: any;
}

declare module 'tern/test/cases/node/exportfunc' {
  declare module.exports: any;
}

declare module 'tern/test/cases/node/localfile' {
  declare module.exports: any;
}

declare module 'tern/test/cases/node/main' {
  declare module.exports: any;
}

declare module 'tern/test/cases/node_exports' {
  declare module.exports: any;
}

declare module 'tern/test/cases/node_modules/mod1/a' {
  declare module.exports: any;
}

declare module 'tern/test/cases/node_modules/mod1/dir1/index' {
  declare module.exports: any;
}

declare module 'tern/test/cases/node_modules/mod1/doc' {
  declare module.exports: any;
}

declare module 'tern/test/cases/node_modules/mod1/mainfile' {
  declare module.exports: any;
}

declare module 'tern/test/cases/node_modules/mod1/node_modules/subdep1/subdep1' {
  declare module.exports: any;
}

declare module 'tern/test/cases/node_modules/mod1/reassign_exports' {
  declare module.exports: any;
}

declare module 'tern/test/cases/node_modules/mod1/reassign_exports_to_required' {
  declare module.exports: any;
}

declare module 'tern/test/cases/node_modules/mod1/secondfile' {
  declare module.exports: any;
}

declare module 'tern/test/cases/node_origin_paths' {
  declare module.exports: any;
}

declare module 'tern/test/cases/object_create' {
  declare module.exports: any;
}

declare module 'tern/test/cases/objectlit' {
  declare module.exports: any;
}

declare module 'tern/test/cases/objnames' {
  declare module.exports: any;
}

declare module 'tern/test/cases/order_of_definition' {
  declare module.exports: any;
}

declare module 'tern/test/cases/phantom_object' {
  declare module.exports: any;
}

declare module 'tern/test/cases/plus' {
  declare module.exports: any;
}

declare module 'tern/test/cases/promise' {
  declare module.exports: any;
}

declare module 'tern/test/cases/proto' {
  declare module.exports: any;
}

declare module 'tern/test/cases/protoname' {
  declare module.exports: any;
}

declare module 'tern/test/cases/replace_bogus_prop' {
  declare module.exports: any;
}

declare module 'tern/test/cases/requirejs/bar' {
  declare module.exports: any;
}

declare module 'tern/test/cases/requirejs/baz' {
  declare module.exports: any;
}

declare module 'tern/test/cases/requirejs/foo' {
  declare module.exports: any;
}

declare module 'tern/test/cases/requirejs/func' {
  declare module.exports: any;
}

declare module 'tern/test/cases/requirejs/main' {
  declare module.exports: any;
}

declare module 'tern/test/cases/requirejs/module_exports' {
  declare module.exports: any;
}

declare module 'tern/test/cases/requirejs/named' {
  declare module.exports: any;
}

declare module 'tern/test/cases/requirejs/requireme' {
  declare module.exports: any;
}

declare module 'tern/test/cases/requirejs/simplifiedcommon' {
  declare module.exports: any;
}

declare module 'tern/test/cases/requirejs/subdir/zap' {
  declare module.exports: any;
}

declare module 'tern/test/cases/requirejs/useexports' {
  declare module.exports: any;
}

declare module 'tern/test/cases/requirejs_config/main' {
  declare module.exports: any;
}

declare module 'tern/test/cases/set' {
  declare module.exports: any;
}

declare module 'tern/test/cases/simple' {
  declare module.exports: any;
}

declare module 'tern/test/cases/simple_generic' {
  declare module.exports: any;
}

declare module 'tern/test/cases/span_from_def' {
  declare module.exports: any;
}

declare module 'tern/test/cases/super' {
  declare module.exports: any;
}

declare module 'tern/test/cases/symbol' {
  declare module.exports: any;
}

declare module 'tern/test/cases/template' {
  declare module.exports: any;
}

declare module 'tern/test/cases/underscore' {
  declare module.exports: any;
}

declare module 'tern/test/cases/webpack/component/foo' {
  declare module.exports: any;
}

declare module 'tern/test/cases/webpack/main' {
  declare module.exports: any;
}

declare module 'tern/test/cases/webpack/node_modules/esnext/index' {
  declare module.exports: any;
}

declare module 'tern/test/cases/webpack/node_modules/foo/browser' {
  declare module.exports: any;
}

declare module 'tern/test/cases/webpack/node_modules/foo/index' {
  declare module.exports: any;
}

declare module 'tern/test/cases/webpack/node_modules/modu/index' {
  declare module.exports: any;
}

declare module 'tern/test/cases/webpack/node_modules/xyz/index' {
  declare module.exports: any;
}

declare module 'tern/test/cases/webpack/webpack.config' {
  declare module.exports: any;
}

declare module 'tern/test/condense' {
  declare module.exports: any;
}

declare module 'tern/test/condense/add_to_old' {
  declare module.exports: any;
}

declare module 'tern/test/condense/angular_simple' {
  declare module.exports: any;
}

declare module 'tern/test/condense/array' {
  declare module.exports: any;
}

declare module 'tern/test/condense/basic' {
  declare module.exports: any;
}

declare module 'tern/test/condense/double_ref' {
  declare module.exports: any;
}

declare module 'tern/test/condense/extend_foo' {
  declare module.exports: any;
}

declare module 'tern/test/condense/fn' {
  declare module.exports: any;
}

declare module 'tern/test/condense/function_prop' {
  declare module.exports: any;
}

declare module 'tern/test/condense/generic' {
  declare module.exports: any;
}

declare module 'tern/test/condense/ignore_newer' {
  declare module.exports: any;
}

declare module 'tern/test/condense/node_export_function_a' {
  declare module.exports: any;
}

declare module 'tern/test/condense/node_fn_export' {
  declare module.exports: any;
}

declare module 'tern/test/condense/node_other_module_type_ref' {
  declare module.exports: any;
}

declare module 'tern/test/condense/node_require_private' {
  declare module.exports: any;
}

declare module 'tern/test/condense/node_simple' {
  declare module.exports: any;
}

declare module 'tern/test/condense/proto' {
  declare module.exports: any;
}

declare module 'tern/test/condense/recursive' {
  declare module.exports: any;
}

declare module 'tern/test/condense/ref_in_type' {
  declare module.exports: any;
}

declare module 'tern/test/condense/ref_to_old' {
  declare module.exports: any;
}

declare module 'tern/test/condense/requirejs_const' {
  declare module.exports: any;
}

declare module 'tern/test/condense/requirejs_dep' {
  declare module.exports: any;
}

declare module 'tern/test/condense/requirejs_empty_deps' {
  declare module.exports: any;
}

declare module 'tern/test/condense/requirejs_primitive' {
  declare module.exports: any;
}

declare module 'tern/test/condense/requirejs_setup' {
  declare module.exports: any;
}

declare module 'tern/test/condense/uniontype' {
  declare module.exports: any;
}

declare module 'tern/test/data/large' {
  declare module.exports: any;
}

declare module 'tern/test/fragments' {
  declare module.exports: any;
}

declare module 'tern/test/reload' {
  declare module.exports: any;
}

declare module 'tern/test/runcases' {
  declare module.exports: any;
}

declare module 'tern/test/timeout' {
  declare module.exports: any;
}

declare module 'tern/test/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tern/doc/demo/demo.js' {
  declare module.exports: $Exports<'tern/doc/demo/demo'>;
}
declare module 'tern/doc/demo/polyfill.js' {
  declare module.exports: $Exports<'tern/doc/demo/polyfill'>;
}
declare module 'tern/doc/demo/underscore.js' {
  declare module.exports: $Exports<'tern/doc/demo/underscore'>;
}
declare module 'tern/lib/comment.js' {
  declare module.exports: $Exports<'tern/lib/comment'>;
}
declare module 'tern/lib/condense.js' {
  declare module.exports: $Exports<'tern/lib/condense'>;
}
declare module 'tern/lib/def.js' {
  declare module.exports: $Exports<'tern/lib/def'>;
}
declare module 'tern/lib/infer.js' {
  declare module.exports: $Exports<'tern/lib/infer'>;
}
declare module 'tern/lib/signal.js' {
  declare module.exports: $Exports<'tern/lib/signal'>;
}
declare module 'tern/lib/tern.js' {
  declare module.exports: $Exports<'tern/lib/tern'>;
}
declare module 'tern/plugin/angular.js' {
  declare module.exports: $Exports<'tern/plugin/angular'>;
}
declare module 'tern/plugin/commonjs.js' {
  declare module.exports: $Exports<'tern/plugin/commonjs'>;
}
declare module 'tern/plugin/complete_strings.js' {
  declare module.exports: $Exports<'tern/plugin/complete_strings'>;
}
declare module 'tern/plugin/doc_comment.js' {
  declare module.exports: $Exports<'tern/plugin/doc_comment'>;
}
declare module 'tern/plugin/es_modules.js' {
  declare module.exports: $Exports<'tern/plugin/es_modules'>;
}
declare module 'tern/plugin/modules.js' {
  declare module.exports: $Exports<'tern/plugin/modules'>;
}
declare module 'tern/plugin/node.js' {
  declare module.exports: $Exports<'tern/plugin/node'>;
}
declare module 'tern/plugin/node_resolve.js' {
  declare module.exports: $Exports<'tern/plugin/node_resolve'>;
}
declare module 'tern/plugin/requirejs.js' {
  declare module.exports: $Exports<'tern/plugin/requirejs'>;
}
declare module 'tern/plugin/webpack.js' {
  declare module.exports: $Exports<'tern/plugin/webpack'>;
}
declare module 'tern/test/cases/angular/config.js' {
  declare module.exports: $Exports<'tern/test/cases/angular/config'>;
}
declare module 'tern/test/cases/angular/filters.js' {
  declare module.exports: $Exports<'tern/test/cases/angular/filters'>;
}
declare module 'tern/test/cases/angular/main.js' {
  declare module.exports: $Exports<'tern/test/cases/angular/main'>;
}
declare module 'tern/test/cases/angular_service.js' {
  declare module.exports: $Exports<'tern/test/cases/angular_service'>;
}
declare module 'tern/test/cases/arguments.js' {
  declare module.exports: $Exports<'tern/test/cases/arguments'>;
}
declare module 'tern/test/cases/array_holes.js' {
  declare module.exports: $Exports<'tern/test/cases/array_holes'>;
}
declare module 'tern/test/cases/arrow.js' {
  declare module.exports: $Exports<'tern/test/cases/arrow'>;
}
declare module 'tern/test/cases/autothis.js' {
  declare module.exports: $Exports<'tern/test/cases/autothis'>;
}
declare module 'tern/test/cases/bind.js' {
  declare module.exports: $Exports<'tern/test/cases/bind'>;
}
declare module 'tern/test/cases/block_scope.js' {
  declare module.exports: $Exports<'tern/test/cases/block_scope'>;
}
declare module 'tern/test/cases/blowup.js' {
  declare module.exports: $Exports<'tern/test/cases/blowup'>;
}
declare module 'tern/test/cases/browser.js' {
  declare module.exports: $Exports<'tern/test/cases/browser'>;
}
declare module 'tern/test/cases/builtins.js' {
  declare module.exports: $Exports<'tern/test/cases/builtins'>;
}
declare module 'tern/test/cases/catch_error.js' {
  declare module.exports: $Exports<'tern/test/cases/catch_error'>;
}
declare module 'tern/test/cases/cautiouspropagation.js' {
  declare module.exports: $Exports<'tern/test/cases/cautiouspropagation'>;
}
declare module 'tern/test/cases/class.js' {
  declare module.exports: $Exports<'tern/test/cases/class'>;
}
declare module 'tern/test/cases/complete_strings.js' {
  declare module.exports: $Exports<'tern/test/cases/complete_strings'>;
}
declare module 'tern/test/cases/computedprop.js' {
  declare module.exports: $Exports<'tern/test/cases/computedprop'>;
}
declare module 'tern/test/cases/contextcomplete.js' {
  declare module.exports: $Exports<'tern/test/cases/contextcomplete'>;
}
declare module 'tern/test/cases/copyprops.js' {
  declare module.exports: $Exports<'tern/test/cases/copyprops'>;
}
declare module 'tern/test/cases/ctorpattern.js' {
  declare module.exports: $Exports<'tern/test/cases/ctorpattern'>;
}
declare module 'tern/test/cases/def_type_string.js' {
  declare module.exports: $Exports<'tern/test/cases/def_type_string'>;
}
declare module 'tern/test/cases/defineProperty.js' {
  declare module.exports: $Exports<'tern/test/cases/defineProperty'>;
}
declare module 'tern/test/cases/destructure.js' {
  declare module.exports: $Exports<'tern/test/cases/destructure'>;
}
declare module 'tern/test/cases/docstrings.js' {
  declare module.exports: $Exports<'tern/test/cases/docstrings'>;
}
declare module 'tern/test/cases/effects.js' {
  declare module.exports: $Exports<'tern/test/cases/effects'>;
}
declare module 'tern/test/cases/empty_overridden_prop.js' {
  declare module.exports: $Exports<'tern/test/cases/empty_overridden_prop'>;
}
declare module 'tern/test/cases/es6-features.js' {
  declare module.exports: $Exports<'tern/test/cases/es6-features'>;
}
declare module 'tern/test/cases/es_modules/blah.js' {
  declare module.exports: $Exports<'tern/test/cases/es_modules/blah'>;
}
declare module 'tern/test/cases/es_modules/foo.js' {
  declare module.exports: $Exports<'tern/test/cases/es_modules/foo'>;
}
declare module 'tern/test/cases/es_modules/main.js' {
  declare module.exports: $Exports<'tern/test/cases/es_modules/main'>;
}
declare module 'tern/test/cases/es_modules/reexp.js' {
  declare module.exports: $Exports<'tern/test/cases/es_modules/reexp'>;
}
declare module 'tern/test/cases/extends.js' {
  declare module.exports: $Exports<'tern/test/cases/extends'>;
}
declare module 'tern/test/cases/finddef.js' {
  declare module.exports: $Exports<'tern/test/cases/finddef'>;
}
declare module 'tern/test/cases/findref.js' {
  declare module.exports: $Exports<'tern/test/cases/findref'>;
}
declare module 'tern/test/cases/fn_arguments.js' {
  declare module.exports: $Exports<'tern/test/cases/fn_arguments'>;
}
declare module 'tern/test/cases/for_of.js' {
  declare module.exports: $Exports<'tern/test/cases/for_of'>;
}
declare module 'tern/test/cases/generator.js' {
  declare module.exports: $Exports<'tern/test/cases/generator'>;
}
declare module 'tern/test/cases/generic_each.js' {
  declare module.exports: $Exports<'tern/test/cases/generic_each'>;
}
declare module 'tern/test/cases/getter.js' {
  declare module.exports: $Exports<'tern/test/cases/getter'>;
}
declare module 'tern/test/cases/global_this.js' {
  declare module.exports: $Exports<'tern/test/cases/global_this'>;
}
declare module 'tern/test/cases/hint-objlit.js' {
  declare module.exports: $Exports<'tern/test/cases/hint-objlit'>;
}
declare module 'tern/test/cases/hint_browser.js' {
  declare module.exports: $Exports<'tern/test/cases/hint_browser'>;
}
declare module 'tern/test/cases/hint_ecma5.js' {
  declare module.exports: $Exports<'tern/test/cases/hint_ecma5'>;
}
declare module 'tern/test/cases/hint_simple.js' {
  declare module.exports: $Exports<'tern/test/cases/hint_simple'>;
}
declare module 'tern/test/cases/in_comment.js' {
  declare module.exports: $Exports<'tern/test/cases/in_comment'>;
}
declare module 'tern/test/cases/indirect_class.js' {
  declare module.exports: $Exports<'tern/test/cases/indirect_class'>;
}
declare module 'tern/test/cases/infinite-expansion.js' {
  declare module.exports: $Exports<'tern/test/cases/infinite-expansion'>;
}
declare module 'tern/test/cases/jquery_event.js' {
  declare module.exports: $Exports<'tern/test/cases/jquery_event'>;
}
declare module 'tern/test/cases/jsdoc.js' {
  declare module.exports: $Exports<'tern/test/cases/jsdoc'>;
}
declare module 'tern/test/cases/map.js' {
  declare module.exports: $Exports<'tern/test/cases/map'>;
}
declare module 'tern/test/cases/merge.js' {
  declare module.exports: $Exports<'tern/test/cases/merge'>;
}
declare module 'tern/test/cases/mixin.js' {
  declare module.exports: $Exports<'tern/test/cases/mixin'>;
}
declare module 'tern/test/cases/new_array.js' {
  declare module.exports: $Exports<'tern/test/cases/new_array'>;
}
declare module 'tern/test/cases/new_to_prototype.js' {
  declare module.exports: $Exports<'tern/test/cases/new_to_prototype'>;
}
declare module 'tern/test/cases/node/dir/index.js' {
  declare module.exports: $Exports<'tern/test/cases/node/dir/index'>;
}
declare module 'tern/test/cases/node/dir/lib/other.js' {
  declare module.exports: $Exports<'tern/test/cases/node/dir/lib/other'>;
}
declare module 'tern/test/cases/node/dir/lib/relative.js' {
  declare module.exports: $Exports<'tern/test/cases/node/dir/lib/relative'>;
}
declare module 'tern/test/cases/node/exportfunc.js' {
  declare module.exports: $Exports<'tern/test/cases/node/exportfunc'>;
}
declare module 'tern/test/cases/node/localfile.js' {
  declare module.exports: $Exports<'tern/test/cases/node/localfile'>;
}
declare module 'tern/test/cases/node/main.js' {
  declare module.exports: $Exports<'tern/test/cases/node/main'>;
}
declare module 'tern/test/cases/node_exports.js' {
  declare module.exports: $Exports<'tern/test/cases/node_exports'>;
}
declare module 'tern/test/cases/node_modules/mod1/a.js' {
  declare module.exports: $Exports<'tern/test/cases/node_modules/mod1/a'>;
}
declare module 'tern/test/cases/node_modules/mod1/dir1/index.js' {
  declare module.exports: $Exports<'tern/test/cases/node_modules/mod1/dir1/index'>;
}
declare module 'tern/test/cases/node_modules/mod1/doc.js' {
  declare module.exports: $Exports<'tern/test/cases/node_modules/mod1/doc'>;
}
declare module 'tern/test/cases/node_modules/mod1/mainfile.js' {
  declare module.exports: $Exports<'tern/test/cases/node_modules/mod1/mainfile'>;
}
declare module 'tern/test/cases/node_modules/mod1/node_modules/subdep1/subdep1.js' {
  declare module.exports: $Exports<'tern/test/cases/node_modules/mod1/node_modules/subdep1/subdep1'>;
}
declare module 'tern/test/cases/node_modules/mod1/reassign_exports.js' {
  declare module.exports: $Exports<'tern/test/cases/node_modules/mod1/reassign_exports'>;
}
declare module 'tern/test/cases/node_modules/mod1/reassign_exports_to_required.js' {
  declare module.exports: $Exports<'tern/test/cases/node_modules/mod1/reassign_exports_to_required'>;
}
declare module 'tern/test/cases/node_modules/mod1/secondfile.js' {
  declare module.exports: $Exports<'tern/test/cases/node_modules/mod1/secondfile'>;
}
declare module 'tern/test/cases/node_origin_paths.js' {
  declare module.exports: $Exports<'tern/test/cases/node_origin_paths'>;
}
declare module 'tern/test/cases/object_create.js' {
  declare module.exports: $Exports<'tern/test/cases/object_create'>;
}
declare module 'tern/test/cases/objectlit.js' {
  declare module.exports: $Exports<'tern/test/cases/objectlit'>;
}
declare module 'tern/test/cases/objnames.js' {
  declare module.exports: $Exports<'tern/test/cases/objnames'>;
}
declare module 'tern/test/cases/order_of_definition.js' {
  declare module.exports: $Exports<'tern/test/cases/order_of_definition'>;
}
declare module 'tern/test/cases/phantom_object.js' {
  declare module.exports: $Exports<'tern/test/cases/phantom_object'>;
}
declare module 'tern/test/cases/plus.js' {
  declare module.exports: $Exports<'tern/test/cases/plus'>;
}
declare module 'tern/test/cases/promise.js' {
  declare module.exports: $Exports<'tern/test/cases/promise'>;
}
declare module 'tern/test/cases/proto.js' {
  declare module.exports: $Exports<'tern/test/cases/proto'>;
}
declare module 'tern/test/cases/protoname.js' {
  declare module.exports: $Exports<'tern/test/cases/protoname'>;
}
declare module 'tern/test/cases/replace_bogus_prop.js' {
  declare module.exports: $Exports<'tern/test/cases/replace_bogus_prop'>;
}
declare module 'tern/test/cases/requirejs/bar.js' {
  declare module.exports: $Exports<'tern/test/cases/requirejs/bar'>;
}
declare module 'tern/test/cases/requirejs/baz.js' {
  declare module.exports: $Exports<'tern/test/cases/requirejs/baz'>;
}
declare module 'tern/test/cases/requirejs/foo.js' {
  declare module.exports: $Exports<'tern/test/cases/requirejs/foo'>;
}
declare module 'tern/test/cases/requirejs/func.js' {
  declare module.exports: $Exports<'tern/test/cases/requirejs/func'>;
}
declare module 'tern/test/cases/requirejs/main.js' {
  declare module.exports: $Exports<'tern/test/cases/requirejs/main'>;
}
declare module 'tern/test/cases/requirejs/module_exports.js' {
  declare module.exports: $Exports<'tern/test/cases/requirejs/module_exports'>;
}
declare module 'tern/test/cases/requirejs/named.js' {
  declare module.exports: $Exports<'tern/test/cases/requirejs/named'>;
}
declare module 'tern/test/cases/requirejs/requireme.js' {
  declare module.exports: $Exports<'tern/test/cases/requirejs/requireme'>;
}
declare module 'tern/test/cases/requirejs/simplifiedcommon.js' {
  declare module.exports: $Exports<'tern/test/cases/requirejs/simplifiedcommon'>;
}
declare module 'tern/test/cases/requirejs/subdir/zap.js' {
  declare module.exports: $Exports<'tern/test/cases/requirejs/subdir/zap'>;
}
declare module 'tern/test/cases/requirejs/useexports.js' {
  declare module.exports: $Exports<'tern/test/cases/requirejs/useexports'>;
}
declare module 'tern/test/cases/requirejs_config/main.js' {
  declare module.exports: $Exports<'tern/test/cases/requirejs_config/main'>;
}
declare module 'tern/test/cases/set.js' {
  declare module.exports: $Exports<'tern/test/cases/set'>;
}
declare module 'tern/test/cases/simple.js' {
  declare module.exports: $Exports<'tern/test/cases/simple'>;
}
declare module 'tern/test/cases/simple_generic.js' {
  declare module.exports: $Exports<'tern/test/cases/simple_generic'>;
}
declare module 'tern/test/cases/span_from_def.js' {
  declare module.exports: $Exports<'tern/test/cases/span_from_def'>;
}
declare module 'tern/test/cases/super.js' {
  declare module.exports: $Exports<'tern/test/cases/super'>;
}
declare module 'tern/test/cases/symbol.js' {
  declare module.exports: $Exports<'tern/test/cases/symbol'>;
}
declare module 'tern/test/cases/template.js' {
  declare module.exports: $Exports<'tern/test/cases/template'>;
}
declare module 'tern/test/cases/underscore.js' {
  declare module.exports: $Exports<'tern/test/cases/underscore'>;
}
declare module 'tern/test/cases/webpack/component/foo.js' {
  declare module.exports: $Exports<'tern/test/cases/webpack/component/foo'>;
}
declare module 'tern/test/cases/webpack/main.js' {
  declare module.exports: $Exports<'tern/test/cases/webpack/main'>;
}
declare module 'tern/test/cases/webpack/node_modules/esnext/index.js' {
  declare module.exports: $Exports<'tern/test/cases/webpack/node_modules/esnext/index'>;
}
declare module 'tern/test/cases/webpack/node_modules/foo/browser.js' {
  declare module.exports: $Exports<'tern/test/cases/webpack/node_modules/foo/browser'>;
}
declare module 'tern/test/cases/webpack/node_modules/foo/index.js' {
  declare module.exports: $Exports<'tern/test/cases/webpack/node_modules/foo/index'>;
}
declare module 'tern/test/cases/webpack/node_modules/modu/index.js' {
  declare module.exports: $Exports<'tern/test/cases/webpack/node_modules/modu/index'>;
}
declare module 'tern/test/cases/webpack/node_modules/xyz/index.js' {
  declare module.exports: $Exports<'tern/test/cases/webpack/node_modules/xyz/index'>;
}
declare module 'tern/test/cases/webpack/webpack.config.js' {
  declare module.exports: $Exports<'tern/test/cases/webpack/webpack.config'>;
}
declare module 'tern/test/condense.js' {
  declare module.exports: $Exports<'tern/test/condense'>;
}
declare module 'tern/test/condense/add_to_old.js' {
  declare module.exports: $Exports<'tern/test/condense/add_to_old'>;
}
declare module 'tern/test/condense/angular_simple.js' {
  declare module.exports: $Exports<'tern/test/condense/angular_simple'>;
}
declare module 'tern/test/condense/array.js' {
  declare module.exports: $Exports<'tern/test/condense/array'>;
}
declare module 'tern/test/condense/basic.js' {
  declare module.exports: $Exports<'tern/test/condense/basic'>;
}
declare module 'tern/test/condense/double_ref.js' {
  declare module.exports: $Exports<'tern/test/condense/double_ref'>;
}
declare module 'tern/test/condense/extend_foo.js' {
  declare module.exports: $Exports<'tern/test/condense/extend_foo'>;
}
declare module 'tern/test/condense/fn.js' {
  declare module.exports: $Exports<'tern/test/condense/fn'>;
}
declare module 'tern/test/condense/function_prop.js' {
  declare module.exports: $Exports<'tern/test/condense/function_prop'>;
}
declare module 'tern/test/condense/generic.js' {
  declare module.exports: $Exports<'tern/test/condense/generic'>;
}
declare module 'tern/test/condense/ignore_newer.js' {
  declare module.exports: $Exports<'tern/test/condense/ignore_newer'>;
}
declare module 'tern/test/condense/node_export_function_a.js' {
  declare module.exports: $Exports<'tern/test/condense/node_export_function_a'>;
}
declare module 'tern/test/condense/node_fn_export.js' {
  declare module.exports: $Exports<'tern/test/condense/node_fn_export'>;
}
declare module 'tern/test/condense/node_other_module_type_ref.js' {
  declare module.exports: $Exports<'tern/test/condense/node_other_module_type_ref'>;
}
declare module 'tern/test/condense/node_require_private.js' {
  declare module.exports: $Exports<'tern/test/condense/node_require_private'>;
}
declare module 'tern/test/condense/node_simple.js' {
  declare module.exports: $Exports<'tern/test/condense/node_simple'>;
}
declare module 'tern/test/condense/proto.js' {
  declare module.exports: $Exports<'tern/test/condense/proto'>;
}
declare module 'tern/test/condense/recursive.js' {
  declare module.exports: $Exports<'tern/test/condense/recursive'>;
}
declare module 'tern/test/condense/ref_in_type.js' {
  declare module.exports: $Exports<'tern/test/condense/ref_in_type'>;
}
declare module 'tern/test/condense/ref_to_old.js' {
  declare module.exports: $Exports<'tern/test/condense/ref_to_old'>;
}
declare module 'tern/test/condense/requirejs_const.js' {
  declare module.exports: $Exports<'tern/test/condense/requirejs_const'>;
}
declare module 'tern/test/condense/requirejs_dep.js' {
  declare module.exports: $Exports<'tern/test/condense/requirejs_dep'>;
}
declare module 'tern/test/condense/requirejs_empty_deps.js' {
  declare module.exports: $Exports<'tern/test/condense/requirejs_empty_deps'>;
}
declare module 'tern/test/condense/requirejs_primitive.js' {
  declare module.exports: $Exports<'tern/test/condense/requirejs_primitive'>;
}
declare module 'tern/test/condense/requirejs_setup.js' {
  declare module.exports: $Exports<'tern/test/condense/requirejs_setup'>;
}
declare module 'tern/test/condense/uniontype.js' {
  declare module.exports: $Exports<'tern/test/condense/uniontype'>;
}
declare module 'tern/test/data/large.js' {
  declare module.exports: $Exports<'tern/test/data/large'>;
}
declare module 'tern/test/fragments.js' {
  declare module.exports: $Exports<'tern/test/fragments'>;
}
declare module 'tern/test/reload.js' {
  declare module.exports: $Exports<'tern/test/reload'>;
}
declare module 'tern/test/runcases.js' {
  declare module.exports: $Exports<'tern/test/runcases'>;
}
declare module 'tern/test/timeout.js' {
  declare module.exports: $Exports<'tern/test/timeout'>;
}
declare module 'tern/test/util.js' {
  declare module.exports: $Exports<'tern/test/util'>;
}
