export const SANDBOXES_PER_PAGE = 15;

export type SandboxType = 'ALL_SANDBOX' | 'PINNED_SANDBOX' | 'DEFAULT_SANDBOX';

export const sandboxTypes: {
  ALL_SANDBOX: SandboxType;
  PINNED_SANDBOX: SandboxType;
  DEFAULT_SANDBOX: SandboxType;
} = {
  ALL_SANDBOX: 'ALL_SANDBOX',
  PINNED_SANDBOX: 'PINNED_SANDBOX',
  DEFAULT_SANDBOX: 'DEFAULT_SANDBOX',
};

export const DropTargets = {
  SHOWCASED_SANDBOX: 'SHOWCASED_SANDBOX',
  PINNED_SANDBOXES: 'PINNED_SANDBOXES',
};
