export const SANDBOXES_PER_PAGE = 15;

export const SandboxTypes = {
  ALL_SANDBOX: 'ALL_SANDBOX',
  PINNED_SANDBOX: 'PINNED_SANDBOX',
  DEFAULT_SANDBOX: 'DEFAULT_SANDBOX'
};

export const DropTargets = {
  SHOWCASED_SANDBOX: 'SHOWCASED_SANDBOX',
  PINNED_SANDBOXES: 'PINNED_SANDBOXES'
};
