import { Module } from 'cerebral';
import model from './model';
import * as sequences from './sequences';
import {
  isAllModulesSynced,
  currentSandbox,
  currentModule,
  mainModule,
  currentPackageJSON,
  currentPackageJSONCode,
  parsedConfigurations,
  currentTab,
  modulesByPath,
} from './getters';
import { isModuleSynced, shouldDirectoryBeOpen } from './computed';
import { loadSandbox } from '../../sequences';

export default Module({
  model,
  state: {
    sandboxes: {},
    currentId: null,
    isForkingSandbox: false,
    currentModuleShortid: null,
    mainModuleShortid: null,
    isLoading: true,
    notFound: false,
    error: null,
    isResizing: false,
    changedModuleShortids: [],
    currentTabId: null,
    tabs: [],
    errors: [],
    glyphs: [],
    corrections: [],
    pendingOperations: {},
    pendingUserSelections: [],
    isInProjectView: false,
    forceRender: 0,
    initialPath: '/',
    highlightedLines: [],
    isUpdatingPrivacy: false,
    quickActionsOpen: false,
    previewWindow: {
      height: undefined,
      width: undefined,
      editorSize: 50,
      x: 0,
      y: 0,
      content: 'browser',
    },
  },
  getters: {
    isAllModulesSynced,
    currentSandbox,
    currentModule,
    mainModule,
    currentPackageJSON,
    currentPackageJSONCode,
    parsedConfigurations,
    currentTab,
    modulesByPath,
  },
  computed: {
    isModuleSynced,
    shouldDirectoryBeOpen,
  },
  signals: {
    addNpmDependency: sequences.addNpmDependency,
    npmDependencyRemoved: sequences.removeNpmDependency,
    sandboxChanged: loadSandbox,
    contentMounted: sequences.onUnload,
    resizingStarted: sequences.startResizing,
    resizingStopped: sequences.stopResizing,
    codeSaved: sequences.saveCode,
    codeChanged: sequences.changeCode,
    saveClicked: sequences.saveChangedModules,
    createZipClicked: sequences.createZip,
    forkSandboxClicked: sequences.forceForkSandbox,
    likeSandboxToggled: sequences.toggleLikeSandbox,
    moduleSelected: sequences.changeCurrentModule,
    moduleDoubleClicked: sequences.unsetDirtyTab,
    tabClosed: sequences.closeTab,
    tabMoved: sequences.moveTab,
    prettifyClicked: sequences.prettifyCode,
    errorsCleared: sequences.clearErrors,
    projectViewToggled: sequences.toggleProjectView,
    previewActionReceived: sequences.handlePreviewAction,
    privacyUpdated: sequences.updatePrivacy,
    frozenUpdated: sequences.updateFrozen,
    quickActionsOpened: sequences.openQuickActions,
    quickActionsClosed: sequences.closeQuickActions,
    setPreviewBounds: sequences.setPreviewBounds,
    setPreviewContent: sequences.setPreviewContent,
    currentTabChanged: sequences.changeCurrentTab,
    discardModuleChanges: sequences.discardModuleChanges,
    editorSizeUpdated: sequences.updateEditorSize,
  },
});
