FROM node:7.3.0
MAINTAINER Ives van Hoorne

RUN npm install -g yarn

ADD package.json /app/package.json
ADD yarn.lock /app/yarn.lock

WORKDIR /app
RUN yarn install

# After yarn install, so dev deps are also installed (for building)
ENV NODE_ENV production

ADD . /app
RUN npm run build
