// flow-typed signature: bdf2ef8bbcbf11daa4020e8f072abb83
// flow-typed version: <<STUB>>/all-contributors-cli_v^4.3.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'all-contributors-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'all-contributors-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'all-contributors-cli/cli' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/lib/contributors/add' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/lib/contributors/add.test' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/lib/contributors/github' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/lib/contributors/github.test' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/lib/contributors/index' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/lib/contributors/prompt' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/lib/generate/format-badge' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/lib/generate/format-badge.test' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/lib/generate/format-contribution-type' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/lib/generate/format-contribution-type.test' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/lib/generate/format-contributor' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/lib/generate/format-contributor.test' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/lib/generate/index' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/lib/generate/index.test' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/lib/init/add-badge.test' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/lib/init/add-contributors-list.test' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/lib/init/index' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/lib/init/init-content' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/lib/init/prompt' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/lib/util/check' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/lib/util/check.test' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/lib/util/config-file' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/lib/util/config-file.test' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/lib/util/contribution-types' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/lib/util/git' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/lib/util/index' {
  declare module.exports: any;
}

declare module 'all-contributors-cli/lib/util/markdown' {
  declare module.exports: any;
}

// Filename aliases
declare module 'all-contributors-cli/cli.js' {
  declare module.exports: $Exports<'all-contributors-cli/cli'>;
}
declare module 'all-contributors-cli/lib/contributors/add.js' {
  declare module.exports: $Exports<'all-contributors-cli/lib/contributors/add'>;
}
declare module 'all-contributors-cli/lib/contributors/add.test.js' {
  declare module.exports: $Exports<
    'all-contributors-cli/lib/contributors/add.test'
  >;
}
declare module 'all-contributors-cli/lib/contributors/github.js' {
  declare module.exports: $Exports<
    'all-contributors-cli/lib/contributors/github'
  >;
}
declare module 'all-contributors-cli/lib/contributors/github.test.js' {
  declare module.exports: $Exports<
    'all-contributors-cli/lib/contributors/github.test'
  >;
}
declare module 'all-contributors-cli/lib/contributors/index.js' {
  declare module.exports: $Exports<
    'all-contributors-cli/lib/contributors/index'
  >;
}
declare module 'all-contributors-cli/lib/contributors/prompt.js' {
  declare module.exports: $Exports<
    'all-contributors-cli/lib/contributors/prompt'
  >;
}
declare module 'all-contributors-cli/lib/generate/format-badge.js' {
  declare module.exports: $Exports<
    'all-contributors-cli/lib/generate/format-badge'
  >;
}
declare module 'all-contributors-cli/lib/generate/format-badge.test.js' {
  declare module.exports: $Exports<
    'all-contributors-cli/lib/generate/format-badge.test'
  >;
}
declare module 'all-contributors-cli/lib/generate/format-contribution-type.js' {
  declare module.exports: $Exports<
    'all-contributors-cli/lib/generate/format-contribution-type'
  >;
}
declare module 'all-contributors-cli/lib/generate/format-contribution-type.test.js' {
  declare module.exports: $Exports<
    'all-contributors-cli/lib/generate/format-contribution-type.test'
  >;
}
declare module 'all-contributors-cli/lib/generate/format-contributor.js' {
  declare module.exports: $Exports<
    'all-contributors-cli/lib/generate/format-contributor'
  >;
}
declare module 'all-contributors-cli/lib/generate/format-contributor.test.js' {
  declare module.exports: $Exports<
    'all-contributors-cli/lib/generate/format-contributor.test'
  >;
}
declare module 'all-contributors-cli/lib/generate/index.js' {
  declare module.exports: $Exports<'all-contributors-cli/lib/generate/index'>;
}
declare module 'all-contributors-cli/lib/generate/index.test.js' {
  declare module.exports: $Exports<
    'all-contributors-cli/lib/generate/index.test'
  >;
}
declare module 'all-contributors-cli/lib/init/add-badge.test.js' {
  declare module.exports: $Exports<
    'all-contributors-cli/lib/init/add-badge.test'
  >;
}
declare module 'all-contributors-cli/lib/init/add-contributors-list.test.js' {
  declare module.exports: $Exports<
    'all-contributors-cli/lib/init/add-contributors-list.test'
  >;
}
declare module 'all-contributors-cli/lib/init/index.js' {
  declare module.exports: $Exports<'all-contributors-cli/lib/init/index'>;
}
declare module 'all-contributors-cli/lib/init/init-content.js' {
  declare module.exports: $Exports<
    'all-contributors-cli/lib/init/init-content'
  >;
}
declare module 'all-contributors-cli/lib/init/prompt.js' {
  declare module.exports: $Exports<'all-contributors-cli/lib/init/prompt'>;
}
declare module 'all-contributors-cli/lib/util/check.js' {
  declare module.exports: $Exports<'all-contributors-cli/lib/util/check'>;
}
declare module 'all-contributors-cli/lib/util/check.test.js' {
  declare module.exports: $Exports<'all-contributors-cli/lib/util/check.test'>;
}
declare module 'all-contributors-cli/lib/util/config-file.js' {
  declare module.exports: $Exports<'all-contributors-cli/lib/util/config-file'>;
}
declare module 'all-contributors-cli/lib/util/config-file.test.js' {
  declare module.exports: $Exports<
    'all-contributors-cli/lib/util/config-file.test'
  >;
}
declare module 'all-contributors-cli/lib/util/contribution-types.js' {
  declare module.exports: $Exports<
    'all-contributors-cli/lib/util/contribution-types'
  >;
}
declare module 'all-contributors-cli/lib/util/git.js' {
  declare module.exports: $Exports<'all-contributors-cli/lib/util/git'>;
}
declare module 'all-contributors-cli/lib/util/index.js' {
  declare module.exports: $Exports<'all-contributors-cli/lib/util/index'>;
}
declare module 'all-contributors-cli/lib/util/markdown.js' {
  declare module.exports: $Exports<'all-contributors-cli/lib/util/markdown'>;
}
