// flow-typed signature: 409a416589da496370983f3a7101f6f3
// flow-typed version: <<STUB>>/babel-plugin-system-import_v^1.1.5/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-system-import'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-system-import' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'babel-plugin-system-import/index' {
  declare module.exports: $Exports<'babel-plugin-system-import'>;
}
declare module 'babel-plugin-system-import/index.js' {
  declare module.exports: $Exports<'babel-plugin-system-import'>;
}
