// flow-typed signature: 9665db2bd17dc46992b43026d29ff967
// flow-typed version: <<STUB>>/babel-plugin-transform-regenerator_v^6.16.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-regenerator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-regenerator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-regenerator/lib/emit' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-regenerator/lib/hoist' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-regenerator/lib/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-regenerator/lib/leap' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-regenerator/lib/meta' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-regenerator/lib/util' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-regenerator/lib/visit' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-regenerator/src/emit' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-regenerator/src/hoist' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-regenerator/src/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-regenerator/src/leap' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-regenerator/src/meta' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-regenerator/src/util' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-regenerator/src/visit' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-regenerator/lib/emit.js' {
  declare module.exports: $Exports<'babel-plugin-transform-regenerator/lib/emit'>;
}
declare module 'babel-plugin-transform-regenerator/lib/hoist.js' {
  declare module.exports: $Exports<'babel-plugin-transform-regenerator/lib/hoist'>;
}
declare module 'babel-plugin-transform-regenerator/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-regenerator/lib/index'>;
}
declare module 'babel-plugin-transform-regenerator/lib/leap.js' {
  declare module.exports: $Exports<'babel-plugin-transform-regenerator/lib/leap'>;
}
declare module 'babel-plugin-transform-regenerator/lib/meta.js' {
  declare module.exports: $Exports<'babel-plugin-transform-regenerator/lib/meta'>;
}
declare module 'babel-plugin-transform-regenerator/lib/util.js' {
  declare module.exports: $Exports<'babel-plugin-transform-regenerator/lib/util'>;
}
declare module 'babel-plugin-transform-regenerator/lib/visit.js' {
  declare module.exports: $Exports<'babel-plugin-transform-regenerator/lib/visit'>;
}
declare module 'babel-plugin-transform-regenerator/src/emit.js' {
  declare module.exports: $Exports<'babel-plugin-transform-regenerator/src/emit'>;
}
declare module 'babel-plugin-transform-regenerator/src/hoist.js' {
  declare module.exports: $Exports<'babel-plugin-transform-regenerator/src/hoist'>;
}
declare module 'babel-plugin-transform-regenerator/src/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-regenerator/src/index'>;
}
declare module 'babel-plugin-transform-regenerator/src/leap.js' {
  declare module.exports: $Exports<'babel-plugin-transform-regenerator/src/leap'>;
}
declare module 'babel-plugin-transform-regenerator/src/meta.js' {
  declare module.exports: $Exports<'babel-plugin-transform-regenerator/src/meta'>;
}
declare module 'babel-plugin-transform-regenerator/src/util.js' {
  declare module.exports: $Exports<'babel-plugin-transform-regenerator/src/util'>;
}
declare module 'babel-plugin-transform-regenerator/src/visit.js' {
  declare module.exports: $Exports<'babel-plugin-transform-regenerator/src/visit'>;
}
