// flow-typed signature: 1437cf5fc44a974327ec63213b7b30b4
// flow-typed version: <<STUB>>/babel-plugin-detective_v^2.0.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-detective'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-detective' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-detective/wrap-listener' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-detective/index' {
  declare module.exports: $Exports<'babel-plugin-detective'>;
}
declare module 'babel-plugin-detective/index.js' {
  declare module.exports: $Exports<'babel-plugin-detective'>;
}
declare module 'babel-plugin-detective/wrap-listener.js' {
  declare module.exports: $Exports<'babel-plugin-detective/wrap-listener'>;
}
