// flow-typed signature: df67eeea6586020a5e79c02e7183399a
// flow-typed version: <<STUB>>/babel-plugin-codegen_v^1.2.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-codegen'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-codegen' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-codegen/dist/get-replacement' {
  declare module.exports: any;
}

declare module 'babel-plugin-codegen/dist/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-codegen/dist/macro' {
  declare module.exports: any;
}

declare module 'babel-plugin-codegen/dist/replace' {
  declare module.exports: any;
}

declare module 'babel-plugin-codegen/macro' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-codegen/dist/get-replacement.js' {
  declare module.exports: $Exports<'babel-plugin-codegen/dist/get-replacement'>;
}
declare module 'babel-plugin-codegen/dist/index.js' {
  declare module.exports: $Exports<'babel-plugin-codegen/dist/index'>;
}
declare module 'babel-plugin-codegen/dist/macro.js' {
  declare module.exports: $Exports<'babel-plugin-codegen/dist/macro'>;
}
declare module 'babel-plugin-codegen/dist/replace.js' {
  declare module.exports: $Exports<'babel-plugin-codegen/dist/replace'>;
}
declare module 'babel-plugin-codegen/macro.js' {
  declare module.exports: $Exports<'babel-plugin-codegen/macro'>;
}
