// flow-typed signature: bb6129bb5a029041923809cb7fe6097b
// flow-typed version: <<STUB>>/babel-helper-vue-jsx-merge-props_v^2.0.2/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-helper-vue-jsx-merge-props'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-helper-vue-jsx-merge-props' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'babel-helper-vue-jsx-merge-props/index' {
  declare module.exports: $Exports<'babel-helper-vue-jsx-merge-props'>;
}
declare module 'babel-helper-vue-jsx-merge-props/index.js' {
  declare module.exports: $Exports<'babel-helper-vue-jsx-merge-props'>;
}
