// flow-typed signature: 0a57823e1042fc6faa44d86f7154faaa
// flow-typed version: <<STUB>>/babel-plugin-transform-react-constant-elements_v6.9.1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-react-constant-elements'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-react-constant-elements' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-react-constant-elements/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-react-constant-elements/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-react-constant-elements/lib/index'>;
}
