// flow-typed signature: 4e346aceff2e3af0153c3dac3f9900f2
// flow-typed version: <<STUB>>/babel-plugin-system-import-transformer_v3.1.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-system-import-transformer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-system-import-transformer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-system-import-transformer/dist/babelArgumentProvider' {
  declare module.exports: any;
}

declare module 'babel-plugin-system-import-transformer/dist/globalObjectHelper' {
  declare module.exports: any;
}

declare module 'babel-plugin-system-import-transformer/dist/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-system-import-transformer/dist/moduleImportHelper' {
  declare module.exports: any;
}

declare module 'babel-plugin-system-import-transformer/dist/promiseUtils' {
  declare module.exports: any;
}

declare module 'babel-plugin-system-import-transformer/dist/SystemImportExpressionTransformer' {
  declare module.exports: any;
}

declare module 'babel-plugin-system-import-transformer/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-system-import-transformer/dist/babelArgumentProvider.js' {
  declare module.exports: $Exports<
    'babel-plugin-system-import-transformer/dist/babelArgumentProvider'
  >;
}
declare module 'babel-plugin-system-import-transformer/dist/globalObjectHelper.js' {
  declare module.exports: $Exports<
    'babel-plugin-system-import-transformer/dist/globalObjectHelper'
  >;
}
declare module 'babel-plugin-system-import-transformer/dist/index.js' {
  declare module.exports: $Exports<
    'babel-plugin-system-import-transformer/dist/index'
  >;
}
declare module 'babel-plugin-system-import-transformer/dist/moduleImportHelper.js' {
  declare module.exports: $Exports<
    'babel-plugin-system-import-transformer/dist/moduleImportHelper'
  >;
}
declare module 'babel-plugin-system-import-transformer/dist/promiseUtils.js' {
  declare module.exports: $Exports<
    'babel-plugin-system-import-transformer/dist/promiseUtils'
  >;
}
declare module 'babel-plugin-system-import-transformer/dist/SystemImportExpressionTransformer.js' {
  declare module.exports: $Exports<
    'babel-plugin-system-import-transformer/dist/SystemImportExpressionTransformer'
  >;
}
declare module 'babel-plugin-system-import-transformer/dist/utils.js' {
  declare module.exports: $Exports<
    'babel-plugin-system-import-transformer/dist/utils'
  >;
}
