// flow-typed signature: 2e98f59034206d62f8449935f5fead2a
// flow-typed version: <<STUB>>/babel-standalone_v^6.15.0/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-standalone'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-standalone' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-standalone/babel' {
  declare module.exports: any;
}

declare module 'babel-standalone/babel.min' {
  declare module.exports: any;
}

declare module 'babel-standalone/src/babili' {
  declare module.exports: any;
}

declare module 'babel-standalone/src/index' {
  declare module.exports: any;
}

declare module 'babel-standalone/src/transformScriptTags' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-standalone/babel.js' {
  declare module.exports: $Exports<'babel-standalone/babel'>;
}
declare module 'babel-standalone/babel.min.js' {
  declare module.exports: $Exports<'babel-standalone/babel.min'>;
}
declare module 'babel-standalone/src/babili.js' {
  declare module.exports: $Exports<'babel-standalone/src/babili'>;
}
declare module 'babel-standalone/src/index.js' {
  declare module.exports: $Exports<'babel-standalone/src/index'>;
}
declare module 'babel-standalone/src/transformScriptTags.js' {
  declare module.exports: $Exports<'babel-standalone/src/transformScriptTags'>;
}
