// flow-typed signature: 59e95423ac3053a82bfd1f2bfdb000c5
// flow-typed version: <<STUB>>/babel-plugin-dynamic-import-node_v^1.0.2/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-dynamic-import-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-dynamic-import-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-dynamic-import-node/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-dynamic-import-node/lib/index.js' {
  declare module.exports: $Exports<
    'babel-plugin-dynamic-import-node/lib/index'
  >;
}
