// flow-typed signature: 6f0c844069e3798f8d24aa9270b18da0
// flow-typed version: <<STUB>>/base64-loader_v^1.0.0/flow_v0.43.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'base64-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'base64-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'base64-loader/index' {
  declare module.exports: $Exports<'base64-loader'>;
}
declare module 'base64-loader/index.js' {
  declare module.exports: $Exports<'base64-loader'>;
}
