// flow-typed signature: 5786c177e70122fb2a8476804c389d02
// flow-typed version: <<STUB>>/browser-resolve_v^1.11.2/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'browser-resolve'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'browser-resolve' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'browser-resolve/empty' {
  declare module.exports: any;
}

// Filename aliases
declare module 'browser-resolve/empty.js' {
  declare module.exports: $Exports<'browser-resolve/empty'>;
}
declare module 'browser-resolve/index' {
  declare module.exports: $Exports<'browser-resolve'>;
}
declare module 'browser-resolve/index.js' {
  declare module.exports: $Exports<'browser-resolve'>;
}
