// flow-typed signature: 2fc0d2e93dbcba2eaed013f9c14029b5
// flow-typed version: <<STUB>>/browser-resolve_vCompuIves/node-browser-resolve/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'browser-resolve'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'browser-resolve' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'browser-resolve/empty' {
  declare module.exports: any;
}

declare module 'browser-resolve/example/builtin' {
  declare module.exports: any;
}

declare module 'browser-resolve/example/custom-chromeapp' {
  declare module.exports: any;
}

declare module 'browser-resolve/example/custom' {
  declare module.exports: any;
}

declare module 'browser-resolve/example/custom/custom-chromeapp' {
  declare module.exports: any;
}

declare module 'browser-resolve/example/custom/custom' {
  declare module.exports: any;
}

declare module 'browser-resolve/example/custom/main' {
  declare module.exports: any;
}

declare module 'browser-resolve/example/resolve' {
  declare module.exports: any;
}

declare module 'browser-resolve/example/skip' {
  declare module.exports: any;
}

declare module 'browser-resolve/example/skip/main' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/core-sync' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/core' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/ext' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/false-sync' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/false' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/foo' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/alt-browser-field/chromeapp-direct' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/alt-browser-field/chromeapp' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/alt-browser-field/direct' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/alt-browser-field/foo' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/alt-browser-field/index' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/alt-browser-field/url-browser' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/alt-browser-field/url-chromeapp' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/false/fake' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/false/node_modules/ignore-me/index' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/module-a/index' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/module-b/main' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/module-c/bar' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/module-c/browser' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/module-c/chromeapp' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/module-c/foo' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/module-c/main' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/module-d/browser' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/module-d/main' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/module-e/browser' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/module-e/foo' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/module-e/main' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/module-f/lib/browser' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/module-f/lib/foo' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/module-f/lib/main' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/module-g/foobar-browser' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/module-g/index' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/module-h/index' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/module-i/index' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/module-j/index' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/module-k/browser' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/module-k/index' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/module-l/browser-direct' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/module-l/browser' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/module-l/index' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/module-m/lib/hide' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/module-m/lib/index' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/module-n/browser-foo' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/module-n/index' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/module-o/main' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/module-o/x' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/module-p/x' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/module-q/x' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/module-r/x' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/module-s/x' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/override-engine-shim/index' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/override-engine-shim/url-browser' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/fixtures/node_modules/toString/index' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/local-coffee' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/local-sync' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/local' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/modules-coffee' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/modules-sync' {
  declare module.exports: any;
}

declare module 'browser-resolve/test/modules' {
  declare module.exports: any;
}

// Filename aliases
declare module 'browser-resolve/empty.js' {
  declare module.exports: $Exports<'browser-resolve/empty'>;
}
declare module 'browser-resolve/example/builtin.js' {
  declare module.exports: $Exports<'browser-resolve/example/builtin'>;
}
declare module 'browser-resolve/example/custom-chromeapp.js' {
  declare module.exports: $Exports<'browser-resolve/example/custom-chromeapp'>;
}
declare module 'browser-resolve/example/custom.js' {
  declare module.exports: $Exports<'browser-resolve/example/custom'>;
}
declare module 'browser-resolve/example/custom/custom-chromeapp.js' {
  declare module.exports: $Exports<
    'browser-resolve/example/custom/custom-chromeapp'
  >;
}
declare module 'browser-resolve/example/custom/custom.js' {
  declare module.exports: $Exports<'browser-resolve/example/custom/custom'>;
}
declare module 'browser-resolve/example/custom/main.js' {
  declare module.exports: $Exports<'browser-resolve/example/custom/main'>;
}
declare module 'browser-resolve/example/resolve.js' {
  declare module.exports: $Exports<'browser-resolve/example/resolve'>;
}
declare module 'browser-resolve/example/skip.js' {
  declare module.exports: $Exports<'browser-resolve/example/skip'>;
}
declare module 'browser-resolve/example/skip/main.js' {
  declare module.exports: $Exports<'browser-resolve/example/skip/main'>;
}
declare module 'browser-resolve/index' {
  declare module.exports: $Exports<'browser-resolve'>;
}
declare module 'browser-resolve/index.js' {
  declare module.exports: $Exports<'browser-resolve'>;
}
declare module 'browser-resolve/test/core-sync.js' {
  declare module.exports: $Exports<'browser-resolve/test/core-sync'>;
}
declare module 'browser-resolve/test/core.js' {
  declare module.exports: $Exports<'browser-resolve/test/core'>;
}
declare module 'browser-resolve/test/ext.js' {
  declare module.exports: $Exports<'browser-resolve/test/ext'>;
}
declare module 'browser-resolve/test/false-sync.js' {
  declare module.exports: $Exports<'browser-resolve/test/false-sync'>;
}
declare module 'browser-resolve/test/false.js' {
  declare module.exports: $Exports<'browser-resolve/test/false'>;
}
declare module 'browser-resolve/test/fixtures/foo.js' {
  declare module.exports: $Exports<'browser-resolve/test/fixtures/foo'>;
}
declare module 'browser-resolve/test/fixtures/node_modules/alt-browser-field/chromeapp-direct.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/alt-browser-field/chromeapp-direct'
  >;
}
declare module 'browser-resolve/test/fixtures/node_modules/alt-browser-field/chromeapp.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/alt-browser-field/chromeapp'
  >;
}
declare module 'browser-resolve/test/fixtures/node_modules/alt-browser-field/direct.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/alt-browser-field/direct'
  >;
}
declare module 'browser-resolve/test/fixtures/node_modules/alt-browser-field/foo.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/alt-browser-field/foo'
  >;
}
declare module 'browser-resolve/test/fixtures/node_modules/alt-browser-field/index.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/alt-browser-field/index'
  >;
}
declare module 'browser-resolve/test/fixtures/node_modules/alt-browser-field/url-browser.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/alt-browser-field/url-browser'
  >;
}
declare module 'browser-resolve/test/fixtures/node_modules/alt-browser-field/url-chromeapp.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/alt-browser-field/url-chromeapp'
  >;
}
declare module 'browser-resolve/test/fixtures/node_modules/false/fake.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/false/fake'
  >;
}
declare module 'browser-resolve/test/fixtures/node_modules/false/node_modules/ignore-me/index.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/false/node_modules/ignore-me/index'
  >;
}
declare module 'browser-resolve/test/fixtures/node_modules/module-a/index.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/module-a/index'
  >;
}
declare module 'browser-resolve/test/fixtures/node_modules/module-b/main.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/module-b/main'
  >;
}
declare module 'browser-resolve/test/fixtures/node_modules/module-c/bar.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/module-c/bar'
  >;
}
declare module 'browser-resolve/test/fixtures/node_modules/module-c/browser.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/module-c/browser'
  >;
}
declare module 'browser-resolve/test/fixtures/node_modules/module-c/chromeapp.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/module-c/chromeapp'
  >;
}
declare module 'browser-resolve/test/fixtures/node_modules/module-c/foo.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/module-c/foo'
  >;
}
declare module 'browser-resolve/test/fixtures/node_modules/module-c/main.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/module-c/main'
  >;
}
declare module 'browser-resolve/test/fixtures/node_modules/module-d/browser.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/module-d/browser'
  >;
}
declare module 'browser-resolve/test/fixtures/node_modules/module-d/main.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/module-d/main'
  >;
}
declare module 'browser-resolve/test/fixtures/node_modules/module-e/browser.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/module-e/browser'
  >;
}
declare module 'browser-resolve/test/fixtures/node_modules/module-e/foo.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/module-e/foo'
  >;
}
declare module 'browser-resolve/test/fixtures/node_modules/module-e/main.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/module-e/main'
  >;
}
declare module 'browser-resolve/test/fixtures/node_modules/module-f/lib/browser.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/module-f/lib/browser'
  >;
}
declare module 'browser-resolve/test/fixtures/node_modules/module-f/lib/foo.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/module-f/lib/foo'
  >;
}
declare module 'browser-resolve/test/fixtures/node_modules/module-f/lib/main.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/module-f/lib/main'
  >;
}
declare module 'browser-resolve/test/fixtures/node_modules/module-g/foobar-browser.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/module-g/foobar-browser'
  >;
}
declare module 'browser-resolve/test/fixtures/node_modules/module-g/index.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/module-g/index'
  >;
}
declare module 'browser-resolve/test/fixtures/node_modules/module-h/index.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/module-h/index'
  >;
}
declare module 'browser-resolve/test/fixtures/node_modules/module-i/index.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/module-i/index'
  >;
}
declare module 'browser-resolve/test/fixtures/node_modules/module-j/index.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/module-j/index'
  >;
}
declare module 'browser-resolve/test/fixtures/node_modules/module-k/browser.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/module-k/browser'
  >;
}
declare module 'browser-resolve/test/fixtures/node_modules/module-k/index.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/module-k/index'
  >;
}
declare module 'browser-resolve/test/fixtures/node_modules/module-l/browser-direct.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/module-l/browser-direct'
  >;
}
declare module 'browser-resolve/test/fixtures/node_modules/module-l/browser.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/module-l/browser'
  >;
}
declare module 'browser-resolve/test/fixtures/node_modules/module-l/index.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/module-l/index'
  >;
}
declare module 'browser-resolve/test/fixtures/node_modules/module-m/lib/hide.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/module-m/lib/hide'
  >;
}
declare module 'browser-resolve/test/fixtures/node_modules/module-m/lib/index.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/module-m/lib/index'
  >;
}
declare module 'browser-resolve/test/fixtures/node_modules/module-n/browser-foo.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/module-n/browser-foo'
  >;
}
declare module 'browser-resolve/test/fixtures/node_modules/module-n/index.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/module-n/index'
  >;
}
declare module 'browser-resolve/test/fixtures/node_modules/module-o/main.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/module-o/main'
  >;
}
declare module 'browser-resolve/test/fixtures/node_modules/module-o/x.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/module-o/x'
  >;
}
declare module 'browser-resolve/test/fixtures/node_modules/module-p/x.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/module-p/x'
  >;
}
declare module 'browser-resolve/test/fixtures/node_modules/module-q/x.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/module-q/x'
  >;
}
declare module 'browser-resolve/test/fixtures/node_modules/module-r/x.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/module-r/x'
  >;
}
declare module 'browser-resolve/test/fixtures/node_modules/module-s/x.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/module-s/x'
  >;
}
declare module 'browser-resolve/test/fixtures/node_modules/override-engine-shim/index.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/override-engine-shim/index'
  >;
}
declare module 'browser-resolve/test/fixtures/node_modules/override-engine-shim/url-browser.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/override-engine-shim/url-browser'
  >;
}
declare module 'browser-resolve/test/fixtures/node_modules/toString/index.js' {
  declare module.exports: $Exports<
    'browser-resolve/test/fixtures/node_modules/toString/index'
  >;
}
declare module 'browser-resolve/test/local-coffee.js' {
  declare module.exports: $Exports<'browser-resolve/test/local-coffee'>;
}
declare module 'browser-resolve/test/local-sync.js' {
  declare module.exports: $Exports<'browser-resolve/test/local-sync'>;
}
declare module 'browser-resolve/test/local.js' {
  declare module.exports: $Exports<'browser-resolve/test/local'>;
}
declare module 'browser-resolve/test/modules-coffee.js' {
  declare module.exports: $Exports<'browser-resolve/test/modules-coffee'>;
}
declare module 'browser-resolve/test/modules-sync.js' {
  declare module.exports: $Exports<'browser-resolve/test/modules-sync'>;
}
declare module 'browser-resolve/test/modules.js' {
  declare module.exports: $Exports<'browser-resolve/test/modules'>;
}
