// flow-typed signature: 7cc113c2bd68cd4554352ad0be461a3c
// flow-typed version: <<STUB>>/buffer-loader_v^0.0.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'buffer-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'buffer-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'buffer-loader/index' {
  declare module.exports: $Exports<'buffer-loader'>;
}
declare module 'buffer-loader/index.js' {
  declare module.exports: $Exports<'buffer-loader'>;
}
