// flow-typed signature: 53b2cdc72af4c95910ab63bc84bbeb85
// flow-typed version: <<STUB>>/buffer-loader_v^0.0.1/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'buffer-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'buffer-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'buffer-loader/index' {
  declare module.exports: $Exports<'buffer-loader'>;
}
declare module 'buffer-loader/index.js' {
  declare module.exports: $Exports<'buffer-loader'>;
}
