// flow-typed signature: 1814c118437c25f5d6a4633f7b1b6f88
// flow-typed version: <<STUB>>/cerebral_v^4.0.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cerebral'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cerebral' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cerebral/es/BaseController' {
  declare module.exports: any;
}

declare module 'cerebral/es/BaseModel' {
  declare module.exports: any;
}

declare module 'cerebral/es/CerebralError' {
  declare module.exports: any;
}

declare module 'cerebral/es/Compute' {
  declare module.exports: any;
}

declare module 'cerebral/es/Controller' {
  declare module.exports: any;
}

declare module 'cerebral/es/DependencyStore' {
  declare module.exports: any;
}

declare module 'cerebral/es/DependencyTracker' {
  declare module.exports: any;
}

declare module 'cerebral/es/devtools/index' {
  declare module.exports: any;
}

declare module 'cerebral/es/index' {
  declare module.exports: any;
}

declare module 'cerebral/es/internal' {
  declare module.exports: any;
}

declare module 'cerebral/es/Model' {
  declare module.exports: any;
}

declare module 'cerebral/es/Module' {
  declare module.exports: any;
}

declare module 'cerebral/es/operators/concat' {
  declare module.exports: any;
}

declare module 'cerebral/es/operators/debounce' {
  declare module.exports: any;
}

declare module 'cerebral/es/operators/equals' {
  declare module.exports: any;
}

declare module 'cerebral/es/operators/increment' {
  declare module.exports: any;
}

declare module 'cerebral/es/operators/index' {
  declare module.exports: any;
}

declare module 'cerebral/es/operators/merge' {
  declare module.exports: any;
}

declare module 'cerebral/es/operators/pop' {
  declare module.exports: any;
}

declare module 'cerebral/es/operators/push' {
  declare module.exports: any;
}

declare module 'cerebral/es/operators/set' {
  declare module.exports: any;
}

declare module 'cerebral/es/operators/shift' {
  declare module.exports: any;
}

declare module 'cerebral/es/operators/splice' {
  declare module.exports: any;
}

declare module 'cerebral/es/operators/toggle' {
  declare module.exports: any;
}

declare module 'cerebral/es/operators/unset' {
  declare module.exports: any;
}

declare module 'cerebral/es/operators/unshift' {
  declare module.exports: any;
}

declare module 'cerebral/es/operators/wait' {
  declare module.exports: any;
}

declare module 'cerebral/es/operators/when' {
  declare module.exports: any;
}

declare module 'cerebral/es/Provider' {
  declare module.exports: any;
}

declare module 'cerebral/es/providers/Debugger' {
  declare module.exports: any;
}

declare module 'cerebral/es/providers/index' {
  declare module.exports: any;
}

declare module 'cerebral/es/providers/Module' {
  declare module.exports: any;
}

declare module 'cerebral/es/providers/Recorder' {
  declare module.exports: any;
}

declare module 'cerebral/es/providers/State' {
  declare module.exports: any;
}

declare module 'cerebral/es/tags/index' {
  declare module.exports: any;
}

declare module 'cerebral/es/test/index' {
  declare module.exports: any;
}

declare module 'cerebral/es/UniversalController' {
  declare module.exports: any;
}

declare module 'cerebral/es/utils' {
  declare module.exports: any;
}

declare module 'cerebral/es/View' {
  declare module.exports: any;
}

declare module 'cerebral/lib/BaseController' {
  declare module.exports: any;
}

declare module 'cerebral/lib/BaseModel' {
  declare module.exports: any;
}

declare module 'cerebral/lib/CerebralError' {
  declare module.exports: any;
}

declare module 'cerebral/lib/Compute' {
  declare module.exports: any;
}

declare module 'cerebral/lib/Controller' {
  declare module.exports: any;
}

declare module 'cerebral/lib/DependencyStore' {
  declare module.exports: any;
}

declare module 'cerebral/lib/DependencyTracker' {
  declare module.exports: any;
}

declare module 'cerebral/lib/devtools/index' {
  declare module.exports: any;
}

declare module 'cerebral/lib/index' {
  declare module.exports: any;
}

declare module 'cerebral/lib/internal' {
  declare module.exports: any;
}

declare module 'cerebral/lib/Model' {
  declare module.exports: any;
}

declare module 'cerebral/lib/Module' {
  declare module.exports: any;
}

declare module 'cerebral/lib/operators/concat' {
  declare module.exports: any;
}

declare module 'cerebral/lib/operators/debounce' {
  declare module.exports: any;
}

declare module 'cerebral/lib/operators/equals' {
  declare module.exports: any;
}

declare module 'cerebral/lib/operators/increment' {
  declare module.exports: any;
}

declare module 'cerebral/lib/operators/index' {
  declare module.exports: any;
}

declare module 'cerebral/lib/operators/merge' {
  declare module.exports: any;
}

declare module 'cerebral/lib/operators/pop' {
  declare module.exports: any;
}

declare module 'cerebral/lib/operators/push' {
  declare module.exports: any;
}

declare module 'cerebral/lib/operators/set' {
  declare module.exports: any;
}

declare module 'cerebral/lib/operators/shift' {
  declare module.exports: any;
}

declare module 'cerebral/lib/operators/splice' {
  declare module.exports: any;
}

declare module 'cerebral/lib/operators/toggle' {
  declare module.exports: any;
}

declare module 'cerebral/lib/operators/unset' {
  declare module.exports: any;
}

declare module 'cerebral/lib/operators/unshift' {
  declare module.exports: any;
}

declare module 'cerebral/lib/operators/wait' {
  declare module.exports: any;
}

declare module 'cerebral/lib/operators/when' {
  declare module.exports: any;
}

declare module 'cerebral/lib/Provider' {
  declare module.exports: any;
}

declare module 'cerebral/lib/providers/Debugger' {
  declare module.exports: any;
}

declare module 'cerebral/lib/providers/index' {
  declare module.exports: any;
}

declare module 'cerebral/lib/providers/Module' {
  declare module.exports: any;
}

declare module 'cerebral/lib/providers/Recorder' {
  declare module.exports: any;
}

declare module 'cerebral/lib/providers/State' {
  declare module.exports: any;
}

declare module 'cerebral/lib/tags/index' {
  declare module.exports: any;
}

declare module 'cerebral/lib/test/index' {
  declare module.exports: any;
}

declare module 'cerebral/lib/UniversalController' {
  declare module.exports: any;
}

declare module 'cerebral/lib/utils' {
  declare module.exports: any;
}

declare module 'cerebral/lib/View' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cerebral/es/BaseController.js' {
  declare module.exports: $Exports<'cerebral/es/BaseController'>;
}
declare module 'cerebral/es/BaseModel.js' {
  declare module.exports: $Exports<'cerebral/es/BaseModel'>;
}
declare module 'cerebral/es/CerebralError.js' {
  declare module.exports: $Exports<'cerebral/es/CerebralError'>;
}
declare module 'cerebral/es/Compute.js' {
  declare module.exports: $Exports<'cerebral/es/Compute'>;
}
declare module 'cerebral/es/Controller.js' {
  declare module.exports: $Exports<'cerebral/es/Controller'>;
}
declare module 'cerebral/es/DependencyStore.js' {
  declare module.exports: $Exports<'cerebral/es/DependencyStore'>;
}
declare module 'cerebral/es/DependencyTracker.js' {
  declare module.exports: $Exports<'cerebral/es/DependencyTracker'>;
}
declare module 'cerebral/es/devtools/index.js' {
  declare module.exports: $Exports<'cerebral/es/devtools/index'>;
}
declare module 'cerebral/es/index.js' {
  declare module.exports: $Exports<'cerebral/es/index'>;
}
declare module 'cerebral/es/internal.js' {
  declare module.exports: $Exports<'cerebral/es/internal'>;
}
declare module 'cerebral/es/Model.js' {
  declare module.exports: $Exports<'cerebral/es/Model'>;
}
declare module 'cerebral/es/Module.js' {
  declare module.exports: $Exports<'cerebral/es/Module'>;
}
declare module 'cerebral/es/operators/concat.js' {
  declare module.exports: $Exports<'cerebral/es/operators/concat'>;
}
declare module 'cerebral/es/operators/debounce.js' {
  declare module.exports: $Exports<'cerebral/es/operators/debounce'>;
}
declare module 'cerebral/es/operators/equals.js' {
  declare module.exports: $Exports<'cerebral/es/operators/equals'>;
}
declare module 'cerebral/es/operators/increment.js' {
  declare module.exports: $Exports<'cerebral/es/operators/increment'>;
}
declare module 'cerebral/es/operators/index.js' {
  declare module.exports: $Exports<'cerebral/es/operators/index'>;
}
declare module 'cerebral/es/operators/merge.js' {
  declare module.exports: $Exports<'cerebral/es/operators/merge'>;
}
declare module 'cerebral/es/operators/pop.js' {
  declare module.exports: $Exports<'cerebral/es/operators/pop'>;
}
declare module 'cerebral/es/operators/push.js' {
  declare module.exports: $Exports<'cerebral/es/operators/push'>;
}
declare module 'cerebral/es/operators/set.js' {
  declare module.exports: $Exports<'cerebral/es/operators/set'>;
}
declare module 'cerebral/es/operators/shift.js' {
  declare module.exports: $Exports<'cerebral/es/operators/shift'>;
}
declare module 'cerebral/es/operators/splice.js' {
  declare module.exports: $Exports<'cerebral/es/operators/splice'>;
}
declare module 'cerebral/es/operators/toggle.js' {
  declare module.exports: $Exports<'cerebral/es/operators/toggle'>;
}
declare module 'cerebral/es/operators/unset.js' {
  declare module.exports: $Exports<'cerebral/es/operators/unset'>;
}
declare module 'cerebral/es/operators/unshift.js' {
  declare module.exports: $Exports<'cerebral/es/operators/unshift'>;
}
declare module 'cerebral/es/operators/wait.js' {
  declare module.exports: $Exports<'cerebral/es/operators/wait'>;
}
declare module 'cerebral/es/operators/when.js' {
  declare module.exports: $Exports<'cerebral/es/operators/when'>;
}
declare module 'cerebral/es/Provider.js' {
  declare module.exports: $Exports<'cerebral/es/Provider'>;
}
declare module 'cerebral/es/providers/Debugger.js' {
  declare module.exports: $Exports<'cerebral/es/providers/Debugger'>;
}
declare module 'cerebral/es/providers/index.js' {
  declare module.exports: $Exports<'cerebral/es/providers/index'>;
}
declare module 'cerebral/es/providers/Module.js' {
  declare module.exports: $Exports<'cerebral/es/providers/Module'>;
}
declare module 'cerebral/es/providers/Recorder.js' {
  declare module.exports: $Exports<'cerebral/es/providers/Recorder'>;
}
declare module 'cerebral/es/providers/State.js' {
  declare module.exports: $Exports<'cerebral/es/providers/State'>;
}
declare module 'cerebral/es/tags/index.js' {
  declare module.exports: $Exports<'cerebral/es/tags/index'>;
}
declare module 'cerebral/es/test/index.js' {
  declare module.exports: $Exports<'cerebral/es/test/index'>;
}
declare module 'cerebral/es/UniversalController.js' {
  declare module.exports: $Exports<'cerebral/es/UniversalController'>;
}
declare module 'cerebral/es/utils.js' {
  declare module.exports: $Exports<'cerebral/es/utils'>;
}
declare module 'cerebral/es/View.js' {
  declare module.exports: $Exports<'cerebral/es/View'>;
}
declare module 'cerebral/index' {
  declare module.exports: $Exports<'cerebral'>;
}
declare module 'cerebral/index.js' {
  declare module.exports: $Exports<'cerebral'>;
}
declare module 'cerebral/lib/BaseController.js' {
  declare module.exports: $Exports<'cerebral/lib/BaseController'>;
}
declare module 'cerebral/lib/BaseModel.js' {
  declare module.exports: $Exports<'cerebral/lib/BaseModel'>;
}
declare module 'cerebral/lib/CerebralError.js' {
  declare module.exports: $Exports<'cerebral/lib/CerebralError'>;
}
declare module 'cerebral/lib/Compute.js' {
  declare module.exports: $Exports<'cerebral/lib/Compute'>;
}
declare module 'cerebral/lib/Controller.js' {
  declare module.exports: $Exports<'cerebral/lib/Controller'>;
}
declare module 'cerebral/lib/DependencyStore.js' {
  declare module.exports: $Exports<'cerebral/lib/DependencyStore'>;
}
declare module 'cerebral/lib/DependencyTracker.js' {
  declare module.exports: $Exports<'cerebral/lib/DependencyTracker'>;
}
declare module 'cerebral/lib/devtools/index.js' {
  declare module.exports: $Exports<'cerebral/lib/devtools/index'>;
}
declare module 'cerebral/lib/index.js' {
  declare module.exports: $Exports<'cerebral/lib/index'>;
}
declare module 'cerebral/lib/internal.js' {
  declare module.exports: $Exports<'cerebral/lib/internal'>;
}
declare module 'cerebral/lib/Model.js' {
  declare module.exports: $Exports<'cerebral/lib/Model'>;
}
declare module 'cerebral/lib/Module.js' {
  declare module.exports: $Exports<'cerebral/lib/Module'>;
}
declare module 'cerebral/lib/operators/concat.js' {
  declare module.exports: $Exports<'cerebral/lib/operators/concat'>;
}
declare module 'cerebral/lib/operators/debounce.js' {
  declare module.exports: $Exports<'cerebral/lib/operators/debounce'>;
}
declare module 'cerebral/lib/operators/equals.js' {
  declare module.exports: $Exports<'cerebral/lib/operators/equals'>;
}
declare module 'cerebral/lib/operators/increment.js' {
  declare module.exports: $Exports<'cerebral/lib/operators/increment'>;
}
declare module 'cerebral/lib/operators/index.js' {
  declare module.exports: $Exports<'cerebral/lib/operators/index'>;
}
declare module 'cerebral/lib/operators/merge.js' {
  declare module.exports: $Exports<'cerebral/lib/operators/merge'>;
}
declare module 'cerebral/lib/operators/pop.js' {
  declare module.exports: $Exports<'cerebral/lib/operators/pop'>;
}
declare module 'cerebral/lib/operators/push.js' {
  declare module.exports: $Exports<'cerebral/lib/operators/push'>;
}
declare module 'cerebral/lib/operators/set.js' {
  declare module.exports: $Exports<'cerebral/lib/operators/set'>;
}
declare module 'cerebral/lib/operators/shift.js' {
  declare module.exports: $Exports<'cerebral/lib/operators/shift'>;
}
declare module 'cerebral/lib/operators/splice.js' {
  declare module.exports: $Exports<'cerebral/lib/operators/splice'>;
}
declare module 'cerebral/lib/operators/toggle.js' {
  declare module.exports: $Exports<'cerebral/lib/operators/toggle'>;
}
declare module 'cerebral/lib/operators/unset.js' {
  declare module.exports: $Exports<'cerebral/lib/operators/unset'>;
}
declare module 'cerebral/lib/operators/unshift.js' {
  declare module.exports: $Exports<'cerebral/lib/operators/unshift'>;
}
declare module 'cerebral/lib/operators/wait.js' {
  declare module.exports: $Exports<'cerebral/lib/operators/wait'>;
}
declare module 'cerebral/lib/operators/when.js' {
  declare module.exports: $Exports<'cerebral/lib/operators/when'>;
}
declare module 'cerebral/lib/Provider.js' {
  declare module.exports: $Exports<'cerebral/lib/Provider'>;
}
declare module 'cerebral/lib/providers/Debugger.js' {
  declare module.exports: $Exports<'cerebral/lib/providers/Debugger'>;
}
declare module 'cerebral/lib/providers/index.js' {
  declare module.exports: $Exports<'cerebral/lib/providers/index'>;
}
declare module 'cerebral/lib/providers/Module.js' {
  declare module.exports: $Exports<'cerebral/lib/providers/Module'>;
}
declare module 'cerebral/lib/providers/Recorder.js' {
  declare module.exports: $Exports<'cerebral/lib/providers/Recorder'>;
}
declare module 'cerebral/lib/providers/State.js' {
  declare module.exports: $Exports<'cerebral/lib/providers/State'>;
}
declare module 'cerebral/lib/tags/index.js' {
  declare module.exports: $Exports<'cerebral/lib/tags/index'>;
}
declare module 'cerebral/lib/test/index.js' {
  declare module.exports: $Exports<'cerebral/lib/test/index'>;
}
declare module 'cerebral/lib/UniversalController.js' {
  declare module.exports: $Exports<'cerebral/lib/UniversalController'>;
}
declare module 'cerebral/lib/utils.js' {
  declare module.exports: $Exports<'cerebral/lib/utils'>;
}
declare module 'cerebral/lib/View.js' {
  declare module.exports: $Exports<'cerebral/lib/View'>;
}
