// flow-typed signature: d61e9bd460dc1ef77107860fb16e107a
// flow-typed version: <<STUB>>/codesandbox-api_v^0.0.14/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'codesandbox-api'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'codesandbox-api' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'codesandbox-api/compiled/actions/correction' {
  declare module.exports: any;
}

declare module 'codesandbox-api/compiled/actions/editor' {
  declare module.exports: any;
}

declare module 'codesandbox-api/compiled/actions/error' {
  declare module.exports: any;
}

declare module 'codesandbox-api/compiled/actions/glyph' {
  declare module.exports: any;
}

declare module 'codesandbox-api/compiled/actions/index' {
  declare module.exports: any;
}

declare module 'codesandbox-api/compiled/actions/notifications' {
  declare module.exports: any;
}

declare module 'codesandbox-api/compiled/actions/source/dependencies' {
  declare module.exports: any;
}

declare module 'codesandbox-api/compiled/actions/source/index' {
  declare module.exports: any;
}

declare module 'codesandbox-api/compiled/actions/source/modules' {
  declare module.exports: any;
}

declare module 'codesandbox-api/compiled/codesandbox' {
  declare module.exports: any;
}

declare module 'codesandbox-api/compiled/dispatcher/host' {
  declare module.exports: any;
}

declare module 'codesandbox-api/compiled/dispatcher/index' {
  declare module.exports: any;
}

declare module 'codesandbox-api/compiled/errors/index' {
  declare module.exports: any;
}

declare module 'codesandbox-api/dist/codesandbox.es5' {
  declare module.exports: any;
}

declare module 'codesandbox-api/dist/codesandbox.umd' {
  declare module.exports: any;
}

declare module 'codesandbox-api/rollup.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'codesandbox-api/compiled/actions/correction.js' {
  declare module.exports: $Exports<
    'codesandbox-api/compiled/actions/correction'
  >;
}
declare module 'codesandbox-api/compiled/actions/editor.js' {
  declare module.exports: $Exports<'codesandbox-api/compiled/actions/editor'>;
}
declare module 'codesandbox-api/compiled/actions/error.js' {
  declare module.exports: $Exports<'codesandbox-api/compiled/actions/error'>;
}
declare module 'codesandbox-api/compiled/actions/glyph.js' {
  declare module.exports: $Exports<'codesandbox-api/compiled/actions/glyph'>;
}
declare module 'codesandbox-api/compiled/actions/index.js' {
  declare module.exports: $Exports<'codesandbox-api/compiled/actions/index'>;
}
declare module 'codesandbox-api/compiled/actions/notifications.js' {
  declare module.exports: $Exports<
    'codesandbox-api/compiled/actions/notifications'
  >;
}
declare module 'codesandbox-api/compiled/actions/source/dependencies.js' {
  declare module.exports: $Exports<
    'codesandbox-api/compiled/actions/source/dependencies'
  >;
}
declare module 'codesandbox-api/compiled/actions/source/index.js' {
  declare module.exports: $Exports<
    'codesandbox-api/compiled/actions/source/index'
  >;
}
declare module 'codesandbox-api/compiled/actions/source/modules.js' {
  declare module.exports: $Exports<
    'codesandbox-api/compiled/actions/source/modules'
  >;
}
declare module 'codesandbox-api/compiled/codesandbox.js' {
  declare module.exports: $Exports<'codesandbox-api/compiled/codesandbox'>;
}
declare module 'codesandbox-api/compiled/dispatcher/host.js' {
  declare module.exports: $Exports<'codesandbox-api/compiled/dispatcher/host'>;
}
declare module 'codesandbox-api/compiled/dispatcher/index.js' {
  declare module.exports: $Exports<'codesandbox-api/compiled/dispatcher/index'>;
}
declare module 'codesandbox-api/compiled/errors/index.js' {
  declare module.exports: $Exports<'codesandbox-api/compiled/errors/index'>;
}
declare module 'codesandbox-api/dist/codesandbox.es5.js' {
  declare module.exports: $Exports<'codesandbox-api/dist/codesandbox.es5'>;
}
declare module 'codesandbox-api/dist/codesandbox.umd.js' {
  declare module.exports: $Exports<'codesandbox-api/dist/codesandbox.umd'>;
}
declare module 'codesandbox-api/rollup.config.js' {
  declare module.exports: $Exports<'codesandbox-api/rollup.config'>;
}
