// flow-typed signature: eebc65cb7328934ea7634614a51a3fdd
// flow-typed version: <<STUB>>/codesandbox-api_v0.0.6/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'codesandbox-api'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'codesandbox-api' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'codesandbox-api/dist/codesandbox.es5' {
  declare module.exports: any;
}

declare module 'codesandbox-api/dist/codesandbox.umd' {
  declare module.exports: any;
}

declare module 'codesandbox-api/dist/docs/assets/js/main' {
  declare module.exports: any;
}

declare module 'codesandbox-api/dist/docs/assets/js/search' {
  declare module.exports: any;
}

// Filename aliases
declare module 'codesandbox-api/dist/codesandbox.es5.js' {
  declare module.exports: $Exports<'codesandbox-api/dist/codesandbox.es5'>;
}
declare module 'codesandbox-api/dist/codesandbox.umd.js' {
  declare module.exports: $Exports<'codesandbox-api/dist/codesandbox.umd'>;
}
declare module 'codesandbox-api/dist/docs/assets/js/main.js' {
  declare module.exports: $Exports<'codesandbox-api/dist/docs/assets/js/main'>;
}
declare module 'codesandbox-api/dist/docs/assets/js/search.js' {
  declare module.exports: $Exports<
    'codesandbox-api/dist/docs/assets/js/search'
  >;
}
