// flow-typed signature: dcce7db434e6824c32d2616cada7ac06
// flow-typed version: <<STUB>>/copy-webpack-plugin_v^4.0.1/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'copy-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'copy-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'copy-webpack-plugin/backup' {
  declare module.exports: any;
}

declare module 'copy-webpack-plugin/dist/index' {
  declare module.exports: any;
}

declare module 'copy-webpack-plugin/dist/indexOld' {
  declare module.exports: any;
}

declare module 'copy-webpack-plugin/dist/path' {
  declare module.exports: any;
}

declare module 'copy-webpack-plugin/dist/preProcessPattern' {
  declare module.exports: any;
}

declare module 'copy-webpack-plugin/dist/processPattern' {
  declare module.exports: any;
}

declare module 'copy-webpack-plugin/dist/shouldIgnore' {
  declare module.exports: any;
}

declare module 'copy-webpack-plugin/dist/toLooksLikeDirectory' {
  declare module.exports: any;
}

declare module 'copy-webpack-plugin/dist/writeDirectoryToAssets' {
  declare module.exports: any;
}

declare module 'copy-webpack-plugin/dist/writeFile' {
  declare module.exports: any;
}

declare module 'copy-webpack-plugin/dist/writeFileToAssets' {
  declare module.exports: any;
}

// Filename aliases
declare module 'copy-webpack-plugin/backup.js' {
  declare module.exports: $Exports<'copy-webpack-plugin/backup'>;
}
declare module 'copy-webpack-plugin/dist/index.js' {
  declare module.exports: $Exports<'copy-webpack-plugin/dist/index'>;
}
declare module 'copy-webpack-plugin/dist/indexOld.js' {
  declare module.exports: $Exports<'copy-webpack-plugin/dist/indexOld'>;
}
declare module 'copy-webpack-plugin/dist/path.js' {
  declare module.exports: $Exports<'copy-webpack-plugin/dist/path'>;
}
declare module 'copy-webpack-plugin/dist/preProcessPattern.js' {
  declare module.exports: $Exports<
    'copy-webpack-plugin/dist/preProcessPattern'
  >;
}
declare module 'copy-webpack-plugin/dist/processPattern.js' {
  declare module.exports: $Exports<'copy-webpack-plugin/dist/processPattern'>;
}
declare module 'copy-webpack-plugin/dist/shouldIgnore.js' {
  declare module.exports: $Exports<'copy-webpack-plugin/dist/shouldIgnore'>;
}
declare module 'copy-webpack-plugin/dist/toLooksLikeDirectory.js' {
  declare module.exports: $Exports<
    'copy-webpack-plugin/dist/toLooksLikeDirectory'
  >;
}
declare module 'copy-webpack-plugin/dist/writeDirectoryToAssets.js' {
  declare module.exports: $Exports<
    'copy-webpack-plugin/dist/writeDirectoryToAssets'
  >;
}
declare module 'copy-webpack-plugin/dist/writeFile.js' {
  declare module.exports: $Exports<'copy-webpack-plugin/dist/writeFile'>;
}
declare module 'copy-webpack-plugin/dist/writeFileToAssets.js' {
  declare module.exports: $Exports<
    'copy-webpack-plugin/dist/writeFileToAssets'
  >;
}
