// flow-typed signature: 9a75a862155978df81463cb036b7bdd7
// flow-typed version: <<STUB>>/copy-webpack-plugin_v^4.0.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'copy-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'copy-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'copy-webpack-plugin/dist/index' {
  declare module.exports: any;
}

declare module 'copy-webpack-plugin/dist/preProcessPattern' {
  declare module.exports: any;
}

declare module 'copy-webpack-plugin/dist/processPattern' {
  declare module.exports: any;
}

declare module 'copy-webpack-plugin/dist/writeFile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'copy-webpack-plugin/dist/index.js' {
  declare module.exports: $Exports<'copy-webpack-plugin/dist/index'>;
}
declare module 'copy-webpack-plugin/dist/preProcessPattern.js' {
  declare module.exports: $Exports<
    'copy-webpack-plugin/dist/preProcessPattern'
  >;
}
declare module 'copy-webpack-plugin/dist/processPattern.js' {
  declare module.exports: $Exports<'copy-webpack-plugin/dist/processPattern'>;
}
declare module 'copy-webpack-plugin/dist/writeFile.js' {
  declare module.exports: $Exports<'copy-webpack-plugin/dist/writeFile'>;
}
