// flow-typed signature: 30ac6ac038ae5ffc4b587f5d7533daa5
// flow-typed version: <<STUB>>/css-modules-loader-core_v^1.1.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'css-modules-loader-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'css-modules-loader-core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'css-modules-loader-core/lib/file-system-loader' {
  declare module.exports: any;
}

declare module 'css-modules-loader-core/lib/index' {
  declare module.exports: any;
}

declare module 'css-modules-loader-core/lib/parser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'css-modules-loader-core/lib/file-system-loader.js' {
  declare module.exports: $Exports<
    'css-modules-loader-core/lib/file-system-loader'
  >;
}
declare module 'css-modules-loader-core/lib/index.js' {
  declare module.exports: $Exports<'css-modules-loader-core/lib/index'>;
}
declare module 'css-modules-loader-core/lib/parser.js' {
  declare module.exports: $Exports<'css-modules-loader-core/lib/parser'>;
}
