// flow-typed signature: 6149e9fa0ed5ca1d75feeb40c892da27
// flow-typed version: <<STUB>>/detect-port_v^1.0.7/flow_v0.43.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'detect-port'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'detect-port' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'detect-port/lib/detect-port' {
  declare module.exports: any;
}

// Filename aliases
declare module 'detect-port/index' {
  declare module.exports: $Exports<'detect-port'>;
}
declare module 'detect-port/index.js' {
  declare module.exports: $Exports<'detect-port'>;
}
declare module 'detect-port/lib/detect-port.js' {
  declare module.exports: $Exports<'detect-port/lib/detect-port'>;
}
