// flow-typed signature: 03b4dbc2924ccdc6209a7d106cb3eeaf
// flow-typed version: <<STUB>>/downshift_v^1.0.0-rc.14/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'downshift'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'downshift' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'downshift/dist/downshift.cjs' {
  declare module.exports: any;
}

declare module 'downshift/dist/downshift.esm' {
  declare module.exports: any;
}

declare module 'downshift/dist/downshift.umd' {
  declare module.exports: any;
}

declare module 'downshift/dist/downshift.umd.min' {
  declare module.exports: any;
}

declare module 'downshift/preact/dist/downshift.cjs' {
  declare module.exports: any;
}

declare module 'downshift/preact/dist/downshift.esm' {
  declare module.exports: any;
}

declare module 'downshift/preact/dist/downshift.umd' {
  declare module.exports: any;
}

declare module 'downshift/preact/dist/downshift.umd.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'downshift/dist/downshift.cjs.js' {
  declare module.exports: $Exports<'downshift/dist/downshift.cjs'>;
}
declare module 'downshift/dist/downshift.esm.js' {
  declare module.exports: $Exports<'downshift/dist/downshift.esm'>;
}
declare module 'downshift/dist/downshift.umd.js' {
  declare module.exports: $Exports<'downshift/dist/downshift.umd'>;
}
declare module 'downshift/dist/downshift.umd.min.js' {
  declare module.exports: $Exports<'downshift/dist/downshift.umd.min'>;
}
declare module 'downshift/preact/dist/downshift.cjs.js' {
  declare module.exports: $Exports<'downshift/preact/dist/downshift.cjs'>;
}
declare module 'downshift/preact/dist/downshift.esm.js' {
  declare module.exports: $Exports<'downshift/preact/dist/downshift.esm'>;
}
declare module 'downshift/preact/dist/downshift.umd.js' {
  declare module.exports: $Exports<'downshift/preact/dist/downshift.umd'>;
}
declare module 'downshift/preact/dist/downshift.umd.min.js' {
  declare module.exports: $Exports<'downshift/preact/dist/downshift.umd.min'>;
}
