// flow-typed signature: 2634b9c405b243554f4ba8a4c305d290
// flow-typed version: <<STUB>>/geniejs_v^0.5.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'geniejs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'geniejs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'geniejs/dist/geniejs.cjs' {
  declare module.exports: any;
}

declare module 'geniejs/dist/geniejs.es' {
  declare module.exports: any;
}

declare module 'geniejs/dist/geniejs.umd' {
  declare module.exports: any;
}

declare module 'geniejs/dist/geniejs.umd.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'geniejs/dist/geniejs.cjs.js' {
  declare module.exports: $Exports<'geniejs/dist/geniejs.cjs'>;
}
declare module 'geniejs/dist/geniejs.es.js' {
  declare module.exports: $Exports<'geniejs/dist/geniejs.es'>;
}
declare module 'geniejs/dist/geniejs.umd.js' {
  declare module.exports: $Exports<'geniejs/dist/geniejs.umd'>;
}
declare module 'geniejs/dist/geniejs.umd.min.js' {
  declare module.exports: $Exports<'geniejs/dist/geniejs.umd.min'>;
}
