// flow-typed signature: b090456b6e9764499e13e2876091d532
// flow-typed version: <<STUB>>/glamor_v^2.20.25/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'glamor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'glamor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'glamor/aphrodite' {
  declare module.exports: any;
}

declare module 'glamor/babel-hoist' {
  declare module.exports: any;
}

declare module 'glamor/babel' {
  declare module.exports: any;
}

declare module 'glamor/inline' {
  declare module.exports: any;
}

declare module 'glamor/jsxstyle' {
  declare module.exports: any;
}

declare module 'glamor/lib/aphrodite' {
  declare module.exports: any;
}

declare module 'glamor/lib/babel-hoist' {
  declare module.exports: any;
}

declare module 'glamor/lib/clean' {
  declare module.exports: any;
}

declare module 'glamor/lib/css/babel' {
  declare module.exports: any;
}

declare module 'glamor/lib/css/raw' {
  declare module.exports: any;
}

declare module 'glamor/lib/css/spec' {
  declare module.exports: any;
}

declare module 'glamor/lib/CSSPropertyOperations/CSSProperty' {
  declare module.exports: any;
}

declare module 'glamor/lib/CSSPropertyOperations/dangerousStyleValue' {
  declare module.exports: any;
}

declare module 'glamor/lib/CSSPropertyOperations/index' {
  declare module.exports: any;
}

declare module 'glamor/lib/hash' {
  declare module.exports: any;
}

declare module 'glamor/lib/index' {
  declare module.exports: any;
}

declare module 'glamor/lib/inline' {
  declare module.exports: any;
}

declare module 'glamor/lib/jsxstyle' {
  declare module.exports: any;
}

declare module 'glamor/lib/ous' {
  declare module.exports: any;
}

declare module 'glamor/lib/plugins' {
  declare module.exports: any;
}

declare module 'glamor/lib/prefixer' {
  declare module.exports: any;
}

declare module 'glamor/lib/react' {
  declare module.exports: any;
}

declare module 'glamor/lib/reset' {
  declare module.exports: any;
}

declare module 'glamor/lib/server' {
  declare module.exports: any;
}

declare module 'glamor/lib/sheet' {
  declare module.exports: any;
}

declare module 'glamor/lib/styled/index' {
  declare module.exports: any;
}

declare module 'glamor/lib/utils' {
  declare module.exports: any;
}

declare module 'glamor/ous' {
  declare module.exports: any;
}

declare module 'glamor/react' {
  declare module.exports: any;
}

declare module 'glamor/reset' {
  declare module.exports: any;
}

declare module 'glamor/server' {
  declare module.exports: any;
}

declare module 'glamor/styled' {
  declare module.exports: any;
}

declare module 'glamor/umd/index' {
  declare module.exports: any;
}

declare module 'glamor/umd/index.min' {
  declare module.exports: any;
}

declare module 'glamor/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'glamor/aphrodite.js' {
  declare module.exports: $Exports<'glamor/aphrodite'>;
}
declare module 'glamor/babel-hoist.js' {
  declare module.exports: $Exports<'glamor/babel-hoist'>;
}
declare module 'glamor/babel.js' {
  declare module.exports: $Exports<'glamor/babel'>;
}
declare module 'glamor/inline.js' {
  declare module.exports: $Exports<'glamor/inline'>;
}
declare module 'glamor/jsxstyle.js' {
  declare module.exports: $Exports<'glamor/jsxstyle'>;
}
declare module 'glamor/lib/aphrodite.js' {
  declare module.exports: $Exports<'glamor/lib/aphrodite'>;
}
declare module 'glamor/lib/babel-hoist.js' {
  declare module.exports: $Exports<'glamor/lib/babel-hoist'>;
}
declare module 'glamor/lib/clean.js' {
  declare module.exports: $Exports<'glamor/lib/clean'>;
}
declare module 'glamor/lib/css/babel.js' {
  declare module.exports: $Exports<'glamor/lib/css/babel'>;
}
declare module 'glamor/lib/css/raw.js' {
  declare module.exports: $Exports<'glamor/lib/css/raw'>;
}
declare module 'glamor/lib/css/spec.js' {
  declare module.exports: $Exports<'glamor/lib/css/spec'>;
}
declare module 'glamor/lib/CSSPropertyOperations/CSSProperty.js' {
  declare module.exports: $Exports<
    'glamor/lib/CSSPropertyOperations/CSSProperty'
  >;
}
declare module 'glamor/lib/CSSPropertyOperations/dangerousStyleValue.js' {
  declare module.exports: $Exports<
    'glamor/lib/CSSPropertyOperations/dangerousStyleValue'
  >;
}
declare module 'glamor/lib/CSSPropertyOperations/index.js' {
  declare module.exports: $Exports<'glamor/lib/CSSPropertyOperations/index'>;
}
declare module 'glamor/lib/hash.js' {
  declare module.exports: $Exports<'glamor/lib/hash'>;
}
declare module 'glamor/lib/index.js' {
  declare module.exports: $Exports<'glamor/lib/index'>;
}
declare module 'glamor/lib/inline.js' {
  declare module.exports: $Exports<'glamor/lib/inline'>;
}
declare module 'glamor/lib/jsxstyle.js' {
  declare module.exports: $Exports<'glamor/lib/jsxstyle'>;
}
declare module 'glamor/lib/ous.js' {
  declare module.exports: $Exports<'glamor/lib/ous'>;
}
declare module 'glamor/lib/plugins.js' {
  declare module.exports: $Exports<'glamor/lib/plugins'>;
}
declare module 'glamor/lib/prefixer.js' {
  declare module.exports: $Exports<'glamor/lib/prefixer'>;
}
declare module 'glamor/lib/react.js' {
  declare module.exports: $Exports<'glamor/lib/react'>;
}
declare module 'glamor/lib/reset.js' {
  declare module.exports: $Exports<'glamor/lib/reset'>;
}
declare module 'glamor/lib/server.js' {
  declare module.exports: $Exports<'glamor/lib/server'>;
}
declare module 'glamor/lib/sheet.js' {
  declare module.exports: $Exports<'glamor/lib/sheet'>;
}
declare module 'glamor/lib/styled/index.js' {
  declare module.exports: $Exports<'glamor/lib/styled/index'>;
}
declare module 'glamor/lib/utils.js' {
  declare module.exports: $Exports<'glamor/lib/utils'>;
}
declare module 'glamor/ous.js' {
  declare module.exports: $Exports<'glamor/ous'>;
}
declare module 'glamor/react.js' {
  declare module.exports: $Exports<'glamor/react'>;
}
declare module 'glamor/reset.js' {
  declare module.exports: $Exports<'glamor/reset'>;
}
declare module 'glamor/server.js' {
  declare module.exports: $Exports<'glamor/server'>;
}
declare module 'glamor/styled.js' {
  declare module.exports: $Exports<'glamor/styled'>;
}
declare module 'glamor/umd/index.js' {
  declare module.exports: $Exports<'glamor/umd/index'>;
}
declare module 'glamor/umd/index.min.js' {
  declare module.exports: $Exports<'glamor/umd/index.min'>;
}
declare module 'glamor/utils.js' {
  declare module.exports: $Exports<'glamor/utils'>;
}
