// flow-typed signature: d9b3606923a14b403e4f046dfc087008
// flow-typed version: <<STUB>>/gsap_v^1.20.3/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gsap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gsap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gsap/AttrPlugin' {
  declare module.exports: any;
}

declare module 'gsap/BezierPlugin' {
  declare module.exports: any;
}

declare module 'gsap/ColorPropsPlugin' {
  declare module.exports: any;
}

declare module 'gsap/CSSPlugin' {
  declare module.exports: any;
}

declare module 'gsap/CSSRulePlugin' {
  declare module.exports: any;
}

declare module 'gsap/DirectionalRotationPlugin' {
  declare module.exports: any;
}

declare module 'gsap/Draggable' {
  declare module.exports: any;
}

declare module 'gsap/EaselPlugin' {
  declare module.exports: any;
}

declare module 'gsap/EasePack' {
  declare module.exports: any;
}

declare module 'gsap/EndArrayPlugin' {
  declare module.exports: any;
}

declare module 'gsap/jquery.gsap' {
  declare module.exports: any;
}

declare module 'gsap/ModifiersPlugin' {
  declare module.exports: any;
}

declare module 'gsap/PixiPlugin' {
  declare module.exports: any;
}

declare module 'gsap/RaphaelPlugin' {
  declare module.exports: any;
}

declare module 'gsap/RoundPropsPlugin' {
  declare module.exports: any;
}

declare module 'gsap/ScrollToPlugin' {
  declare module.exports: any;
}

declare module 'gsap/src/minified/easing/EasePack.min' {
  declare module.exports: any;
}

declare module 'gsap/src/minified/jquery.gsap.min' {
  declare module.exports: any;
}

declare module 'gsap/src/minified/plugins/AttrPlugin.min' {
  declare module.exports: any;
}

declare module 'gsap/src/minified/plugins/BezierPlugin.min' {
  declare module.exports: any;
}

declare module 'gsap/src/minified/plugins/ColorPropsPlugin.min' {
  declare module.exports: any;
}

declare module 'gsap/src/minified/plugins/CSSPlugin.min' {
  declare module.exports: any;
}

declare module 'gsap/src/minified/plugins/CSSRulePlugin.min' {
  declare module.exports: any;
}

declare module 'gsap/src/minified/plugins/DirectionalRotationPlugin.min' {
  declare module.exports: any;
}

declare module 'gsap/src/minified/plugins/EaselPlugin.min' {
  declare module.exports: any;
}

declare module 'gsap/src/minified/plugins/EndArrayPlugin.min' {
  declare module.exports: any;
}

declare module 'gsap/src/minified/plugins/ModifiersPlugin.min' {
  declare module.exports: any;
}

declare module 'gsap/src/minified/plugins/PixiPlugin.min' {
  declare module.exports: any;
}

declare module 'gsap/src/minified/plugins/RaphaelPlugin.min' {
  declare module.exports: any;
}

declare module 'gsap/src/minified/plugins/RoundPropsPlugin.min' {
  declare module.exports: any;
}

declare module 'gsap/src/minified/plugins/ScrollToPlugin.min' {
  declare module.exports: any;
}

declare module 'gsap/src/minified/plugins/TextPlugin.min' {
  declare module.exports: any;
}

declare module 'gsap/src/minified/TimelineLite.min' {
  declare module.exports: any;
}

declare module 'gsap/src/minified/TimelineMax.min' {
  declare module.exports: any;
}

declare module 'gsap/src/minified/TweenLite.min' {
  declare module.exports: any;
}

declare module 'gsap/src/minified/TweenMax.min' {
  declare module.exports: any;
}

declare module 'gsap/src/minified/utils/Draggable.min' {
  declare module.exports: any;
}

declare module 'gsap/src/uncompressed/easing/EasePack' {
  declare module.exports: any;
}

declare module 'gsap/src/uncompressed/jquery.gsap' {
  declare module.exports: any;
}

declare module 'gsap/src/uncompressed/plugins/AttrPlugin' {
  declare module.exports: any;
}

declare module 'gsap/src/uncompressed/plugins/BezierPlugin' {
  declare module.exports: any;
}

declare module 'gsap/src/uncompressed/plugins/ColorPropsPlugin' {
  declare module.exports: any;
}

declare module 'gsap/src/uncompressed/plugins/CSSPlugin' {
  declare module.exports: any;
}

declare module 'gsap/src/uncompressed/plugins/CSSRulePlugin' {
  declare module.exports: any;
}

declare module 'gsap/src/uncompressed/plugins/DirectionalRotationPlugin' {
  declare module.exports: any;
}

declare module 'gsap/src/uncompressed/plugins/EaselPlugin' {
  declare module.exports: any;
}

declare module 'gsap/src/uncompressed/plugins/EndArrayPlugin' {
  declare module.exports: any;
}

declare module 'gsap/src/uncompressed/plugins/ModifiersPlugin' {
  declare module.exports: any;
}

declare module 'gsap/src/uncompressed/plugins/PixiPlugin' {
  declare module.exports: any;
}

declare module 'gsap/src/uncompressed/plugins/RaphaelPlugin' {
  declare module.exports: any;
}

declare module 'gsap/src/uncompressed/plugins/RoundPropsPlugin' {
  declare module.exports: any;
}

declare module 'gsap/src/uncompressed/plugins/ScrollToPlugin' {
  declare module.exports: any;
}

declare module 'gsap/src/uncompressed/plugins/TEMPLATE_Plugin' {
  declare module.exports: any;
}

declare module 'gsap/src/uncompressed/plugins/TextPlugin' {
  declare module.exports: any;
}

declare module 'gsap/src/uncompressed/TimelineLite' {
  declare module.exports: any;
}

declare module 'gsap/src/uncompressed/TimelineMax' {
  declare module.exports: any;
}

declare module 'gsap/src/uncompressed/TweenLite' {
  declare module.exports: any;
}

declare module 'gsap/src/uncompressed/TweenMax' {
  declare module.exports: any;
}

declare module 'gsap/src/uncompressed/utils/Draggable' {
  declare module.exports: any;
}

declare module 'gsap/TEMPLATE_Plugin' {
  declare module.exports: any;
}

declare module 'gsap/TextPlugin' {
  declare module.exports: any;
}

declare module 'gsap/TimelineLite' {
  declare module.exports: any;
}

declare module 'gsap/TimelineMax' {
  declare module.exports: any;
}

declare module 'gsap/TweenLite' {
  declare module.exports: any;
}

declare module 'gsap/TweenMax' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gsap/AttrPlugin.js' {
  declare module.exports: $Exports<'gsap/AttrPlugin'>;
}
declare module 'gsap/BezierPlugin.js' {
  declare module.exports: $Exports<'gsap/BezierPlugin'>;
}
declare module 'gsap/ColorPropsPlugin.js' {
  declare module.exports: $Exports<'gsap/ColorPropsPlugin'>;
}
declare module 'gsap/CSSPlugin.js' {
  declare module.exports: $Exports<'gsap/CSSPlugin'>;
}
declare module 'gsap/CSSRulePlugin.js' {
  declare module.exports: $Exports<'gsap/CSSRulePlugin'>;
}
declare module 'gsap/DirectionalRotationPlugin.js' {
  declare module.exports: $Exports<'gsap/DirectionalRotationPlugin'>;
}
declare module 'gsap/Draggable.js' {
  declare module.exports: $Exports<'gsap/Draggable'>;
}
declare module 'gsap/EaselPlugin.js' {
  declare module.exports: $Exports<'gsap/EaselPlugin'>;
}
declare module 'gsap/EasePack.js' {
  declare module.exports: $Exports<'gsap/EasePack'>;
}
declare module 'gsap/EndArrayPlugin.js' {
  declare module.exports: $Exports<'gsap/EndArrayPlugin'>;
}
declare module 'gsap/jquery.gsap.js' {
  declare module.exports: $Exports<'gsap/jquery.gsap'>;
}
declare module 'gsap/ModifiersPlugin.js' {
  declare module.exports: $Exports<'gsap/ModifiersPlugin'>;
}
declare module 'gsap/PixiPlugin.js' {
  declare module.exports: $Exports<'gsap/PixiPlugin'>;
}
declare module 'gsap/RaphaelPlugin.js' {
  declare module.exports: $Exports<'gsap/RaphaelPlugin'>;
}
declare module 'gsap/RoundPropsPlugin.js' {
  declare module.exports: $Exports<'gsap/RoundPropsPlugin'>;
}
declare module 'gsap/ScrollToPlugin.js' {
  declare module.exports: $Exports<'gsap/ScrollToPlugin'>;
}
declare module 'gsap/src/minified/easing/EasePack.min.js' {
  declare module.exports: $Exports<'gsap/src/minified/easing/EasePack.min'>;
}
declare module 'gsap/src/minified/jquery.gsap.min.js' {
  declare module.exports: $Exports<'gsap/src/minified/jquery.gsap.min'>;
}
declare module 'gsap/src/minified/plugins/AttrPlugin.min.js' {
  declare module.exports: $Exports<'gsap/src/minified/plugins/AttrPlugin.min'>;
}
declare module 'gsap/src/minified/plugins/BezierPlugin.min.js' {
  declare module.exports: $Exports<
    'gsap/src/minified/plugins/BezierPlugin.min'
  >;
}
declare module 'gsap/src/minified/plugins/ColorPropsPlugin.min.js' {
  declare module.exports: $Exports<
    'gsap/src/minified/plugins/ColorPropsPlugin.min'
  >;
}
declare module 'gsap/src/minified/plugins/CSSPlugin.min.js' {
  declare module.exports: $Exports<'gsap/src/minified/plugins/CSSPlugin.min'>;
}
declare module 'gsap/src/minified/plugins/CSSRulePlugin.min.js' {
  declare module.exports: $Exports<
    'gsap/src/minified/plugins/CSSRulePlugin.min'
  >;
}
declare module 'gsap/src/minified/plugins/DirectionalRotationPlugin.min.js' {
  declare module.exports: $Exports<
    'gsap/src/minified/plugins/DirectionalRotationPlugin.min'
  >;
}
declare module 'gsap/src/minified/plugins/EaselPlugin.min.js' {
  declare module.exports: $Exports<'gsap/src/minified/plugins/EaselPlugin.min'>;
}
declare module 'gsap/src/minified/plugins/EndArrayPlugin.min.js' {
  declare module.exports: $Exports<
    'gsap/src/minified/plugins/EndArrayPlugin.min'
  >;
}
declare module 'gsap/src/minified/plugins/ModifiersPlugin.min.js' {
  declare module.exports: $Exports<
    'gsap/src/minified/plugins/ModifiersPlugin.min'
  >;
}
declare module 'gsap/src/minified/plugins/PixiPlugin.min.js' {
  declare module.exports: $Exports<'gsap/src/minified/plugins/PixiPlugin.min'>;
}
declare module 'gsap/src/minified/plugins/RaphaelPlugin.min.js' {
  declare module.exports: $Exports<
    'gsap/src/minified/plugins/RaphaelPlugin.min'
  >;
}
declare module 'gsap/src/minified/plugins/RoundPropsPlugin.min.js' {
  declare module.exports: $Exports<
    'gsap/src/minified/plugins/RoundPropsPlugin.min'
  >;
}
declare module 'gsap/src/minified/plugins/ScrollToPlugin.min.js' {
  declare module.exports: $Exports<
    'gsap/src/minified/plugins/ScrollToPlugin.min'
  >;
}
declare module 'gsap/src/minified/plugins/TextPlugin.min.js' {
  declare module.exports: $Exports<'gsap/src/minified/plugins/TextPlugin.min'>;
}
declare module 'gsap/src/minified/TimelineLite.min.js' {
  declare module.exports: $Exports<'gsap/src/minified/TimelineLite.min'>;
}
declare module 'gsap/src/minified/TimelineMax.min.js' {
  declare module.exports: $Exports<'gsap/src/minified/TimelineMax.min'>;
}
declare module 'gsap/src/minified/TweenLite.min.js' {
  declare module.exports: $Exports<'gsap/src/minified/TweenLite.min'>;
}
declare module 'gsap/src/minified/TweenMax.min.js' {
  declare module.exports: $Exports<'gsap/src/minified/TweenMax.min'>;
}
declare module 'gsap/src/minified/utils/Draggable.min.js' {
  declare module.exports: $Exports<'gsap/src/minified/utils/Draggable.min'>;
}
declare module 'gsap/src/uncompressed/easing/EasePack.js' {
  declare module.exports: $Exports<'gsap/src/uncompressed/easing/EasePack'>;
}
declare module 'gsap/src/uncompressed/jquery.gsap.js' {
  declare module.exports: $Exports<'gsap/src/uncompressed/jquery.gsap'>;
}
declare module 'gsap/src/uncompressed/plugins/AttrPlugin.js' {
  declare module.exports: $Exports<'gsap/src/uncompressed/plugins/AttrPlugin'>;
}
declare module 'gsap/src/uncompressed/plugins/BezierPlugin.js' {
  declare module.exports: $Exports<
    'gsap/src/uncompressed/plugins/BezierPlugin'
  >;
}
declare module 'gsap/src/uncompressed/plugins/ColorPropsPlugin.js' {
  declare module.exports: $Exports<
    'gsap/src/uncompressed/plugins/ColorPropsPlugin'
  >;
}
declare module 'gsap/src/uncompressed/plugins/CSSPlugin.js' {
  declare module.exports: $Exports<'gsap/src/uncompressed/plugins/CSSPlugin'>;
}
declare module 'gsap/src/uncompressed/plugins/CSSRulePlugin.js' {
  declare module.exports: $Exports<
    'gsap/src/uncompressed/plugins/CSSRulePlugin'
  >;
}
declare module 'gsap/src/uncompressed/plugins/DirectionalRotationPlugin.js' {
  declare module.exports: $Exports<
    'gsap/src/uncompressed/plugins/DirectionalRotationPlugin'
  >;
}
declare module 'gsap/src/uncompressed/plugins/EaselPlugin.js' {
  declare module.exports: $Exports<'gsap/src/uncompressed/plugins/EaselPlugin'>;
}
declare module 'gsap/src/uncompressed/plugins/EndArrayPlugin.js' {
  declare module.exports: $Exports<
    'gsap/src/uncompressed/plugins/EndArrayPlugin'
  >;
}
declare module 'gsap/src/uncompressed/plugins/ModifiersPlugin.js' {
  declare module.exports: $Exports<
    'gsap/src/uncompressed/plugins/ModifiersPlugin'
  >;
}
declare module 'gsap/src/uncompressed/plugins/PixiPlugin.js' {
  declare module.exports: $Exports<'gsap/src/uncompressed/plugins/PixiPlugin'>;
}
declare module 'gsap/src/uncompressed/plugins/RaphaelPlugin.js' {
  declare module.exports: $Exports<
    'gsap/src/uncompressed/plugins/RaphaelPlugin'
  >;
}
declare module 'gsap/src/uncompressed/plugins/RoundPropsPlugin.js' {
  declare module.exports: $Exports<
    'gsap/src/uncompressed/plugins/RoundPropsPlugin'
  >;
}
declare module 'gsap/src/uncompressed/plugins/ScrollToPlugin.js' {
  declare module.exports: $Exports<
    'gsap/src/uncompressed/plugins/ScrollToPlugin'
  >;
}
declare module 'gsap/src/uncompressed/plugins/TEMPLATE_Plugin.js' {
  declare module.exports: $Exports<
    'gsap/src/uncompressed/plugins/TEMPLATE_Plugin'
  >;
}
declare module 'gsap/src/uncompressed/plugins/TextPlugin.js' {
  declare module.exports: $Exports<'gsap/src/uncompressed/plugins/TextPlugin'>;
}
declare module 'gsap/src/uncompressed/TimelineLite.js' {
  declare module.exports: $Exports<'gsap/src/uncompressed/TimelineLite'>;
}
declare module 'gsap/src/uncompressed/TimelineMax.js' {
  declare module.exports: $Exports<'gsap/src/uncompressed/TimelineMax'>;
}
declare module 'gsap/src/uncompressed/TweenLite.js' {
  declare module.exports: $Exports<'gsap/src/uncompressed/TweenLite'>;
}
declare module 'gsap/src/uncompressed/TweenMax.js' {
  declare module.exports: $Exports<'gsap/src/uncompressed/TweenMax'>;
}
declare module 'gsap/src/uncompressed/utils/Draggable.js' {
  declare module.exports: $Exports<'gsap/src/uncompressed/utils/Draggable'>;
}
declare module 'gsap/TEMPLATE_Plugin.js' {
  declare module.exports: $Exports<'gsap/TEMPLATE_Plugin'>;
}
declare module 'gsap/TextPlugin.js' {
  declare module.exports: $Exports<'gsap/TextPlugin'>;
}
declare module 'gsap/TimelineLite.js' {
  declare module.exports: $Exports<'gsap/TimelineLite'>;
}
declare module 'gsap/TimelineMax.js' {
  declare module.exports: $Exports<'gsap/TimelineMax'>;
}
declare module 'gsap/TweenLite.js' {
  declare module.exports: $Exports<'gsap/TweenLite'>;
}
declare module 'gsap/TweenMax.js' {
  declare module.exports: $Exports<'gsap/TweenMax'>;
}
