// flow-typed signature: 75a33f081c519e8a38f9407ac42bb75a
// flow-typed version: <<STUB>>/gulp-replace_v^0.5.4/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-replace'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-replace' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'gulp-replace/index' {
  declare module.exports: $Exports<'gulp-replace'>;
}
declare module 'gulp-replace/index.js' {
  declare module.exports: $Exports<'gulp-replace'>;
}
