// flow-typed signature: 1ee869a6593e9e90e3d1e0b31419eb0f
// flow-typed version: <<STUB>>/gulp-rev_v^7.1.2/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-rev'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-rev' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-rev/index' {
  declare module.exports: $Exports<'gulp-rev'>;
}
declare module 'gulp-rev/index.js' {
  declare module.exports: $Exports<'gulp-rev'>;
}
