// flow-typed signature: 8800ba7ad0cc3698bffc3940312308b5
// flow-typed version: <<STUB>>/gulp-filter_v^5.0.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-filter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-filter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-filter/index' {
  declare module.exports: $Exports<'gulp-filter'>;
}
declare module 'gulp-filter/index.js' {
  declare module.exports: $Exports<'gulp-filter'>;
}
