// flow-typed signature: 0be04545e50e6a7ed810aacbbe0572c5
// flow-typed version: <<STUB>>/gulp_v^3.9.1/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp/bin/gulp' {
  declare module.exports: any;
}

declare module 'gulp/lib/completion' {
  declare module.exports: any;
}

declare module 'gulp/lib/taskTree' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp/bin/gulp.js' {
  declare module.exports: $Exports<'gulp/bin/gulp'>;
}
declare module 'gulp/index' {
  declare module.exports: $Exports<'gulp'>;
}
declare module 'gulp/index.js' {
  declare module.exports: $Exports<'gulp'>;
}
declare module 'gulp/lib/completion.js' {
  declare module.exports: $Exports<'gulp/lib/completion'>;
}
declare module 'gulp/lib/taskTree.js' {
  declare module.exports: $Exports<'gulp/lib/taskTree'>;
}
