// flow-typed signature: 910e16572fccf6c670b2ddaca6c1dac1
// flow-typed version: <<STUB>>/happypack_v^4.0.0-beta.2/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'happypack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'happypack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'happypack/lib/applyLoaders' {
  declare module.exports: any;
}

declare module 'happypack/lib/BufferedFd' {
  declare module.exports: any;
}

declare module 'happypack/lib/constants' {
  declare module.exports: any;
}

declare module 'happypack/lib/ErrorSerializer' {
  declare module.exports: any;
}

declare module 'happypack/lib/fnOnce' {
  declare module.exports: any;
}

declare module 'happypack/lib/fnOncePedantic' {
  declare module.exports: any;
}

declare module 'happypack/lib/HappyFakeCompiler' {
  declare module.exports: any;
}

declare module 'happypack/lib/HappyFakeLoaderContext' {
  declare module.exports: any;
}

declare module 'happypack/lib/HappyForegroundThreadPool' {
  declare module.exports: any;
}

declare module 'happypack/lib/HappyLoader' {
  declare module.exports: any;
}

declare module 'happypack/lib/HappyMessage' {
  declare module.exports: any;
}

declare module 'happypack/lib/HappyPlugin' {
  declare module.exports: any;
}

declare module 'happypack/lib/HappyRPCHandler' {
  declare module.exports: any;
}

declare module 'happypack/lib/HappyThread' {
  declare module.exports: any;
}

declare module 'happypack/lib/HappyThreadPool' {
  declare module.exports: any;
}

declare module 'happypack/lib/HappyWorker' {
  declare module.exports: any;
}

declare module 'happypack/lib/HappyWorkerChannel' {
  declare module.exports: any;
}

declare module 'happypack/lib/JSONSerializer' {
  declare module.exports: any;
}

declare module 'happypack/lib/OptionParser' {
  declare module.exports: any;
}

declare module 'happypack/lib/pick' {
  declare module.exports: any;
}

declare module 'happypack/lib/processSend' {
  declare module.exports: any;
}

declare module 'happypack/lib/SharedPtr' {
  declare module.exports: any;
}

declare module 'happypack/lib/SharedPtrMap' {
  declare module.exports: any;
}

declare module 'happypack/lib/SourceMapSerializer' {
  declare module.exports: any;
}

declare module 'happypack/lib/UnbufferedFd' {
  declare module.exports: any;
}

declare module 'happypack/lib/WebpackUtils' {
  declare module.exports: any;
}

declare module 'happypack/loader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'happypack/lib/applyLoaders.js' {
  declare module.exports: $Exports<'happypack/lib/applyLoaders'>;
}
declare module 'happypack/lib/BufferedFd.js' {
  declare module.exports: $Exports<'happypack/lib/BufferedFd'>;
}
declare module 'happypack/lib/constants.js' {
  declare module.exports: $Exports<'happypack/lib/constants'>;
}
declare module 'happypack/lib/ErrorSerializer.js' {
  declare module.exports: $Exports<'happypack/lib/ErrorSerializer'>;
}
declare module 'happypack/lib/fnOnce.js' {
  declare module.exports: $Exports<'happypack/lib/fnOnce'>;
}
declare module 'happypack/lib/fnOncePedantic.js' {
  declare module.exports: $Exports<'happypack/lib/fnOncePedantic'>;
}
declare module 'happypack/lib/HappyFakeCompiler.js' {
  declare module.exports: $Exports<'happypack/lib/HappyFakeCompiler'>;
}
declare module 'happypack/lib/HappyFakeLoaderContext.js' {
  declare module.exports: $Exports<'happypack/lib/HappyFakeLoaderContext'>;
}
declare module 'happypack/lib/HappyForegroundThreadPool.js' {
  declare module.exports: $Exports<'happypack/lib/HappyForegroundThreadPool'>;
}
declare module 'happypack/lib/HappyLoader.js' {
  declare module.exports: $Exports<'happypack/lib/HappyLoader'>;
}
declare module 'happypack/lib/HappyMessage.js' {
  declare module.exports: $Exports<'happypack/lib/HappyMessage'>;
}
declare module 'happypack/lib/HappyPlugin.js' {
  declare module.exports: $Exports<'happypack/lib/HappyPlugin'>;
}
declare module 'happypack/lib/HappyRPCHandler.js' {
  declare module.exports: $Exports<'happypack/lib/HappyRPCHandler'>;
}
declare module 'happypack/lib/HappyThread.js' {
  declare module.exports: $Exports<'happypack/lib/HappyThread'>;
}
declare module 'happypack/lib/HappyThreadPool.js' {
  declare module.exports: $Exports<'happypack/lib/HappyThreadPool'>;
}
declare module 'happypack/lib/HappyWorker.js' {
  declare module.exports: $Exports<'happypack/lib/HappyWorker'>;
}
declare module 'happypack/lib/HappyWorkerChannel.js' {
  declare module.exports: $Exports<'happypack/lib/HappyWorkerChannel'>;
}
declare module 'happypack/lib/JSONSerializer.js' {
  declare module.exports: $Exports<'happypack/lib/JSONSerializer'>;
}
declare module 'happypack/lib/OptionParser.js' {
  declare module.exports: $Exports<'happypack/lib/OptionParser'>;
}
declare module 'happypack/lib/pick.js' {
  declare module.exports: $Exports<'happypack/lib/pick'>;
}
declare module 'happypack/lib/processSend.js' {
  declare module.exports: $Exports<'happypack/lib/processSend'>;
}
declare module 'happypack/lib/SharedPtr.js' {
  declare module.exports: $Exports<'happypack/lib/SharedPtr'>;
}
declare module 'happypack/lib/SharedPtrMap.js' {
  declare module.exports: $Exports<'happypack/lib/SharedPtrMap'>;
}
declare module 'happypack/lib/SourceMapSerializer.js' {
  declare module.exports: $Exports<'happypack/lib/SourceMapSerializer'>;
}
declare module 'happypack/lib/UnbufferedFd.js' {
  declare module.exports: $Exports<'happypack/lib/UnbufferedFd'>;
}
declare module 'happypack/lib/WebpackUtils.js' {
  declare module.exports: $Exports<'happypack/lib/WebpackUtils'>;
}
declare module 'happypack/loader.js' {
  declare module.exports: $Exports<'happypack/loader'>;
}
