// flow-typed signature: bf068c88a2861419d0579169cbae47eb
// flow-typed version: <<STUB>>/hash-sum_v^1.0.2/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hash-sum'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hash-sum' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hash-sum/hash-sum' {
  declare module.exports: any;
}

declare module 'hash-sum/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hash-sum/hash-sum.js' {
  declare module.exports: $Exports<'hash-sum/hash-sum'>;
}
declare module 'hash-sum/test.js' {
  declare module.exports: $Exports<'hash-sum/test'>;
}
