// flow-typed signature: f881df438a631c87407d16ae52dc4a2b
// flow-typed version: <<STUB>>/http-proxy-middleware_v^0.17.2/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'http-proxy-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'http-proxy-middleware' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'http-proxy-middleware/lib/config-factory' {
  declare module.exports: any;
}

declare module 'http-proxy-middleware/lib/context-matcher' {
  declare module.exports: any;
}

declare module 'http-proxy-middleware/lib/handlers' {
  declare module.exports: any;
}

declare module 'http-proxy-middleware/lib/index' {
  declare module.exports: any;
}

declare module 'http-proxy-middleware/lib/logger' {
  declare module.exports: any;
}

declare module 'http-proxy-middleware/lib/path-rewriter' {
  declare module.exports: any;
}

declare module 'http-proxy-middleware/lib/router' {
  declare module.exports: any;
}

// Filename aliases
declare module 'http-proxy-middleware/index' {
  declare module.exports: $Exports<'http-proxy-middleware'>;
}
declare module 'http-proxy-middleware/index.js' {
  declare module.exports: $Exports<'http-proxy-middleware'>;
}
declare module 'http-proxy-middleware/lib/config-factory.js' {
  declare module.exports: $Exports<'http-proxy-middleware/lib/config-factory'>;
}
declare module 'http-proxy-middleware/lib/context-matcher.js' {
  declare module.exports: $Exports<'http-proxy-middleware/lib/context-matcher'>;
}
declare module 'http-proxy-middleware/lib/handlers.js' {
  declare module.exports: $Exports<'http-proxy-middleware/lib/handlers'>;
}
declare module 'http-proxy-middleware/lib/index.js' {
  declare module.exports: $Exports<'http-proxy-middleware/lib/index'>;
}
declare module 'http-proxy-middleware/lib/logger.js' {
  declare module.exports: $Exports<'http-proxy-middleware/lib/logger'>;
}
declare module 'http-proxy-middleware/lib/path-rewriter.js' {
  declare module.exports: $Exports<'http-proxy-middleware/lib/path-rewriter'>;
}
declare module 'http-proxy-middleware/lib/router.js' {
  declare module.exports: $Exports<'http-proxy-middleware/lib/router'>;
}
