// flow-typed signature: 3189a82d58c8f43a170b6194d7b015fe
// flow-typed version: <<STUB>>/humps_vCompuIves/humps/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'humps'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'humps' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'humps/humps' {
  declare module.exports: any;
}

declare module 'humps/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'humps/humps.js' {
  declare module.exports: $Exports<'humps/humps'>;
}
declare module 'humps/test/test.js' {
  declare module.exports: $Exports<'humps/test/test'>;
}
