// flow-typed signature: baef9cdf87dc6ef906ec99cb984ce62e
// flow-typed version: <<STUB>>/i18next_v8.x.x/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'i18next'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'i18next' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'i18next/dist/commonjs/BackendConnector' {
  declare module.exports: any;
}

declare module 'i18next/dist/commonjs/CacheConnector' {
  declare module.exports: any;
}

declare module 'i18next/dist/commonjs/compatibility/v1' {
  declare module.exports: any;
}

declare module 'i18next/dist/commonjs/defaults' {
  declare module.exports: any;
}

declare module 'i18next/dist/commonjs/EventEmitter' {
  declare module.exports: any;
}

declare module 'i18next/dist/commonjs/i18next' {
  declare module.exports: any;
}

declare module 'i18next/dist/commonjs/index' {
  declare module.exports: any;
}

declare module 'i18next/dist/commonjs/Interpolator' {
  declare module.exports: any;
}

declare module 'i18next/dist/commonjs/LanguageUtils' {
  declare module.exports: any;
}

declare module 'i18next/dist/commonjs/logger' {
  declare module.exports: any;
}

declare module 'i18next/dist/commonjs/PluralResolver' {
  declare module.exports: any;
}

declare module 'i18next/dist/commonjs/postProcessor' {
  declare module.exports: any;
}

declare module 'i18next/dist/commonjs/ResourceStore' {
  declare module.exports: any;
}

declare module 'i18next/dist/commonjs/Translator' {
  declare module.exports: any;
}

declare module 'i18next/dist/commonjs/utils' {
  declare module.exports: any;
}

declare module 'i18next/dist/es/BackendConnector' {
  declare module.exports: any;
}

declare module 'i18next/dist/es/CacheConnector' {
  declare module.exports: any;
}

declare module 'i18next/dist/es/compatibility/v1' {
  declare module.exports: any;
}

declare module 'i18next/dist/es/defaults' {
  declare module.exports: any;
}

declare module 'i18next/dist/es/EventEmitter' {
  declare module.exports: any;
}

declare module 'i18next/dist/es/i18next' {
  declare module.exports: any;
}

declare module 'i18next/dist/es/index' {
  declare module.exports: any;
}

declare module 'i18next/dist/es/Interpolator' {
  declare module.exports: any;
}

declare module 'i18next/dist/es/LanguageUtils' {
  declare module.exports: any;
}

declare module 'i18next/dist/es/logger' {
  declare module.exports: any;
}

declare module 'i18next/dist/es/PluralResolver' {
  declare module.exports: any;
}

declare module 'i18next/dist/es/postProcessor' {
  declare module.exports: any;
}

declare module 'i18next/dist/es/ResourceStore' {
  declare module.exports: any;
}

declare module 'i18next/dist/es/Translator' {
  declare module.exports: any;
}

declare module 'i18next/dist/es/utils' {
  declare module.exports: any;
}

declare module 'i18next/dist/umd/i18next' {
  declare module.exports: any;
}

declare module 'i18next/dist/umd/i18next.min' {
  declare module.exports: any;
}

declare module 'i18next/i18next' {
  declare module.exports: any;
}

declare module 'i18next/i18next.min' {
  declare module.exports: any;
}

declare module 'i18next/karma.backward.conf' {
  declare module.exports: any;
}

declare module 'i18next/rollup.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'i18next/dist/commonjs/BackendConnector.js' {
  declare module.exports: $Exports<'i18next/dist/commonjs/BackendConnector'>;
}
declare module 'i18next/dist/commonjs/CacheConnector.js' {
  declare module.exports: $Exports<'i18next/dist/commonjs/CacheConnector'>;
}
declare module 'i18next/dist/commonjs/compatibility/v1.js' {
  declare module.exports: $Exports<'i18next/dist/commonjs/compatibility/v1'>;
}
declare module 'i18next/dist/commonjs/defaults.js' {
  declare module.exports: $Exports<'i18next/dist/commonjs/defaults'>;
}
declare module 'i18next/dist/commonjs/EventEmitter.js' {
  declare module.exports: $Exports<'i18next/dist/commonjs/EventEmitter'>;
}
declare module 'i18next/dist/commonjs/i18next.js' {
  declare module.exports: $Exports<'i18next/dist/commonjs/i18next'>;
}
declare module 'i18next/dist/commonjs/index.js' {
  declare module.exports: $Exports<'i18next/dist/commonjs/index'>;
}
declare module 'i18next/dist/commonjs/Interpolator.js' {
  declare module.exports: $Exports<'i18next/dist/commonjs/Interpolator'>;
}
declare module 'i18next/dist/commonjs/LanguageUtils.js' {
  declare module.exports: $Exports<'i18next/dist/commonjs/LanguageUtils'>;
}
declare module 'i18next/dist/commonjs/logger.js' {
  declare module.exports: $Exports<'i18next/dist/commonjs/logger'>;
}
declare module 'i18next/dist/commonjs/PluralResolver.js' {
  declare module.exports: $Exports<'i18next/dist/commonjs/PluralResolver'>;
}
declare module 'i18next/dist/commonjs/postProcessor.js' {
  declare module.exports: $Exports<'i18next/dist/commonjs/postProcessor'>;
}
declare module 'i18next/dist/commonjs/ResourceStore.js' {
  declare module.exports: $Exports<'i18next/dist/commonjs/ResourceStore'>;
}
declare module 'i18next/dist/commonjs/Translator.js' {
  declare module.exports: $Exports<'i18next/dist/commonjs/Translator'>;
}
declare module 'i18next/dist/commonjs/utils.js' {
  declare module.exports: $Exports<'i18next/dist/commonjs/utils'>;
}
declare module 'i18next/dist/es/BackendConnector.js' {
  declare module.exports: $Exports<'i18next/dist/es/BackendConnector'>;
}
declare module 'i18next/dist/es/CacheConnector.js' {
  declare module.exports: $Exports<'i18next/dist/es/CacheConnector'>;
}
declare module 'i18next/dist/es/compatibility/v1.js' {
  declare module.exports: $Exports<'i18next/dist/es/compatibility/v1'>;
}
declare module 'i18next/dist/es/defaults.js' {
  declare module.exports: $Exports<'i18next/dist/es/defaults'>;
}
declare module 'i18next/dist/es/EventEmitter.js' {
  declare module.exports: $Exports<'i18next/dist/es/EventEmitter'>;
}
declare module 'i18next/dist/es/i18next.js' {
  declare module.exports: $Exports<'i18next/dist/es/i18next'>;
}
declare module 'i18next/dist/es/index.js' {
  declare module.exports: $Exports<'i18next/dist/es/index'>;
}
declare module 'i18next/dist/es/Interpolator.js' {
  declare module.exports: $Exports<'i18next/dist/es/Interpolator'>;
}
declare module 'i18next/dist/es/LanguageUtils.js' {
  declare module.exports: $Exports<'i18next/dist/es/LanguageUtils'>;
}
declare module 'i18next/dist/es/logger.js' {
  declare module.exports: $Exports<'i18next/dist/es/logger'>;
}
declare module 'i18next/dist/es/PluralResolver.js' {
  declare module.exports: $Exports<'i18next/dist/es/PluralResolver'>;
}
declare module 'i18next/dist/es/postProcessor.js' {
  declare module.exports: $Exports<'i18next/dist/es/postProcessor'>;
}
declare module 'i18next/dist/es/ResourceStore.js' {
  declare module.exports: $Exports<'i18next/dist/es/ResourceStore'>;
}
declare module 'i18next/dist/es/Translator.js' {
  declare module.exports: $Exports<'i18next/dist/es/Translator'>;
}
declare module 'i18next/dist/es/utils.js' {
  declare module.exports: $Exports<'i18next/dist/es/utils'>;
}
declare module 'i18next/dist/umd/i18next.js' {
  declare module.exports: $Exports<'i18next/dist/umd/i18next'>;
}
declare module 'i18next/dist/umd/i18next.min.js' {
  declare module.exports: $Exports<'i18next/dist/umd/i18next.min'>;
}
declare module 'i18next/i18next.js' {
  declare module.exports: $Exports<'i18next/i18next'>;
}
declare module 'i18next/i18next.min.js' {
  declare module.exports: $Exports<'i18next/i18next.min'>;
}
declare module 'i18next/index' {
  declare module.exports: $Exports<'i18next'>;
}
declare module 'i18next/index.js' {
  declare module.exports: $Exports<'i18next'>;
}
declare module 'i18next/karma.backward.conf.js' {
  declare module.exports: $Exports<'i18next/karma.backward.conf'>;
}
declare module 'i18next/rollup.config.js' {
  declare module.exports: $Exports<'i18next/rollup.config'>;
}
