// flow-typed signature: 4b7767255e88a7b301f89d5ff7f409b3
// flow-typed version: <<STUB>>/image-extensions_v^1.1.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'image-extensions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'image-extensions' {
  declare module.exports: any;
}
