// flow-typed signature: d674d8a194751beabf217c4245cc86c3
// flow-typed version: <<STUB>>/jest-image-snapshot_v^1.0.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-image-snapshot'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-image-snapshot' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-image-snapshot/__tests__/src/diff-snapshot.spec' {
  declare module.exports: any;
}

declare module 'jest-image-snapshot/__tests__/src/index.spec' {
  declare module.exports: any;
}

declare module 'jest-image-snapshot/src/diff-snapshot' {
  declare module.exports: any;
}

declare module 'jest-image-snapshot/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-image-snapshot/__tests__/src/diff-snapshot.spec.js' {
  declare module.exports: $Exports<
    'jest-image-snapshot/__tests__/src/diff-snapshot.spec'
  >;
}
declare module 'jest-image-snapshot/__tests__/src/index.spec.js' {
  declare module.exports: $Exports<
    'jest-image-snapshot/__tests__/src/index.spec'
  >;
}
declare module 'jest-image-snapshot/src/diff-snapshot.js' {
  declare module.exports: $Exports<'jest-image-snapshot/src/diff-snapshot'>;
}
declare module 'jest-image-snapshot/src/index.js' {
  declare module.exports: $Exports<'jest-image-snapshot/src/index'>;
}
