// flow-typed signature: 33fffebea7ffb75cca7167ff7c214169
// flow-typed version: <<STUB>>/jest-matchers_v20.x.x/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-matchers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-matchers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-matchers/build-es5/asymmetric-matchers' {
  declare module.exports: any;
}

declare module 'jest-matchers/build-es5/index' {
  declare module.exports: any;
}

declare module 'jest-matchers/build-es5/jasmine-utils' {
  declare module.exports: any;
}

declare module 'jest-matchers/build-es5/matchers' {
  declare module.exports: any;
}

declare module 'jest-matchers/build-es5/spyMatchers' {
  declare module.exports: any;
}

declare module 'jest-matchers/build-es5/toThrowMatchers' {
  declare module.exports: any;
}

declare module 'jest-matchers/build-es5/utils' {
  declare module.exports: any;
}

declare module 'jest-matchers/build/asymmetric-matchers' {
  declare module.exports: any;
}

declare module 'jest-matchers/build/index' {
  declare module.exports: any;
}

declare module 'jest-matchers/build/jasmine-utils' {
  declare module.exports: any;
}

declare module 'jest-matchers/build/matchers' {
  declare module.exports: any;
}

declare module 'jest-matchers/build/spyMatchers' {
  declare module.exports: any;
}

declare module 'jest-matchers/build/toThrowMatchers' {
  declare module.exports: any;
}

declare module 'jest-matchers/build/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-matchers/build-es5/asymmetric-matchers.js' {
  declare module.exports: $Exports<
    'jest-matchers/build-es5/asymmetric-matchers'
  >;
}
declare module 'jest-matchers/build-es5/index.js' {
  declare module.exports: $Exports<'jest-matchers/build-es5/index'>;
}
declare module 'jest-matchers/build-es5/jasmine-utils.js' {
  declare module.exports: $Exports<'jest-matchers/build-es5/jasmine-utils'>;
}
declare module 'jest-matchers/build-es5/matchers.js' {
  declare module.exports: $Exports<'jest-matchers/build-es5/matchers'>;
}
declare module 'jest-matchers/build-es5/spyMatchers.js' {
  declare module.exports: $Exports<'jest-matchers/build-es5/spyMatchers'>;
}
declare module 'jest-matchers/build-es5/toThrowMatchers.js' {
  declare module.exports: $Exports<'jest-matchers/build-es5/toThrowMatchers'>;
}
declare module 'jest-matchers/build-es5/utils.js' {
  declare module.exports: $Exports<'jest-matchers/build-es5/utils'>;
}
declare module 'jest-matchers/build/asymmetric-matchers.js' {
  declare module.exports: $Exports<'jest-matchers/build/asymmetric-matchers'>;
}
declare module 'jest-matchers/build/index.js' {
  declare module.exports: $Exports<'jest-matchers/build/index'>;
}
declare module 'jest-matchers/build/jasmine-utils.js' {
  declare module.exports: $Exports<'jest-matchers/build/jasmine-utils'>;
}
declare module 'jest-matchers/build/matchers.js' {
  declare module.exports: $Exports<'jest-matchers/build/matchers'>;
}
declare module 'jest-matchers/build/spyMatchers.js' {
  declare module.exports: $Exports<'jest-matchers/build/spyMatchers'>;
}
declare module 'jest-matchers/build/toThrowMatchers.js' {
  declare module.exports: $Exports<'jest-matchers/build/toThrowMatchers'>;
}
declare module 'jest-matchers/build/utils.js' {
  declare module.exports: $Exports<'jest-matchers/build/utils'>;
}
