// flow-typed signature: 53cc637df532e2d6b36c13a35e2a0c0a
// flow-typed version: <<STUB>>/jest-circus_v^22.1.4/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-circus'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-circus' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-circus/build/event_handler' {
  declare module.exports: any;
}

declare module 'jest-circus/build/format_node_assert_errors' {
  declare module.exports: any;
}

declare module 'jest-circus/build/index' {
  declare module.exports: any;
}

declare module 'jest-circus/build/legacy_code_todo_rewrite/jest_adapter_init' {
  declare module.exports: any;
}

declare module 'jest-circus/build/legacy_code_todo_rewrite/jest_adapter' {
  declare module.exports: any;
}

declare module 'jest-circus/build/legacy_code_todo_rewrite/jest_expect' {
  declare module.exports: any;
}

declare module 'jest-circus/build/run' {
  declare module.exports: any;
}

declare module 'jest-circus/build/state' {
  declare module.exports: any;
}

declare module 'jest-circus/build/utils' {
  declare module.exports: any;
}

declare module 'jest-circus/src/event_handler' {
  declare module.exports: any;
}

declare module 'jest-circus/src/format_node_assert_errors' {
  declare module.exports: any;
}

declare module 'jest-circus/src/index' {
  declare module.exports: any;
}

declare module 'jest-circus/src/legacy_code_todo_rewrite/jest_adapter_init' {
  declare module.exports: any;
}

declare module 'jest-circus/src/legacy_code_todo_rewrite/jest_adapter' {
  declare module.exports: any;
}

declare module 'jest-circus/src/legacy_code_todo_rewrite/jest_expect' {
  declare module.exports: any;
}

declare module 'jest-circus/src/run' {
  declare module.exports: any;
}

declare module 'jest-circus/src/state' {
  declare module.exports: any;
}

declare module 'jest-circus/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-circus/build/event_handler.js' {
  declare module.exports: $Exports<'jest-circus/build/event_handler'>;
}
declare module 'jest-circus/build/format_node_assert_errors.js' {
  declare module.exports: $Exports<
    'jest-circus/build/format_node_assert_errors'
  >;
}
declare module 'jest-circus/build/index.js' {
  declare module.exports: $Exports<'jest-circus/build/index'>;
}
declare module 'jest-circus/build/legacy_code_todo_rewrite/jest_adapter_init.js' {
  declare module.exports: $Exports<
    'jest-circus/build/legacy_code_todo_rewrite/jest_adapter_init'
  >;
}
declare module 'jest-circus/build/legacy_code_todo_rewrite/jest_adapter.js' {
  declare module.exports: $Exports<
    'jest-circus/build/legacy_code_todo_rewrite/jest_adapter'
  >;
}
declare module 'jest-circus/build/legacy_code_todo_rewrite/jest_expect.js' {
  declare module.exports: $Exports<
    'jest-circus/build/legacy_code_todo_rewrite/jest_expect'
  >;
}
declare module 'jest-circus/build/run.js' {
  declare module.exports: $Exports<'jest-circus/build/run'>;
}
declare module 'jest-circus/build/state.js' {
  declare module.exports: $Exports<'jest-circus/build/state'>;
}
declare module 'jest-circus/build/utils.js' {
  declare module.exports: $Exports<'jest-circus/build/utils'>;
}
declare module 'jest-circus/src/event_handler.js' {
  declare module.exports: $Exports<'jest-circus/src/event_handler'>;
}
declare module 'jest-circus/src/format_node_assert_errors.js' {
  declare module.exports: $Exports<'jest-circus/src/format_node_assert_errors'>;
}
declare module 'jest-circus/src/index.js' {
  declare module.exports: $Exports<'jest-circus/src/index'>;
}
declare module 'jest-circus/src/legacy_code_todo_rewrite/jest_adapter_init.js' {
  declare module.exports: $Exports<
    'jest-circus/src/legacy_code_todo_rewrite/jest_adapter_init'
  >;
}
declare module 'jest-circus/src/legacy_code_todo_rewrite/jest_adapter.js' {
  declare module.exports: $Exports<
    'jest-circus/src/legacy_code_todo_rewrite/jest_adapter'
  >;
}
declare module 'jest-circus/src/legacy_code_todo_rewrite/jest_expect.js' {
  declare module.exports: $Exports<
    'jest-circus/src/legacy_code_todo_rewrite/jest_expect'
  >;
}
declare module 'jest-circus/src/run.js' {
  declare module.exports: $Exports<'jest-circus/src/run'>;
}
declare module 'jest-circus/src/state.js' {
  declare module.exports: $Exports<'jest-circus/src/state'>;
}
declare module 'jest-circus/src/utils.js' {
  declare module.exports: $Exports<'jest-circus/src/utils'>;
}
