// flow-typed signature: c65d228b9890997d59ebc68664dc23b5
// flow-typed version: <<STUB>>/lerna_v^2.5.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lerna'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lerna' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lerna/bin/lerna' {
  declare module.exports: any;
}

declare module 'lerna/lib/ChildProcessUtilities' {
  declare module.exports: any;
}

declare module 'lerna/lib/cli' {
  declare module.exports: any;
}

declare module 'lerna/lib/Command' {
  declare module.exports: any;
}

declare module 'lerna/lib/commands/AddCommand' {
  declare module.exports: any;
}

declare module 'lerna/lib/commands/BootstrapCommand' {
  declare module.exports: any;
}

declare module 'lerna/lib/commands/CleanCommand' {
  declare module.exports: any;
}

declare module 'lerna/lib/commands/DiffCommand' {
  declare module.exports: any;
}

declare module 'lerna/lib/commands/ExecCommand' {
  declare module.exports: any;
}

declare module 'lerna/lib/commands/ImportCommand' {
  declare module.exports: any;
}

declare module 'lerna/lib/commands/InitCommand' {
  declare module.exports: any;
}

declare module 'lerna/lib/commands/LinkCommand' {
  declare module.exports: any;
}

declare module 'lerna/lib/commands/LsCommand' {
  declare module.exports: any;
}

declare module 'lerna/lib/commands/PublishCommand' {
  declare module.exports: any;
}

declare module 'lerna/lib/commands/RunCommand' {
  declare module.exports: any;
}

declare module 'lerna/lib/commands/UpdatedCommand' {
  declare module.exports: any;
}

declare module 'lerna/lib/ConventionalChangelogContext' {
  declare module.exports: any;
}

declare module 'lerna/lib/ConventionalCommitUtilities' {
  declare module.exports: any;
}

declare module 'lerna/lib/FileSystemUtilities' {
  declare module.exports: any;
}

declare module 'lerna/lib/GitUtilities' {
  declare module.exports: any;
}

declare module 'lerna/lib/GitVersionParser' {
  declare module.exports: any;
}

declare module 'lerna/lib/index' {
  declare module.exports: any;
}

declare module 'lerna/lib/NpmUtilities' {
  declare module.exports: any;
}

declare module 'lerna/lib/Package' {
  declare module.exports: any;
}

declare module 'lerna/lib/PackageGraph' {
  declare module.exports: any;
}

declare module 'lerna/lib/PackageUtilities' {
  declare module.exports: any;
}

declare module 'lerna/lib/PromptUtilities' {
  declare module.exports: any;
}

declare module 'lerna/lib/Repository' {
  declare module.exports: any;
}

declare module 'lerna/lib/UpdatedPackagesCollector' {
  declare module.exports: any;
}

declare module 'lerna/lib/utils/dependencyIsSatisfied' {
  declare module.exports: any;
}

declare module 'lerna/lib/utils/filterFlags' {
  declare module.exports: any;
}

declare module 'lerna/lib/utils/output' {
  declare module.exports: any;
}

declare module 'lerna/lib/utils/splitVersion' {
  declare module.exports: any;
}

declare module 'lerna/lib/utils/writeLogFile' {
  declare module.exports: any;
}

declare module 'lerna/lib/VersionSerializer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lerna/bin/lerna.js' {
  declare module.exports: $Exports<'lerna/bin/lerna'>;
}
declare module 'lerna/lib/ChildProcessUtilities.js' {
  declare module.exports: $Exports<'lerna/lib/ChildProcessUtilities'>;
}
declare module 'lerna/lib/cli.js' {
  declare module.exports: $Exports<'lerna/lib/cli'>;
}
declare module 'lerna/lib/Command.js' {
  declare module.exports: $Exports<'lerna/lib/Command'>;
}
declare module 'lerna/lib/commands/AddCommand.js' {
  declare module.exports: $Exports<'lerna/lib/commands/AddCommand'>;
}
declare module 'lerna/lib/commands/BootstrapCommand.js' {
  declare module.exports: $Exports<'lerna/lib/commands/BootstrapCommand'>;
}
declare module 'lerna/lib/commands/CleanCommand.js' {
  declare module.exports: $Exports<'lerna/lib/commands/CleanCommand'>;
}
declare module 'lerna/lib/commands/DiffCommand.js' {
  declare module.exports: $Exports<'lerna/lib/commands/DiffCommand'>;
}
declare module 'lerna/lib/commands/ExecCommand.js' {
  declare module.exports: $Exports<'lerna/lib/commands/ExecCommand'>;
}
declare module 'lerna/lib/commands/ImportCommand.js' {
  declare module.exports: $Exports<'lerna/lib/commands/ImportCommand'>;
}
declare module 'lerna/lib/commands/InitCommand.js' {
  declare module.exports: $Exports<'lerna/lib/commands/InitCommand'>;
}
declare module 'lerna/lib/commands/LinkCommand.js' {
  declare module.exports: $Exports<'lerna/lib/commands/LinkCommand'>;
}
declare module 'lerna/lib/commands/LsCommand.js' {
  declare module.exports: $Exports<'lerna/lib/commands/LsCommand'>;
}
declare module 'lerna/lib/commands/PublishCommand.js' {
  declare module.exports: $Exports<'lerna/lib/commands/PublishCommand'>;
}
declare module 'lerna/lib/commands/RunCommand.js' {
  declare module.exports: $Exports<'lerna/lib/commands/RunCommand'>;
}
declare module 'lerna/lib/commands/UpdatedCommand.js' {
  declare module.exports: $Exports<'lerna/lib/commands/UpdatedCommand'>;
}
declare module 'lerna/lib/ConventionalChangelogContext.js' {
  declare module.exports: $Exports<'lerna/lib/ConventionalChangelogContext'>;
}
declare module 'lerna/lib/ConventionalCommitUtilities.js' {
  declare module.exports: $Exports<'lerna/lib/ConventionalCommitUtilities'>;
}
declare module 'lerna/lib/FileSystemUtilities.js' {
  declare module.exports: $Exports<'lerna/lib/FileSystemUtilities'>;
}
declare module 'lerna/lib/GitUtilities.js' {
  declare module.exports: $Exports<'lerna/lib/GitUtilities'>;
}
declare module 'lerna/lib/GitVersionParser.js' {
  declare module.exports: $Exports<'lerna/lib/GitVersionParser'>;
}
declare module 'lerna/lib/index.js' {
  declare module.exports: $Exports<'lerna/lib/index'>;
}
declare module 'lerna/lib/NpmUtilities.js' {
  declare module.exports: $Exports<'lerna/lib/NpmUtilities'>;
}
declare module 'lerna/lib/Package.js' {
  declare module.exports: $Exports<'lerna/lib/Package'>;
}
declare module 'lerna/lib/PackageGraph.js' {
  declare module.exports: $Exports<'lerna/lib/PackageGraph'>;
}
declare module 'lerna/lib/PackageUtilities.js' {
  declare module.exports: $Exports<'lerna/lib/PackageUtilities'>;
}
declare module 'lerna/lib/PromptUtilities.js' {
  declare module.exports: $Exports<'lerna/lib/PromptUtilities'>;
}
declare module 'lerna/lib/Repository.js' {
  declare module.exports: $Exports<'lerna/lib/Repository'>;
}
declare module 'lerna/lib/UpdatedPackagesCollector.js' {
  declare module.exports: $Exports<'lerna/lib/UpdatedPackagesCollector'>;
}
declare module 'lerna/lib/utils/dependencyIsSatisfied.js' {
  declare module.exports: $Exports<'lerna/lib/utils/dependencyIsSatisfied'>;
}
declare module 'lerna/lib/utils/filterFlags.js' {
  declare module.exports: $Exports<'lerna/lib/utils/filterFlags'>;
}
declare module 'lerna/lib/utils/output.js' {
  declare module.exports: $Exports<'lerna/lib/utils/output'>;
}
declare module 'lerna/lib/utils/splitVersion.js' {
  declare module.exports: $Exports<'lerna/lib/utils/splitVersion'>;
}
declare module 'lerna/lib/utils/writeLogFile.js' {
  declare module.exports: $Exports<'lerna/lib/utils/writeLogFile'>;
}
declare module 'lerna/lib/VersionSerializer.js' {
  declare module.exports: $Exports<'lerna/lib/VersionSerializer'>;
}
