// flow-typed signature: d2f8318f67c3422b3f6d2d777b04d829
// flow-typed version: <<STUB>>/match-sorter_v^1.8.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'match-sorter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'match-sorter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'match-sorter/dist/cjs/index' {
  declare module.exports: any;
}

declare module 'match-sorter/dist/umd/match-sorter' {
  declare module.exports: any;
}

declare module 'match-sorter/dist/umd/match-sorter.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'match-sorter/dist/cjs/index.js' {
  declare module.exports: $Exports<'match-sorter/dist/cjs/index'>;
}
declare module 'match-sorter/dist/umd/match-sorter.js' {
  declare module.exports: $Exports<'match-sorter/dist/umd/match-sorter'>;
}
declare module 'match-sorter/dist/umd/match-sorter.min.js' {
  declare module.exports: $Exports<'match-sorter/dist/umd/match-sorter.min'>;
}
