// flow-typed signature: 20ef7430312b5f2921691d8cb66c1869
// flow-typed version: <<STUB>>/monaco-vue_v^0.1.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'monaco-vue'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'monaco-vue' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'monaco-vue/release/min/lib/typescriptServices' {
  declare module.exports: any;
}

declare module 'monaco-vue/release/min/monaco.contribution' {
  declare module.exports: any;
}

declare module 'monaco-vue/release/min/vueMode' {
  declare module.exports: any;
}

declare module 'monaco-vue/release/min/vueWorker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'monaco-vue/release/min/lib/typescriptServices.js' {
  declare module.exports: $Exports<
    'monaco-vue/release/min/lib/typescriptServices'
  >;
}
declare module 'monaco-vue/release/min/monaco.contribution.js' {
  declare module.exports: $Exports<
    'monaco-vue/release/min/monaco.contribution'
  >;
}
declare module 'monaco-vue/release/min/vueMode.js' {
  declare module.exports: $Exports<'monaco-vue/release/min/vueMode'>;
}
declare module 'monaco-vue/release/min/vueWorker.js' {
  declare module.exports: $Exports<'monaco-vue/release/min/vueWorker'>;
}
