// flow-typed signature: 588e5a9af64c8fe2e0053b2d8418e8be
// flow-typed version: <<STUB>>/monaco-editor_vCompuIves/codesandbox-monaco-editor/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'monaco-editor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'monaco-editor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'monaco-editor/dev/vs/base/worker/workerMain' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/basic-languages/src/bat' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/basic-languages/src/coffee' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/basic-languages/src/cpp' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/basic-languages/src/csharp' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/basic-languages/src/css' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/basic-languages/src/dockerfile' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/basic-languages/src/fsharp' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/basic-languages/src/go' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/basic-languages/src/handlebars' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/basic-languages/src/html' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/basic-languages/src/ini' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/basic-languages/src/java' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/basic-languages/src/less' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/basic-languages/src/lua' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/basic-languages/src/markdown' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/basic-languages/src/msdax' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/basic-languages/src/objective-c' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/basic-languages/src/php' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/basic-languages/src/postiats' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/basic-languages/src/powershell' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/basic-languages/src/pug' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/basic-languages/src/python' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/basic-languages/src/r' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/basic-languages/src/razor' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/basic-languages/src/ruby' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/basic-languages/src/scss' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/basic-languages/src/solidity' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/basic-languages/src/sql' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/basic-languages/src/swift' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/basic-languages/src/vb' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/basic-languages/src/xml' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/basic-languages/src/yaml' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/editor/editor.main' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/editor/editor.main.nls.de' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/editor/editor.main.nls.es' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/editor/editor.main.nls.fr' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/editor/editor.main.nls.hu' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/editor/editor.main.nls.it' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/editor/editor.main.nls.ja' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/editor/editor.main.nls' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/editor/editor.main.nls.ko' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/editor/editor.main.nls.pt-br' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/editor/editor.main.nls.ru' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/editor/editor.main.nls.tr' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/editor/editor.main.nls.zh-cn' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/editor/editor.main.nls.zh-tw' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/language/css/cssMode' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/language/css/cssWorker' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/language/html/htmlMode' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/language/html/htmlWorker' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/language/json/jsonMode' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/language/json/jsonWorker' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/language/typescript/lib/typescriptServices' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/language/typescript/src/mode' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/language/typescript/src/worker' {
  declare module.exports: any;
}

declare module 'monaco-editor/dev/vs/loader' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/base/worker/workerMain' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/basic-languages/src/bat' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/basic-languages/src/coffee' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/basic-languages/src/cpp' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/basic-languages/src/csharp' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/basic-languages/src/css' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/basic-languages/src/dockerfile' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/basic-languages/src/fsharp' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/basic-languages/src/go' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/basic-languages/src/handlebars' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/basic-languages/src/html' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/basic-languages/src/ini' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/basic-languages/src/java' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/basic-languages/src/less' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/basic-languages/src/lua' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/basic-languages/src/markdown' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/basic-languages/src/msdax' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/basic-languages/src/objective-c' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/basic-languages/src/php' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/basic-languages/src/postiats' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/basic-languages/src/powershell' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/basic-languages/src/pug' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/basic-languages/src/python' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/basic-languages/src/r' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/basic-languages/src/razor' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/basic-languages/src/ruby' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/basic-languages/src/scss' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/basic-languages/src/solidity' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/basic-languages/src/sql' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/basic-languages/src/swift' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/basic-languages/src/vb' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/basic-languages/src/xml' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/basic-languages/src/yaml' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/editor/editor.main' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/editor/editor.main.nls.de' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/editor/editor.main.nls.es' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/editor/editor.main.nls.fr' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/editor/editor.main.nls.hu' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/editor/editor.main.nls.it' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/editor/editor.main.nls.ja' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/editor/editor.main.nls' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/editor/editor.main.nls.ko' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/editor/editor.main.nls.pt-br' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/editor/editor.main.nls.ru' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/editor/editor.main.nls.tr' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/editor/editor.main.nls.zh-cn' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/editor/editor.main.nls.zh-tw' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/language/css/cssMode' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/language/css/cssWorker' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/language/html/htmlMode' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/language/html/htmlWorker' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/language/json/jsonMode' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/language/json/jsonWorker' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/language/typescript/lib/typescriptServices' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/language/typescript/src/mode' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/language/typescript/src/worker' {
  declare module.exports: any;
}

declare module 'monaco-editor/min/vs/loader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'monaco-editor/dev/vs/base/worker/workerMain.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/base/worker/workerMain'
  >;
}
declare module 'monaco-editor/dev/vs/basic-languages/src/bat.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/basic-languages/src/bat'
  >;
}
declare module 'monaco-editor/dev/vs/basic-languages/src/coffee.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/basic-languages/src/coffee'
  >;
}
declare module 'monaco-editor/dev/vs/basic-languages/src/cpp.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/basic-languages/src/cpp'
  >;
}
declare module 'monaco-editor/dev/vs/basic-languages/src/csharp.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/basic-languages/src/csharp'
  >;
}
declare module 'monaco-editor/dev/vs/basic-languages/src/css.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/basic-languages/src/css'
  >;
}
declare module 'monaco-editor/dev/vs/basic-languages/src/dockerfile.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/basic-languages/src/dockerfile'
  >;
}
declare module 'monaco-editor/dev/vs/basic-languages/src/fsharp.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/basic-languages/src/fsharp'
  >;
}
declare module 'monaco-editor/dev/vs/basic-languages/src/go.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/basic-languages/src/go'
  >;
}
declare module 'monaco-editor/dev/vs/basic-languages/src/handlebars.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/basic-languages/src/handlebars'
  >;
}
declare module 'monaco-editor/dev/vs/basic-languages/src/html.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/basic-languages/src/html'
  >;
}
declare module 'monaco-editor/dev/vs/basic-languages/src/ini.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/basic-languages/src/ini'
  >;
}
declare module 'monaco-editor/dev/vs/basic-languages/src/java.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/basic-languages/src/java'
  >;
}
declare module 'monaco-editor/dev/vs/basic-languages/src/less.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/basic-languages/src/less'
  >;
}
declare module 'monaco-editor/dev/vs/basic-languages/src/lua.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/basic-languages/src/lua'
  >;
}
declare module 'monaco-editor/dev/vs/basic-languages/src/markdown.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/basic-languages/src/markdown'
  >;
}
declare module 'monaco-editor/dev/vs/basic-languages/src/msdax.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/basic-languages/src/msdax'
  >;
}
declare module 'monaco-editor/dev/vs/basic-languages/src/objective-c.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/basic-languages/src/objective-c'
  >;
}
declare module 'monaco-editor/dev/vs/basic-languages/src/php.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/basic-languages/src/php'
  >;
}
declare module 'monaco-editor/dev/vs/basic-languages/src/postiats.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/basic-languages/src/postiats'
  >;
}
declare module 'monaco-editor/dev/vs/basic-languages/src/powershell.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/basic-languages/src/powershell'
  >;
}
declare module 'monaco-editor/dev/vs/basic-languages/src/pug.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/basic-languages/src/pug'
  >;
}
declare module 'monaco-editor/dev/vs/basic-languages/src/python.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/basic-languages/src/python'
  >;
}
declare module 'monaco-editor/dev/vs/basic-languages/src/r.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/basic-languages/src/r'
  >;
}
declare module 'monaco-editor/dev/vs/basic-languages/src/razor.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/basic-languages/src/razor'
  >;
}
declare module 'monaco-editor/dev/vs/basic-languages/src/ruby.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/basic-languages/src/ruby'
  >;
}
declare module 'monaco-editor/dev/vs/basic-languages/src/scss.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/basic-languages/src/scss'
  >;
}
declare module 'monaco-editor/dev/vs/basic-languages/src/solidity.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/basic-languages/src/solidity'
  >;
}
declare module 'monaco-editor/dev/vs/basic-languages/src/sql.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/basic-languages/src/sql'
  >;
}
declare module 'monaco-editor/dev/vs/basic-languages/src/swift.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/basic-languages/src/swift'
  >;
}
declare module 'monaco-editor/dev/vs/basic-languages/src/vb.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/basic-languages/src/vb'
  >;
}
declare module 'monaco-editor/dev/vs/basic-languages/src/xml.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/basic-languages/src/xml'
  >;
}
declare module 'monaco-editor/dev/vs/basic-languages/src/yaml.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/basic-languages/src/yaml'
  >;
}
declare module 'monaco-editor/dev/vs/editor/editor.main.js' {
  declare module.exports: $Exports<'monaco-editor/dev/vs/editor/editor.main'>;
}
declare module 'monaco-editor/dev/vs/editor/editor.main.nls.de.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/editor/editor.main.nls.de'
  >;
}
declare module 'monaco-editor/dev/vs/editor/editor.main.nls.es.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/editor/editor.main.nls.es'
  >;
}
declare module 'monaco-editor/dev/vs/editor/editor.main.nls.fr.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/editor/editor.main.nls.fr'
  >;
}
declare module 'monaco-editor/dev/vs/editor/editor.main.nls.hu.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/editor/editor.main.nls.hu'
  >;
}
declare module 'monaco-editor/dev/vs/editor/editor.main.nls.it.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/editor/editor.main.nls.it'
  >;
}
declare module 'monaco-editor/dev/vs/editor/editor.main.nls.ja.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/editor/editor.main.nls.ja'
  >;
}
declare module 'monaco-editor/dev/vs/editor/editor.main.nls.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/editor/editor.main.nls'
  >;
}
declare module 'monaco-editor/dev/vs/editor/editor.main.nls.ko.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/editor/editor.main.nls.ko'
  >;
}
declare module 'monaco-editor/dev/vs/editor/editor.main.nls.pt-br.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/editor/editor.main.nls.pt-br'
  >;
}
declare module 'monaco-editor/dev/vs/editor/editor.main.nls.ru.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/editor/editor.main.nls.ru'
  >;
}
declare module 'monaco-editor/dev/vs/editor/editor.main.nls.tr.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/editor/editor.main.nls.tr'
  >;
}
declare module 'monaco-editor/dev/vs/editor/editor.main.nls.zh-cn.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/editor/editor.main.nls.zh-cn'
  >;
}
declare module 'monaco-editor/dev/vs/editor/editor.main.nls.zh-tw.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/editor/editor.main.nls.zh-tw'
  >;
}
declare module 'monaco-editor/dev/vs/language/css/cssMode.js' {
  declare module.exports: $Exports<'monaco-editor/dev/vs/language/css/cssMode'>;
}
declare module 'monaco-editor/dev/vs/language/css/cssWorker.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/language/css/cssWorker'
  >;
}
declare module 'monaco-editor/dev/vs/language/html/htmlMode.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/language/html/htmlMode'
  >;
}
declare module 'monaco-editor/dev/vs/language/html/htmlWorker.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/language/html/htmlWorker'
  >;
}
declare module 'monaco-editor/dev/vs/language/json/jsonMode.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/language/json/jsonMode'
  >;
}
declare module 'monaco-editor/dev/vs/language/json/jsonWorker.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/language/json/jsonWorker'
  >;
}
declare module 'monaco-editor/dev/vs/language/typescript/lib/typescriptServices.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/language/typescript/lib/typescriptServices'
  >;
}
declare module 'monaco-editor/dev/vs/language/typescript/src/mode.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/language/typescript/src/mode'
  >;
}
declare module 'monaco-editor/dev/vs/language/typescript/src/worker.js' {
  declare module.exports: $Exports<
    'monaco-editor/dev/vs/language/typescript/src/worker'
  >;
}
declare module 'monaco-editor/dev/vs/loader.js' {
  declare module.exports: $Exports<'monaco-editor/dev/vs/loader'>;
}
declare module 'monaco-editor/min/vs/base/worker/workerMain.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/base/worker/workerMain'
  >;
}
declare module 'monaco-editor/min/vs/basic-languages/src/bat.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/basic-languages/src/bat'
  >;
}
declare module 'monaco-editor/min/vs/basic-languages/src/coffee.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/basic-languages/src/coffee'
  >;
}
declare module 'monaco-editor/min/vs/basic-languages/src/cpp.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/basic-languages/src/cpp'
  >;
}
declare module 'monaco-editor/min/vs/basic-languages/src/csharp.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/basic-languages/src/csharp'
  >;
}
declare module 'monaco-editor/min/vs/basic-languages/src/css.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/basic-languages/src/css'
  >;
}
declare module 'monaco-editor/min/vs/basic-languages/src/dockerfile.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/basic-languages/src/dockerfile'
  >;
}
declare module 'monaco-editor/min/vs/basic-languages/src/fsharp.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/basic-languages/src/fsharp'
  >;
}
declare module 'monaco-editor/min/vs/basic-languages/src/go.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/basic-languages/src/go'
  >;
}
declare module 'monaco-editor/min/vs/basic-languages/src/handlebars.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/basic-languages/src/handlebars'
  >;
}
declare module 'monaco-editor/min/vs/basic-languages/src/html.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/basic-languages/src/html'
  >;
}
declare module 'monaco-editor/min/vs/basic-languages/src/ini.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/basic-languages/src/ini'
  >;
}
declare module 'monaco-editor/min/vs/basic-languages/src/java.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/basic-languages/src/java'
  >;
}
declare module 'monaco-editor/min/vs/basic-languages/src/less.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/basic-languages/src/less'
  >;
}
declare module 'monaco-editor/min/vs/basic-languages/src/lua.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/basic-languages/src/lua'
  >;
}
declare module 'monaco-editor/min/vs/basic-languages/src/markdown.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/basic-languages/src/markdown'
  >;
}
declare module 'monaco-editor/min/vs/basic-languages/src/msdax.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/basic-languages/src/msdax'
  >;
}
declare module 'monaco-editor/min/vs/basic-languages/src/objective-c.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/basic-languages/src/objective-c'
  >;
}
declare module 'monaco-editor/min/vs/basic-languages/src/php.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/basic-languages/src/php'
  >;
}
declare module 'monaco-editor/min/vs/basic-languages/src/postiats.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/basic-languages/src/postiats'
  >;
}
declare module 'monaco-editor/min/vs/basic-languages/src/powershell.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/basic-languages/src/powershell'
  >;
}
declare module 'monaco-editor/min/vs/basic-languages/src/pug.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/basic-languages/src/pug'
  >;
}
declare module 'monaco-editor/min/vs/basic-languages/src/python.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/basic-languages/src/python'
  >;
}
declare module 'monaco-editor/min/vs/basic-languages/src/r.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/basic-languages/src/r'
  >;
}
declare module 'monaco-editor/min/vs/basic-languages/src/razor.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/basic-languages/src/razor'
  >;
}
declare module 'monaco-editor/min/vs/basic-languages/src/ruby.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/basic-languages/src/ruby'
  >;
}
declare module 'monaco-editor/min/vs/basic-languages/src/scss.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/basic-languages/src/scss'
  >;
}
declare module 'monaco-editor/min/vs/basic-languages/src/solidity.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/basic-languages/src/solidity'
  >;
}
declare module 'monaco-editor/min/vs/basic-languages/src/sql.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/basic-languages/src/sql'
  >;
}
declare module 'monaco-editor/min/vs/basic-languages/src/swift.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/basic-languages/src/swift'
  >;
}
declare module 'monaco-editor/min/vs/basic-languages/src/vb.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/basic-languages/src/vb'
  >;
}
declare module 'monaco-editor/min/vs/basic-languages/src/xml.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/basic-languages/src/xml'
  >;
}
declare module 'monaco-editor/min/vs/basic-languages/src/yaml.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/basic-languages/src/yaml'
  >;
}
declare module 'monaco-editor/min/vs/editor/editor.main.js' {
  declare module.exports: $Exports<'monaco-editor/min/vs/editor/editor.main'>;
}
declare module 'monaco-editor/min/vs/editor/editor.main.nls.de.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/editor/editor.main.nls.de'
  >;
}
declare module 'monaco-editor/min/vs/editor/editor.main.nls.es.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/editor/editor.main.nls.es'
  >;
}
declare module 'monaco-editor/min/vs/editor/editor.main.nls.fr.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/editor/editor.main.nls.fr'
  >;
}
declare module 'monaco-editor/min/vs/editor/editor.main.nls.hu.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/editor/editor.main.nls.hu'
  >;
}
declare module 'monaco-editor/min/vs/editor/editor.main.nls.it.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/editor/editor.main.nls.it'
  >;
}
declare module 'monaco-editor/min/vs/editor/editor.main.nls.ja.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/editor/editor.main.nls.ja'
  >;
}
declare module 'monaco-editor/min/vs/editor/editor.main.nls.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/editor/editor.main.nls'
  >;
}
declare module 'monaco-editor/min/vs/editor/editor.main.nls.ko.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/editor/editor.main.nls.ko'
  >;
}
declare module 'monaco-editor/min/vs/editor/editor.main.nls.pt-br.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/editor/editor.main.nls.pt-br'
  >;
}
declare module 'monaco-editor/min/vs/editor/editor.main.nls.ru.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/editor/editor.main.nls.ru'
  >;
}
declare module 'monaco-editor/min/vs/editor/editor.main.nls.tr.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/editor/editor.main.nls.tr'
  >;
}
declare module 'monaco-editor/min/vs/editor/editor.main.nls.zh-cn.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/editor/editor.main.nls.zh-cn'
  >;
}
declare module 'monaco-editor/min/vs/editor/editor.main.nls.zh-tw.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/editor/editor.main.nls.zh-tw'
  >;
}
declare module 'monaco-editor/min/vs/language/css/cssMode.js' {
  declare module.exports: $Exports<'monaco-editor/min/vs/language/css/cssMode'>;
}
declare module 'monaco-editor/min/vs/language/css/cssWorker.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/language/css/cssWorker'
  >;
}
declare module 'monaco-editor/min/vs/language/html/htmlMode.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/language/html/htmlMode'
  >;
}
declare module 'monaco-editor/min/vs/language/html/htmlWorker.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/language/html/htmlWorker'
  >;
}
declare module 'monaco-editor/min/vs/language/json/jsonMode.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/language/json/jsonMode'
  >;
}
declare module 'monaco-editor/min/vs/language/json/jsonWorker.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/language/json/jsonWorker'
  >;
}
declare module 'monaco-editor/min/vs/language/typescript/lib/typescriptServices.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/language/typescript/lib/typescriptServices'
  >;
}
declare module 'monaco-editor/min/vs/language/typescript/src/mode.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/language/typescript/src/mode'
  >;
}
declare module 'monaco-editor/min/vs/language/typescript/src/worker.js' {
  declare module.exports: $Exports<
    'monaco-editor/min/vs/language/typescript/src/worker'
  >;
}
declare module 'monaco-editor/min/vs/loader.js' {
  declare module.exports: $Exports<'monaco-editor/min/vs/loader'>;
}
