// flow-typed signature: 50cbd97846cf5ad95be2ac496850454b
// flow-typed version: <<STUB>>/path-override-webpack-plugin_v^0.1.2/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'path-override-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'path-override-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'path-override-webpack-plugin/src/__tests__/path-override-test' {
  declare module.exports: any;
}

declare module 'path-override-webpack-plugin/src/path-override' {
  declare module.exports: any;
}

// Filename aliases
declare module 'path-override-webpack-plugin/src/__tests__/path-override-test.js' {
  declare module.exports: $Exports<
    'path-override-webpack-plugin/src/__tests__/path-override-test'
  >;
}
declare module 'path-override-webpack-plugin/src/path-override.js' {
  declare module.exports: $Exports<
    'path-override-webpack-plugin/src/path-override'
  >;
}
