// flow-typed signature: 3064d82da2505ce0a8c8e91bfbc0058d
// flow-typed version: <<STUB>>/postcss-selector-parser_v^2.2.3/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-selector-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-selector-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-selector-parser/dist/index' {
  declare module.exports: any;
}

declare module 'postcss-selector-parser/dist/parser' {
  declare module.exports: any;
}

declare module 'postcss-selector-parser/dist/processor' {
  declare module.exports: any;
}

declare module 'postcss-selector-parser/dist/selectors/attribute' {
  declare module.exports: any;
}

declare module 'postcss-selector-parser/dist/selectors/className' {
  declare module.exports: any;
}

declare module 'postcss-selector-parser/dist/selectors/combinator' {
  declare module.exports: any;
}

declare module 'postcss-selector-parser/dist/selectors/comment' {
  declare module.exports: any;
}

declare module 'postcss-selector-parser/dist/selectors/container' {
  declare module.exports: any;
}

declare module 'postcss-selector-parser/dist/selectors/id' {
  declare module.exports: any;
}

declare module 'postcss-selector-parser/dist/selectors/namespace' {
  declare module.exports: any;
}

declare module 'postcss-selector-parser/dist/selectors/nesting' {
  declare module.exports: any;
}

declare module 'postcss-selector-parser/dist/selectors/node' {
  declare module.exports: any;
}

declare module 'postcss-selector-parser/dist/selectors/pseudo' {
  declare module.exports: any;
}

declare module 'postcss-selector-parser/dist/selectors/root' {
  declare module.exports: any;
}

declare module 'postcss-selector-parser/dist/selectors/selector' {
  declare module.exports: any;
}

declare module 'postcss-selector-parser/dist/selectors/string' {
  declare module.exports: any;
}

declare module 'postcss-selector-parser/dist/selectors/tag' {
  declare module.exports: any;
}

declare module 'postcss-selector-parser/dist/selectors/types' {
  declare module.exports: any;
}

declare module 'postcss-selector-parser/dist/selectors/universal' {
  declare module.exports: any;
}

declare module 'postcss-selector-parser/dist/sortAscending' {
  declare module.exports: any;
}

declare module 'postcss-selector-parser/dist/tokenize' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-selector-parser/dist/index.js' {
  declare module.exports: $Exports<'postcss-selector-parser/dist/index'>;
}
declare module 'postcss-selector-parser/dist/parser.js' {
  declare module.exports: $Exports<'postcss-selector-parser/dist/parser'>;
}
declare module 'postcss-selector-parser/dist/processor.js' {
  declare module.exports: $Exports<'postcss-selector-parser/dist/processor'>;
}
declare module 'postcss-selector-parser/dist/selectors/attribute.js' {
  declare module.exports: $Exports<
    'postcss-selector-parser/dist/selectors/attribute'
  >;
}
declare module 'postcss-selector-parser/dist/selectors/className.js' {
  declare module.exports: $Exports<
    'postcss-selector-parser/dist/selectors/className'
  >;
}
declare module 'postcss-selector-parser/dist/selectors/combinator.js' {
  declare module.exports: $Exports<
    'postcss-selector-parser/dist/selectors/combinator'
  >;
}
declare module 'postcss-selector-parser/dist/selectors/comment.js' {
  declare module.exports: $Exports<
    'postcss-selector-parser/dist/selectors/comment'
  >;
}
declare module 'postcss-selector-parser/dist/selectors/container.js' {
  declare module.exports: $Exports<
    'postcss-selector-parser/dist/selectors/container'
  >;
}
declare module 'postcss-selector-parser/dist/selectors/id.js' {
  declare module.exports: $Exports<'postcss-selector-parser/dist/selectors/id'>;
}
declare module 'postcss-selector-parser/dist/selectors/namespace.js' {
  declare module.exports: $Exports<
    'postcss-selector-parser/dist/selectors/namespace'
  >;
}
declare module 'postcss-selector-parser/dist/selectors/nesting.js' {
  declare module.exports: $Exports<
    'postcss-selector-parser/dist/selectors/nesting'
  >;
}
declare module 'postcss-selector-parser/dist/selectors/node.js' {
  declare module.exports: $Exports<
    'postcss-selector-parser/dist/selectors/node'
  >;
}
declare module 'postcss-selector-parser/dist/selectors/pseudo.js' {
  declare module.exports: $Exports<
    'postcss-selector-parser/dist/selectors/pseudo'
  >;
}
declare module 'postcss-selector-parser/dist/selectors/root.js' {
  declare module.exports: $Exports<
    'postcss-selector-parser/dist/selectors/root'
  >;
}
declare module 'postcss-selector-parser/dist/selectors/selector.js' {
  declare module.exports: $Exports<
    'postcss-selector-parser/dist/selectors/selector'
  >;
}
declare module 'postcss-selector-parser/dist/selectors/string.js' {
  declare module.exports: $Exports<
    'postcss-selector-parser/dist/selectors/string'
  >;
}
declare module 'postcss-selector-parser/dist/selectors/tag.js' {
  declare module.exports: $Exports<
    'postcss-selector-parser/dist/selectors/tag'
  >;
}
declare module 'postcss-selector-parser/dist/selectors/types.js' {
  declare module.exports: $Exports<
    'postcss-selector-parser/dist/selectors/types'
  >;
}
declare module 'postcss-selector-parser/dist/selectors/universal.js' {
  declare module.exports: $Exports<
    'postcss-selector-parser/dist/selectors/universal'
  >;
}
declare module 'postcss-selector-parser/dist/sortAscending.js' {
  declare module.exports: $Exports<
    'postcss-selector-parser/dist/sortAscending'
  >;
}
declare module 'postcss-selector-parser/dist/tokenize.js' {
  declare module.exports: $Exports<'postcss-selector-parser/dist/tokenize'>;
}
