// flow-typed signature: d4179a4273b0b820fe42687ba8d2b02a
// flow-typed version: <<STUB>>/prettier_v^0.22.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prettier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'prettier' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prettier/bin/prettier' {
  declare module.exports: any;
}

declare module 'prettier/docs/prettier.min' {
  declare module.exports: any;
}

declare module 'prettier/docs/rollup.config' {
  declare module.exports: any;
}

declare module 'prettier/src/comments' {
  declare module.exports: any;
}

declare module 'prettier/src/deprecated' {
  declare module.exports: any;
}

declare module 'prettier/src/doc-builders' {
  declare module.exports: any;
}

declare module 'prettier/src/doc-debug' {
  declare module.exports: any;
}

declare module 'prettier/src/doc-printer' {
  declare module.exports: any;
}

declare module 'prettier/src/doc-utils' {
  declare module.exports: any;
}

declare module 'prettier/src/fast-path' {
  declare module.exports: any;
}

declare module 'prettier/src/options' {
  declare module.exports: any;
}

declare module 'prettier/src/parser' {
  declare module.exports: any;
}

declare module 'prettier/src/printer' {
  declare module.exports: any;
}

declare module 'prettier/src/util' {
  declare module.exports: any;
}

declare module 'prettier/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prettier/bin/prettier.js' {
  declare module.exports: $Exports<'prettier/bin/prettier'>;
}
declare module 'prettier/docs/prettier.min.js' {
  declare module.exports: $Exports<'prettier/docs/prettier.min'>;
}
declare module 'prettier/docs/rollup.config.js' {
  declare module.exports: $Exports<'prettier/docs/rollup.config'>;
}
declare module 'prettier/index' {
  declare module.exports: $Exports<'prettier'>;
}
declare module 'prettier/index.js' {
  declare module.exports: $Exports<'prettier'>;
}
declare module 'prettier/src/comments.js' {
  declare module.exports: $Exports<'prettier/src/comments'>;
}
declare module 'prettier/src/deprecated.js' {
  declare module.exports: $Exports<'prettier/src/deprecated'>;
}
declare module 'prettier/src/doc-builders.js' {
  declare module.exports: $Exports<'prettier/src/doc-builders'>;
}
declare module 'prettier/src/doc-debug.js' {
  declare module.exports: $Exports<'prettier/src/doc-debug'>;
}
declare module 'prettier/src/doc-printer.js' {
  declare module.exports: $Exports<'prettier/src/doc-printer'>;
}
declare module 'prettier/src/doc-utils.js' {
  declare module.exports: $Exports<'prettier/src/doc-utils'>;
}
declare module 'prettier/src/fast-path.js' {
  declare module.exports: $Exports<'prettier/src/fast-path'>;
}
declare module 'prettier/src/options.js' {
  declare module.exports: $Exports<'prettier/src/options'>;
}
declare module 'prettier/src/parser.js' {
  declare module.exports: $Exports<'prettier/src/parser'>;
}
declare module 'prettier/src/printer.js' {
  declare module.exports: $Exports<'prettier/src/printer'>;
}
declare module 'prettier/src/util.js' {
  declare module.exports: $Exports<'prettier/src/util'>;
}
declare module 'prettier/test.js' {
  declare module.exports: $Exports<'prettier/test'>;
}
