// flow-typed signature: b79603a14c4bc12d8f64b587768e3b66
// flow-typed version: <<STUB>>/puppeteer_v^0.12.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'puppeteer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'puppeteer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'puppeteer/DeviceDescriptors' {
  declare module.exports: any;
}

declare module 'puppeteer/examples/block-images' {
  declare module.exports: any;
}

declare module 'puppeteer/examples/custom-event' {
  declare module.exports: any;
}

declare module 'puppeteer/examples/detect-sniff' {
  declare module.exports: any;
}

declare module 'puppeteer/examples/pdf' {
  declare module.exports: any;
}

declare module 'puppeteer/examples/proxy' {
  declare module.exports: any;
}

declare module 'puppeteer/examples/screenshot-fullpage' {
  declare module.exports: any;
}

declare module 'puppeteer/examples/screenshot' {
  declare module.exports: any;
}

declare module 'puppeteer/examples/search' {
  declare module.exports: any;
}

declare module 'puppeteer/install' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/Browser' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/Connection' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/Dialog' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/ElementHandle' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/EmulationManager' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/ExecutionContext' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/FrameManager' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/Input' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/Launcher' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/Multimap' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/NavigatorWatcher' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/NetworkManager' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/Page' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/Puppeteer' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/Tracing' {
  declare module.exports: any;
}

declare module 'puppeteer/lib/helper' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/Browser' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/Connection' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/Dialog' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/ElementHandle' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/EmulationManager' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/ExecutionContext' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/FrameManager' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/Input' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/Launcher' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/Multimap' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/NavigatorWatcher' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/NetworkManager' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/Page' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/Puppeteer' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/Tracing' {
  declare module.exports: any;
}

declare module 'puppeteer/node6/helper' {
  declare module.exports: any;
}

declare module 'puppeteer/utils/ChromiumDownloader' {
  declare module.exports: any;
}

declare module 'puppeteer/utils/ESTreeWalker' {
  declare module.exports: any;
}

declare module 'puppeteer/utils/check_availability' {
  declare module.exports: any;
}

declare module 'puppeteer/utils/doclint/Message' {
  declare module.exports: any;
}

declare module 'puppeteer/utils/doclint/SourceFactory' {
  declare module.exports: any;
}

declare module 'puppeteer/utils/doclint/check_public_api/Documentation' {
  declare module.exports: any;
}

declare module 'puppeteer/utils/doclint/check_public_api/JSBuilder' {
  declare module.exports: any;
}

declare module 'puppeteer/utils/doclint/check_public_api/MDBuilder' {
  declare module.exports: any;
}

declare module 'puppeteer/utils/doclint/check_public_api/index' {
  declare module.exports: any;
}

declare module 'puppeteer/utils/doclint/cli' {
  declare module.exports: any;
}

declare module 'puppeteer/utils/doclint/preprocessor/index' {
  declare module.exports: any;
}

declare module 'puppeteer/utils/doclint/preprocessor/test' {
  declare module.exports: any;
}

declare module 'puppeteer/utils/doclint/toc' {
  declare module.exports: any;
}

declare module 'puppeteer/utils/fetch_devices' {
  declare module.exports: any;
}

// Filename aliases
declare module 'puppeteer/DeviceDescriptors.js' {
  declare module.exports: $Exports<'puppeteer/DeviceDescriptors'>;
}
declare module 'puppeteer/examples/block-images.js' {
  declare module.exports: $Exports<'puppeteer/examples/block-images'>;
}
declare module 'puppeteer/examples/custom-event.js' {
  declare module.exports: $Exports<'puppeteer/examples/custom-event'>;
}
declare module 'puppeteer/examples/detect-sniff.js' {
  declare module.exports: $Exports<'puppeteer/examples/detect-sniff'>;
}
declare module 'puppeteer/examples/pdf.js' {
  declare module.exports: $Exports<'puppeteer/examples/pdf'>;
}
declare module 'puppeteer/examples/proxy.js' {
  declare module.exports: $Exports<'puppeteer/examples/proxy'>;
}
declare module 'puppeteer/examples/screenshot-fullpage.js' {
  declare module.exports: $Exports<'puppeteer/examples/screenshot-fullpage'>;
}
declare module 'puppeteer/examples/screenshot.js' {
  declare module.exports: $Exports<'puppeteer/examples/screenshot'>;
}
declare module 'puppeteer/examples/search.js' {
  declare module.exports: $Exports<'puppeteer/examples/search'>;
}
declare module 'puppeteer/index' {
  declare module.exports: $Exports<'puppeteer'>;
}
declare module 'puppeteer/index.js' {
  declare module.exports: $Exports<'puppeteer'>;
}
declare module 'puppeteer/install.js' {
  declare module.exports: $Exports<'puppeteer/install'>;
}
declare module 'puppeteer/lib/Browser.js' {
  declare module.exports: $Exports<'puppeteer/lib/Browser'>;
}
declare module 'puppeteer/lib/Connection.js' {
  declare module.exports: $Exports<'puppeteer/lib/Connection'>;
}
declare module 'puppeteer/lib/Dialog.js' {
  declare module.exports: $Exports<'puppeteer/lib/Dialog'>;
}
declare module 'puppeteer/lib/ElementHandle.js' {
  declare module.exports: $Exports<'puppeteer/lib/ElementHandle'>;
}
declare module 'puppeteer/lib/EmulationManager.js' {
  declare module.exports: $Exports<'puppeteer/lib/EmulationManager'>;
}
declare module 'puppeteer/lib/ExecutionContext.js' {
  declare module.exports: $Exports<'puppeteer/lib/ExecutionContext'>;
}
declare module 'puppeteer/lib/FrameManager.js' {
  declare module.exports: $Exports<'puppeteer/lib/FrameManager'>;
}
declare module 'puppeteer/lib/Input.js' {
  declare module.exports: $Exports<'puppeteer/lib/Input'>;
}
declare module 'puppeteer/lib/Launcher.js' {
  declare module.exports: $Exports<'puppeteer/lib/Launcher'>;
}
declare module 'puppeteer/lib/Multimap.js' {
  declare module.exports: $Exports<'puppeteer/lib/Multimap'>;
}
declare module 'puppeteer/lib/NavigatorWatcher.js' {
  declare module.exports: $Exports<'puppeteer/lib/NavigatorWatcher'>;
}
declare module 'puppeteer/lib/NetworkManager.js' {
  declare module.exports: $Exports<'puppeteer/lib/NetworkManager'>;
}
declare module 'puppeteer/lib/Page.js' {
  declare module.exports: $Exports<'puppeteer/lib/Page'>;
}
declare module 'puppeteer/lib/Puppeteer.js' {
  declare module.exports: $Exports<'puppeteer/lib/Puppeteer'>;
}
declare module 'puppeteer/lib/Tracing.js' {
  declare module.exports: $Exports<'puppeteer/lib/Tracing'>;
}
declare module 'puppeteer/lib/helper.js' {
  declare module.exports: $Exports<'puppeteer/lib/helper'>;
}
declare module 'puppeteer/node6/Browser.js' {
  declare module.exports: $Exports<'puppeteer/node6/Browser'>;
}
declare module 'puppeteer/node6/Connection.js' {
  declare module.exports: $Exports<'puppeteer/node6/Connection'>;
}
declare module 'puppeteer/node6/Dialog.js' {
  declare module.exports: $Exports<'puppeteer/node6/Dialog'>;
}
declare module 'puppeteer/node6/ElementHandle.js' {
  declare module.exports: $Exports<'puppeteer/node6/ElementHandle'>;
}
declare module 'puppeteer/node6/EmulationManager.js' {
  declare module.exports: $Exports<'puppeteer/node6/EmulationManager'>;
}
declare module 'puppeteer/node6/ExecutionContext.js' {
  declare module.exports: $Exports<'puppeteer/node6/ExecutionContext'>;
}
declare module 'puppeteer/node6/FrameManager.js' {
  declare module.exports: $Exports<'puppeteer/node6/FrameManager'>;
}
declare module 'puppeteer/node6/Input.js' {
  declare module.exports: $Exports<'puppeteer/node6/Input'>;
}
declare module 'puppeteer/node6/Launcher.js' {
  declare module.exports: $Exports<'puppeteer/node6/Launcher'>;
}
declare module 'puppeteer/node6/Multimap.js' {
  declare module.exports: $Exports<'puppeteer/node6/Multimap'>;
}
declare module 'puppeteer/node6/NavigatorWatcher.js' {
  declare module.exports: $Exports<'puppeteer/node6/NavigatorWatcher'>;
}
declare module 'puppeteer/node6/NetworkManager.js' {
  declare module.exports: $Exports<'puppeteer/node6/NetworkManager'>;
}
declare module 'puppeteer/node6/Page.js' {
  declare module.exports: $Exports<'puppeteer/node6/Page'>;
}
declare module 'puppeteer/node6/Puppeteer.js' {
  declare module.exports: $Exports<'puppeteer/node6/Puppeteer'>;
}
declare module 'puppeteer/node6/Tracing.js' {
  declare module.exports: $Exports<'puppeteer/node6/Tracing'>;
}
declare module 'puppeteer/node6/helper.js' {
  declare module.exports: $Exports<'puppeteer/node6/helper'>;
}
declare module 'puppeteer/utils/ChromiumDownloader.js' {
  declare module.exports: $Exports<'puppeteer/utils/ChromiumDownloader'>;
}
declare module 'puppeteer/utils/ESTreeWalker.js' {
  declare module.exports: $Exports<'puppeteer/utils/ESTreeWalker'>;
}
declare module 'puppeteer/utils/check_availability.js' {
  declare module.exports: $Exports<'puppeteer/utils/check_availability'>;
}
declare module 'puppeteer/utils/doclint/Message.js' {
  declare module.exports: $Exports<'puppeteer/utils/doclint/Message'>;
}
declare module 'puppeteer/utils/doclint/SourceFactory.js' {
  declare module.exports: $Exports<'puppeteer/utils/doclint/SourceFactory'>;
}
declare module 'puppeteer/utils/doclint/check_public_api/Documentation.js' {
  declare module.exports: $Exports<
    'puppeteer/utils/doclint/check_public_api/Documentation'
  >;
}
declare module 'puppeteer/utils/doclint/check_public_api/JSBuilder.js' {
  declare module.exports: $Exports<
    'puppeteer/utils/doclint/check_public_api/JSBuilder'
  >;
}
declare module 'puppeteer/utils/doclint/check_public_api/MDBuilder.js' {
  declare module.exports: $Exports<
    'puppeteer/utils/doclint/check_public_api/MDBuilder'
  >;
}
declare module 'puppeteer/utils/doclint/check_public_api/index.js' {
  declare module.exports: $Exports<
    'puppeteer/utils/doclint/check_public_api/index'
  >;
}
declare module 'puppeteer/utils/doclint/cli.js' {
  declare module.exports: $Exports<'puppeteer/utils/doclint/cli'>;
}
declare module 'puppeteer/utils/doclint/preprocessor/index.js' {
  declare module.exports: $Exports<
    'puppeteer/utils/doclint/preprocessor/index'
  >;
}
declare module 'puppeteer/utils/doclint/preprocessor/test.js' {
  declare module.exports: $Exports<'puppeteer/utils/doclint/preprocessor/test'>;
}
declare module 'puppeteer/utils/doclint/toc.js' {
  declare module.exports: $Exports<'puppeteer/utils/doclint/toc'>;
}
declare module 'puppeteer/utils/fetch_devices.js' {
  declare module.exports: $Exports<'puppeteer/utils/fetch_devices'>;
}
