// flow-typed signature: e97180c9b29c79d356fcb1b8d55b92d9
// flow-typed version: <<STUB>>/querystring_v^0.2.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'querystring'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'querystring' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'querystring/decode' {
  declare module.exports: any;
}

declare module 'querystring/encode' {
  declare module.exports: any;
}

declare module 'querystring/test/common-index' {
  declare module.exports: any;
}

declare module 'querystring/test/index' {
  declare module.exports: any;
}

declare module 'querystring/test/tap-index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'querystring/decode.js' {
  declare module.exports: $Exports<'querystring/decode'>;
}
declare module 'querystring/encode.js' {
  declare module.exports: $Exports<'querystring/encode'>;
}
declare module 'querystring/index' {
  declare module.exports: $Exports<'querystring'>;
}
declare module 'querystring/index.js' {
  declare module.exports: $Exports<'querystring'>;
}
declare module 'querystring/test/common-index.js' {
  declare module.exports: $Exports<'querystring/test/common-index'>;
}
declare module 'querystring/test/index.js' {
  declare module.exports: $Exports<'querystring/test/index'>;
}
declare module 'querystring/test/tap-index.js' {
  declare module.exports: $Exports<'querystring/test/tap-index'>;
}
