// flow-typed signature: a95057c2e1171d8c0a4be2ef8189fc69
// flow-typed version: <<STUB>>/rc-slider_v^8.2.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rc-slider'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rc-slider' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rc-slider/dist/rc-slider' {
  declare module.exports: any;
}

declare module 'rc-slider/dist/rc-slider.min' {
  declare module.exports: any;
}

declare module 'rc-slider/es/common/createSlider' {
  declare module.exports: any;
}

declare module 'rc-slider/es/common/Marks' {
  declare module.exports: any;
}

declare module 'rc-slider/es/common/Steps' {
  declare module.exports: any;
}

declare module 'rc-slider/es/common/Track' {
  declare module.exports: any;
}

declare module 'rc-slider/es/createSliderWithTooltip' {
  declare module.exports: any;
}

declare module 'rc-slider/es/Handle' {
  declare module.exports: any;
}

declare module 'rc-slider/es/index' {
  declare module.exports: any;
}

declare module 'rc-slider/es/Range' {
  declare module.exports: any;
}

declare module 'rc-slider/es/Slider' {
  declare module.exports: any;
}

declare module 'rc-slider/es/utils' {
  declare module.exports: any;
}

declare module 'rc-slider/lib/common/createSlider' {
  declare module.exports: any;
}

declare module 'rc-slider/lib/common/Marks' {
  declare module.exports: any;
}

declare module 'rc-slider/lib/common/Steps' {
  declare module.exports: any;
}

declare module 'rc-slider/lib/common/Track' {
  declare module.exports: any;
}

declare module 'rc-slider/lib/createSliderWithTooltip' {
  declare module.exports: any;
}

declare module 'rc-slider/lib/Handle' {
  declare module.exports: any;
}

declare module 'rc-slider/lib/index' {
  declare module.exports: any;
}

declare module 'rc-slider/lib/Range' {
  declare module.exports: any;
}

declare module 'rc-slider/lib/Slider' {
  declare module.exports: any;
}

declare module 'rc-slider/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rc-slider/dist/rc-slider.js' {
  declare module.exports: $Exports<'rc-slider/dist/rc-slider'>;
}
declare module 'rc-slider/dist/rc-slider.min.js' {
  declare module.exports: $Exports<'rc-slider/dist/rc-slider.min'>;
}
declare module 'rc-slider/es/common/createSlider.js' {
  declare module.exports: $Exports<'rc-slider/es/common/createSlider'>;
}
declare module 'rc-slider/es/common/Marks.js' {
  declare module.exports: $Exports<'rc-slider/es/common/Marks'>;
}
declare module 'rc-slider/es/common/Steps.js' {
  declare module.exports: $Exports<'rc-slider/es/common/Steps'>;
}
declare module 'rc-slider/es/common/Track.js' {
  declare module.exports: $Exports<'rc-slider/es/common/Track'>;
}
declare module 'rc-slider/es/createSliderWithTooltip.js' {
  declare module.exports: $Exports<'rc-slider/es/createSliderWithTooltip'>;
}
declare module 'rc-slider/es/Handle.js' {
  declare module.exports: $Exports<'rc-slider/es/Handle'>;
}
declare module 'rc-slider/es/index.js' {
  declare module.exports: $Exports<'rc-slider/es/index'>;
}
declare module 'rc-slider/es/Range.js' {
  declare module.exports: $Exports<'rc-slider/es/Range'>;
}
declare module 'rc-slider/es/Slider.js' {
  declare module.exports: $Exports<'rc-slider/es/Slider'>;
}
declare module 'rc-slider/es/utils.js' {
  declare module.exports: $Exports<'rc-slider/es/utils'>;
}
declare module 'rc-slider/lib/common/createSlider.js' {
  declare module.exports: $Exports<'rc-slider/lib/common/createSlider'>;
}
declare module 'rc-slider/lib/common/Marks.js' {
  declare module.exports: $Exports<'rc-slider/lib/common/Marks'>;
}
declare module 'rc-slider/lib/common/Steps.js' {
  declare module.exports: $Exports<'rc-slider/lib/common/Steps'>;
}
declare module 'rc-slider/lib/common/Track.js' {
  declare module.exports: $Exports<'rc-slider/lib/common/Track'>;
}
declare module 'rc-slider/lib/createSliderWithTooltip.js' {
  declare module.exports: $Exports<'rc-slider/lib/createSliderWithTooltip'>;
}
declare module 'rc-slider/lib/Handle.js' {
  declare module.exports: $Exports<'rc-slider/lib/Handle'>;
}
declare module 'rc-slider/lib/index.js' {
  declare module.exports: $Exports<'rc-slider/lib/index'>;
}
declare module 'rc-slider/lib/Range.js' {
  declare module.exports: $Exports<'rc-slider/lib/Range'>;
}
declare module 'rc-slider/lib/Slider.js' {
  declare module.exports: $Exports<'rc-slider/lib/Slider'>;
}
declare module 'rc-slider/lib/utils.js' {
  declare module.exports: $Exports<'rc-slider/lib/utils'>;
}
