// flow-typed signature: daa053c27e7b6667ae31e33afc411cf3
// flow-typed version: <<STUB>>/react-draggable_v^3.0.4/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-draggable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-draggable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-draggable/dist/react-draggable' {
  declare module.exports: any;
}

declare module 'react-draggable/dist/react-draggable.min' {
  declare module.exports: any;
}

declare module 'react-draggable/lib/Draggable' {
  declare module.exports: any;
}

declare module 'react-draggable/lib/DraggableCore' {
  declare module.exports: any;
}

declare module 'react-draggable/lib/utils/domFns' {
  declare module.exports: any;
}

declare module 'react-draggable/lib/utils/getPrefix' {
  declare module.exports: any;
}

declare module 'react-draggable/lib/utils/log' {
  declare module.exports: any;
}

declare module 'react-draggable/lib/utils/positionFns' {
  declare module.exports: any;
}

declare module 'react-draggable/lib/utils/shims' {
  declare module.exports: any;
}

declare module 'react-draggable/lib/utils/types' {
  declare module.exports: any;
}

declare module 'react-draggable/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-draggable/dist/react-draggable.js' {
  declare module.exports: $Exports<'react-draggable/dist/react-draggable'>;
}
declare module 'react-draggable/dist/react-draggable.min.js' {
  declare module.exports: $Exports<'react-draggable/dist/react-draggable.min'>;
}
declare module 'react-draggable/index' {
  declare module.exports: $Exports<'react-draggable'>;
}
declare module 'react-draggable/index.js' {
  declare module.exports: $Exports<'react-draggable'>;
}
declare module 'react-draggable/lib/Draggable.js' {
  declare module.exports: $Exports<'react-draggable/lib/Draggable'>;
}
declare module 'react-draggable/lib/DraggableCore.js' {
  declare module.exports: $Exports<'react-draggable/lib/DraggableCore'>;
}
declare module 'react-draggable/lib/utils/domFns.js' {
  declare module.exports: $Exports<'react-draggable/lib/utils/domFns'>;
}
declare module 'react-draggable/lib/utils/getPrefix.js' {
  declare module.exports: $Exports<'react-draggable/lib/utils/getPrefix'>;
}
declare module 'react-draggable/lib/utils/log.js' {
  declare module.exports: $Exports<'react-draggable/lib/utils/log'>;
}
declare module 'react-draggable/lib/utils/positionFns.js' {
  declare module.exports: $Exports<'react-draggable/lib/utils/positionFns'>;
}
declare module 'react-draggable/lib/utils/shims.js' {
  declare module.exports: $Exports<'react-draggable/lib/utils/shims'>;
}
declare module 'react-draggable/lib/utils/types.js' {
  declare module.exports: $Exports<'react-draggable/lib/utils/types'>;
}
declare module 'react-draggable/webpack.config.js' {
  declare module.exports: $Exports<'react-draggable/webpack.config'>;
}
