// flow-typed signature: 92be93578732e38d00bd8ab54debd068
// flow-typed version: <<STUB>>/react-frame-component_v^1.0.2/flow_v0.43.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-frame-component'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-frame-component' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-frame-component/lib/DocumentContext' {
  declare module.exports: any;
}

declare module 'react-frame-component/lib/Frame' {
  declare module.exports: any;
}

declare module 'react-frame-component/lib/index' {
  declare module.exports: any;
}

declare module 'react-frame-component/src/DocumentContext' {
  declare module.exports: any;
}

declare module 'react-frame-component/src/Frame' {
  declare module.exports: any;
}

declare module 'react-frame-component/src/index' {
  declare module.exports: any;
}

declare module 'react-frame-component/test/DocumentContext.spec' {
  declare module.exports: any;
}

declare module 'react-frame-component/test/Frame.spec' {
  declare module.exports: any;
}

declare module 'react-frame-component/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-frame-component/lib/DocumentContext.js' {
  declare module.exports: $Exports<'react-frame-component/lib/DocumentContext'>;
}
declare module 'react-frame-component/lib/Frame.js' {
  declare module.exports: $Exports<'react-frame-component/lib/Frame'>;
}
declare module 'react-frame-component/lib/index.js' {
  declare module.exports: $Exports<'react-frame-component/lib/index'>;
}
declare module 'react-frame-component/src/DocumentContext.jsx' {
  declare module.exports: $Exports<'react-frame-component/src/DocumentContext'>;
}
declare module 'react-frame-component/src/Frame.jsx' {
  declare module.exports: $Exports<'react-frame-component/src/Frame'>;
}
declare module 'react-frame-component/src/index.js' {
  declare module.exports: $Exports<'react-frame-component/src/index'>;
}
declare module 'react-frame-component/test/DocumentContext.spec.jsx' {
  declare module.exports: $Exports<'react-frame-component/test/DocumentContext.spec'>;
}
declare module 'react-frame-component/test/Frame.spec.jsx' {
  declare module.exports: $Exports<'react-frame-component/test/Frame.spec'>;
}
declare module 'react-frame-component/webpack.config.js' {
  declare module.exports: $Exports<'react-frame-component/webpack.config'>;
}
