// flow-typed signature: 02ebf9378847a1666414bad9feb8c108
// flow-typed version: <<STUB>>/react-show_v^2.0.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-show'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-show' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-show/es/index' {
  declare module.exports: any;
}

declare module 'react-show/lib/index' {
  declare module.exports: any;
}

declare module 'react-show/umd/react-show' {
  declare module.exports: any;
}

declare module 'react-show/umd/react-show.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-show/es/index.js' {
  declare module.exports: $Exports<'react-show/es/index'>;
}
declare module 'react-show/lib/index.js' {
  declare module.exports: $Exports<'react-show/lib/index'>;
}
declare module 'react-show/umd/react-show.js' {
  declare module.exports: $Exports<'react-show/umd/react-show'>;
}
declare module 'react-show/umd/react-show.min.js' {
  declare module.exports: $Exports<'react-show/umd/react-show.min'>;
}
