// flow-typed signature: 5025feaadb07caacc125e37efeb3609d
// flow-typed version: <<STUB>>/react-error-overlay_v^1.0.10/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-error-overlay'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-error-overlay' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-error-overlay/lib/__tests__/extract-source-map' {
  declare module.exports: any;
}

declare module 'react-error-overlay/lib/__tests__/get-source-map' {
  declare module.exports: any;
}

declare module 'react-error-overlay/lib/__tests__/lines-around' {
  declare module.exports: any;
}

declare module 'react-error-overlay/lib/__tests__/mapper' {
  declare module.exports: any;
}

declare module 'react-error-overlay/lib/__tests__/parser/chrome' {
  declare module.exports: any;
}

declare module 'react-error-overlay/lib/__tests__/parser/firefox' {
  declare module.exports: any;
}

declare module 'react-error-overlay/lib/__tests__/parser/generic' {
  declare module.exports: any;
}

declare module 'react-error-overlay/lib/__tests__/parser/react' {
  declare module.exports: any;
}

declare module 'react-error-overlay/lib/__tests__/parser/safari' {
  declare module.exports: any;
}

declare module 'react-error-overlay/lib/__tests__/script-lines' {
  declare module.exports: any;
}

declare module 'react-error-overlay/lib/__tests__/setupJest' {
  declare module.exports: any;
}

declare module 'react-error-overlay/lib/__tests__/stack-frame' {
  declare module.exports: any;
}

declare module 'react-error-overlay/lib/__tests__/unmapper' {
  declare module.exports: any;
}

declare module 'react-error-overlay/lib/components/additional' {
  declare module.exports: any;
}

declare module 'react-error-overlay/lib/components/close' {
  declare module.exports: any;
}

declare module 'react-error-overlay/lib/components/code' {
  declare module.exports: any;
}

declare module 'react-error-overlay/lib/components/footer' {
  declare module.exports: any;
}

declare module 'react-error-overlay/lib/components/frame' {
  declare module.exports: any;
}

declare module 'react-error-overlay/lib/components/frames' {
  declare module.exports: any;
}

declare module 'react-error-overlay/lib/components/overlay' {
  declare module.exports: any;
}

declare module 'react-error-overlay/lib/effects/proxyConsole' {
  declare module.exports: any;
}

declare module 'react-error-overlay/lib/effects/shortcuts' {
  declare module.exports: any;
}

declare module 'react-error-overlay/lib/effects/stackTraceLimit' {
  declare module.exports: any;
}

declare module 'react-error-overlay/lib/effects/unhandledError' {
  declare module.exports: any;
}

declare module 'react-error-overlay/lib/effects/unhandledRejection' {
  declare module.exports: any;
}

declare module 'react-error-overlay/lib/index' {
  declare module.exports: any;
}

declare module 'react-error-overlay/lib/overlay' {
  declare module.exports: any;
}

declare module 'react-error-overlay/lib/styles' {
  declare module.exports: any;
}

declare module 'react-error-overlay/lib/utils/dom/absolutifyCaret' {
  declare module.exports: any;
}

declare module 'react-error-overlay/lib/utils/dom/consumeEvent' {
  declare module.exports: any;
}

declare module 'react-error-overlay/lib/utils/dom/css' {
  declare module.exports: any;
}

declare module 'react-error-overlay/lib/utils/dom/enableTabClick' {
  declare module.exports: any;
}

declare module 'react-error-overlay/lib/utils/errorRegister' {
  declare module.exports: any;
}

declare module 'react-error-overlay/lib/utils/getLinesAround' {
  declare module.exports: any;
}

declare module 'react-error-overlay/lib/utils/getSourceMap' {
  declare module.exports: any;
}

declare module 'react-error-overlay/lib/utils/isInternalFile' {
  declare module.exports: any;
}

declare module 'react-error-overlay/lib/utils/mapper' {
  declare module.exports: any;
}

declare module 'react-error-overlay/lib/utils/parser' {
  declare module.exports: any;
}

declare module 'react-error-overlay/lib/utils/stack-frame' {
  declare module.exports: any;
}

declare module 'react-error-overlay/lib/utils/unmapper' {
  declare module.exports: any;
}

declare module 'react-error-overlay/lib/utils/warnings' {
  declare module.exports: any;
}

declare module 'react-error-overlay/middleware' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-error-overlay/lib/__tests__/extract-source-map.js' {
  declare module.exports: $Exports<
    'react-error-overlay/lib/__tests__/extract-source-map'
  >;
}
declare module 'react-error-overlay/lib/__tests__/get-source-map.js' {
  declare module.exports: $Exports<
    'react-error-overlay/lib/__tests__/get-source-map'
  >;
}
declare module 'react-error-overlay/lib/__tests__/lines-around.js' {
  declare module.exports: $Exports<
    'react-error-overlay/lib/__tests__/lines-around'
  >;
}
declare module 'react-error-overlay/lib/__tests__/mapper.js' {
  declare module.exports: $Exports<'react-error-overlay/lib/__tests__/mapper'>;
}
declare module 'react-error-overlay/lib/__tests__/parser/chrome.js' {
  declare module.exports: $Exports<
    'react-error-overlay/lib/__tests__/parser/chrome'
  >;
}
declare module 'react-error-overlay/lib/__tests__/parser/firefox.js' {
  declare module.exports: $Exports<
    'react-error-overlay/lib/__tests__/parser/firefox'
  >;
}
declare module 'react-error-overlay/lib/__tests__/parser/generic.js' {
  declare module.exports: $Exports<
    'react-error-overlay/lib/__tests__/parser/generic'
  >;
}
declare module 'react-error-overlay/lib/__tests__/parser/react.js' {
  declare module.exports: $Exports<
    'react-error-overlay/lib/__tests__/parser/react'
  >;
}
declare module 'react-error-overlay/lib/__tests__/parser/safari.js' {
  declare module.exports: $Exports<
    'react-error-overlay/lib/__tests__/parser/safari'
  >;
}
declare module 'react-error-overlay/lib/__tests__/script-lines.js' {
  declare module.exports: $Exports<
    'react-error-overlay/lib/__tests__/script-lines'
  >;
}
declare module 'react-error-overlay/lib/__tests__/setupJest.js' {
  declare module.exports: $Exports<
    'react-error-overlay/lib/__tests__/setupJest'
  >;
}
declare module 'react-error-overlay/lib/__tests__/stack-frame.js' {
  declare module.exports: $Exports<
    'react-error-overlay/lib/__tests__/stack-frame'
  >;
}
declare module 'react-error-overlay/lib/__tests__/unmapper.js' {
  declare module.exports: $Exports<
    'react-error-overlay/lib/__tests__/unmapper'
  >;
}
declare module 'react-error-overlay/lib/components/additional.js' {
  declare module.exports: $Exports<
    'react-error-overlay/lib/components/additional'
  >;
}
declare module 'react-error-overlay/lib/components/close.js' {
  declare module.exports: $Exports<'react-error-overlay/lib/components/close'>;
}
declare module 'react-error-overlay/lib/components/code.js' {
  declare module.exports: $Exports<'react-error-overlay/lib/components/code'>;
}
declare module 'react-error-overlay/lib/components/footer.js' {
  declare module.exports: $Exports<'react-error-overlay/lib/components/footer'>;
}
declare module 'react-error-overlay/lib/components/frame.js' {
  declare module.exports: $Exports<'react-error-overlay/lib/components/frame'>;
}
declare module 'react-error-overlay/lib/components/frames.js' {
  declare module.exports: $Exports<'react-error-overlay/lib/components/frames'>;
}
declare module 'react-error-overlay/lib/components/overlay.js' {
  declare module.exports: $Exports<
    'react-error-overlay/lib/components/overlay'
  >;
}
declare module 'react-error-overlay/lib/effects/proxyConsole.js' {
  declare module.exports: $Exports<
    'react-error-overlay/lib/effects/proxyConsole'
  >;
}
declare module 'react-error-overlay/lib/effects/shortcuts.js' {
  declare module.exports: $Exports<'react-error-overlay/lib/effects/shortcuts'>;
}
declare module 'react-error-overlay/lib/effects/stackTraceLimit.js' {
  declare module.exports: $Exports<
    'react-error-overlay/lib/effects/stackTraceLimit'
  >;
}
declare module 'react-error-overlay/lib/effects/unhandledError.js' {
  declare module.exports: $Exports<
    'react-error-overlay/lib/effects/unhandledError'
  >;
}
declare module 'react-error-overlay/lib/effects/unhandledRejection.js' {
  declare module.exports: $Exports<
    'react-error-overlay/lib/effects/unhandledRejection'
  >;
}
declare module 'react-error-overlay/lib/index.js' {
  declare module.exports: $Exports<'react-error-overlay/lib/index'>;
}
declare module 'react-error-overlay/lib/overlay.js' {
  declare module.exports: $Exports<'react-error-overlay/lib/overlay'>;
}
declare module 'react-error-overlay/lib/styles.js' {
  declare module.exports: $Exports<'react-error-overlay/lib/styles'>;
}
declare module 'react-error-overlay/lib/utils/dom/absolutifyCaret.js' {
  declare module.exports: $Exports<
    'react-error-overlay/lib/utils/dom/absolutifyCaret'
  >;
}
declare module 'react-error-overlay/lib/utils/dom/consumeEvent.js' {
  declare module.exports: $Exports<
    'react-error-overlay/lib/utils/dom/consumeEvent'
  >;
}
declare module 'react-error-overlay/lib/utils/dom/css.js' {
  declare module.exports: $Exports<'react-error-overlay/lib/utils/dom/css'>;
}
declare module 'react-error-overlay/lib/utils/dom/enableTabClick.js' {
  declare module.exports: $Exports<
    'react-error-overlay/lib/utils/dom/enableTabClick'
  >;
}
declare module 'react-error-overlay/lib/utils/errorRegister.js' {
  declare module.exports: $Exports<
    'react-error-overlay/lib/utils/errorRegister'
  >;
}
declare module 'react-error-overlay/lib/utils/getLinesAround.js' {
  declare module.exports: $Exports<
    'react-error-overlay/lib/utils/getLinesAround'
  >;
}
declare module 'react-error-overlay/lib/utils/getSourceMap.js' {
  declare module.exports: $Exports<
    'react-error-overlay/lib/utils/getSourceMap'
  >;
}
declare module 'react-error-overlay/lib/utils/isInternalFile.js' {
  declare module.exports: $Exports<
    'react-error-overlay/lib/utils/isInternalFile'
  >;
}
declare module 'react-error-overlay/lib/utils/mapper.js' {
  declare module.exports: $Exports<'react-error-overlay/lib/utils/mapper'>;
}
declare module 'react-error-overlay/lib/utils/parser.js' {
  declare module.exports: $Exports<'react-error-overlay/lib/utils/parser'>;
}
declare module 'react-error-overlay/lib/utils/stack-frame.js' {
  declare module.exports: $Exports<'react-error-overlay/lib/utils/stack-frame'>;
}
declare module 'react-error-overlay/lib/utils/unmapper.js' {
  declare module.exports: $Exports<'react-error-overlay/lib/utils/unmapper'>;
}
declare module 'react-error-overlay/lib/utils/warnings.js' {
  declare module.exports: $Exports<'react-error-overlay/lib/utils/warnings'>;
}
declare module 'react-error-overlay/middleware.js' {
  declare module.exports: $Exports<'react-error-overlay/middleware'>;
}
