// flow-typed signature: 41869d706c81cae3f521611d34948482
// flow-typed version: <<STUB>>/react-modal_v^2.2.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-modal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-modal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-modal/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'react-modal/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'react-modal/dist/react-modal' {
  declare module.exports: any;
}

declare module 'react-modal/dist/react-modal.min' {
  declare module.exports: any;
}

declare module 'react-modal/lib/components/Modal' {
  declare module.exports: any;
}

declare module 'react-modal/lib/components/ModalPortal' {
  declare module.exports: any;
}

declare module 'react-modal/lib/helpers/ariaAppHider' {
  declare module.exports: any;
}

declare module 'react-modal/lib/helpers/bodyClassList' {
  declare module.exports: any;
}

declare module 'react-modal/lib/helpers/focusManager' {
  declare module.exports: any;
}

declare module 'react-modal/lib/helpers/refCount' {
  declare module.exports: any;
}

declare module 'react-modal/lib/helpers/safeHTMLElement' {
  declare module.exports: any;
}

declare module 'react-modal/lib/helpers/scopeTab' {
  declare module.exports: any;
}

declare module 'react-modal/lib/helpers/tabbable' {
  declare module.exports: any;
}

declare module 'react-modal/lib/index' {
  declare module.exports: any;
}

declare module 'react-modal/webpack.config' {
  declare module.exports: any;
}

declare module 'react-modal/webpack.dist.config' {
  declare module.exports: any;
}

declare module 'react-modal/webpack.test.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-modal/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'react-modal/coverage/lcov-report/prettify'>;
}
declare module 'react-modal/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'react-modal/coverage/lcov-report/sorter'>;
}
declare module 'react-modal/dist/react-modal.js' {
  declare module.exports: $Exports<'react-modal/dist/react-modal'>;
}
declare module 'react-modal/dist/react-modal.min.js' {
  declare module.exports: $Exports<'react-modal/dist/react-modal.min'>;
}
declare module 'react-modal/lib/components/Modal.js' {
  declare module.exports: $Exports<'react-modal/lib/components/Modal'>;
}
declare module 'react-modal/lib/components/ModalPortal.js' {
  declare module.exports: $Exports<'react-modal/lib/components/ModalPortal'>;
}
declare module 'react-modal/lib/helpers/ariaAppHider.js' {
  declare module.exports: $Exports<'react-modal/lib/helpers/ariaAppHider'>;
}
declare module 'react-modal/lib/helpers/bodyClassList.js' {
  declare module.exports: $Exports<'react-modal/lib/helpers/bodyClassList'>;
}
declare module 'react-modal/lib/helpers/focusManager.js' {
  declare module.exports: $Exports<'react-modal/lib/helpers/focusManager'>;
}
declare module 'react-modal/lib/helpers/refCount.js' {
  declare module.exports: $Exports<'react-modal/lib/helpers/refCount'>;
}
declare module 'react-modal/lib/helpers/safeHTMLElement.js' {
  declare module.exports: $Exports<'react-modal/lib/helpers/safeHTMLElement'>;
}
declare module 'react-modal/lib/helpers/scopeTab.js' {
  declare module.exports: $Exports<'react-modal/lib/helpers/scopeTab'>;
}
declare module 'react-modal/lib/helpers/tabbable.js' {
  declare module.exports: $Exports<'react-modal/lib/helpers/tabbable'>;
}
declare module 'react-modal/lib/index.js' {
  declare module.exports: $Exports<'react-modal/lib/index'>;
}
declare module 'react-modal/webpack.config.js' {
  declare module.exports: $Exports<'react-modal/webpack.config'>;
}
declare module 'react-modal/webpack.dist.config.js' {
  declare module.exports: $Exports<'react-modal/webpack.dist.config'>;
}
declare module 'react-modal/webpack.test.config.js' {
  declare module.exports: $Exports<'react-modal/webpack.test.config'>;
}
