// flow-typed signature: c18a3caa0ad42abb3be6093fac63a337
// flow-typed version: <<STUB>>/react-tagsinput_v^3.19.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-tagsinput'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-tagsinput' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-tagsinput/postcss.config' {
  declare module.exports: any;
}

declare module 'react-tagsinput/react-tagsinput' {
  declare module.exports: any;
}

declare module 'react-tagsinput/src/index' {
  declare module.exports: any;
}

declare module 'react-tagsinput/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-tagsinput/postcss.config.js' {
  declare module.exports: $Exports<'react-tagsinput/postcss.config'>;
}
declare module 'react-tagsinput/react-tagsinput.js' {
  declare module.exports: $Exports<'react-tagsinput/react-tagsinput'>;
}
declare module 'react-tagsinput/src/index.js' {
  declare module.exports: $Exports<'react-tagsinput/src/index'>;
}
declare module 'react-tagsinput/test/index.js' {
  declare module.exports: $Exports<'react-tagsinput/test/index'>;
}
