// flow-typed signature: 78deda3feb120f0108c51211f3bb6fb5
// flow-typed version: <<STUB>>/react-inspector_v^2.2.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-inspector'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-inspector' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-inspector/lib/dom-inspector/DOMInspector' {
  declare module.exports: any;
}

declare module 'react-inspector/lib/dom-inspector/DOMNodePreview' {
  declare module.exports: any;
}

declare module 'react-inspector/lib/dom-inspector/shouldInline' {
  declare module.exports: any;
}

declare module 'react-inspector/lib/index' {
  declare module.exports: any;
}

declare module 'react-inspector/lib/object-inspector/ObjectInspector' {
  declare module.exports: any;
}

declare module 'react-inspector/lib/object-inspector/ObjectInspector.spec' {
  declare module.exports: any;
}

declare module 'react-inspector/lib/object-inspector/ObjectLabel' {
  declare module.exports: any;
}

declare module 'react-inspector/lib/object-inspector/ObjectPreview' {
  declare module.exports: any;
}

declare module 'react-inspector/lib/object-inspector/ObjectRootLabel' {
  declare module.exports: any;
}

declare module 'react-inspector/lib/object/ObjectName' {
  declare module.exports: any;
}

declare module 'react-inspector/lib/object/ObjectName.spec' {
  declare module.exports: any;
}

declare module 'react-inspector/lib/object/ObjectValue' {
  declare module.exports: any;
}

declare module 'react-inspector/lib/object/ObjectValue.spec' {
  declare module.exports: any;
}

declare module 'react-inspector/lib/styles/base' {
  declare module.exports: any;
}

declare module 'react-inspector/lib/styles/createStyles' {
  declare module.exports: any;
}

declare module 'react-inspector/lib/styles/ThemeProvider' {
  declare module.exports: any;
}

declare module 'react-inspector/lib/styles/themes/chromeDark' {
  declare module.exports: any;
}

declare module 'react-inspector/lib/styles/themes/chromeLight' {
  declare module.exports: any;
}

declare module 'react-inspector/lib/styles/themes/index' {
  declare module.exports: any;
}

declare module 'react-inspector/lib/styles/unselectable' {
  declare module.exports: any;
}

declare module 'react-inspector/lib/table-inspector/DataContainer' {
  declare module.exports: any;
}

declare module 'react-inspector/lib/table-inspector/getHeaders' {
  declare module.exports: any;
}

declare module 'react-inspector/lib/table-inspector/getHeaders.spec' {
  declare module.exports: any;
}

declare module 'react-inspector/lib/table-inspector/HeaderContainer' {
  declare module.exports: any;
}

declare module 'react-inspector/lib/table-inspector/TableInspector' {
  declare module.exports: any;
}

declare module 'react-inspector/lib/table-inspector/TH' {
  declare module.exports: any;
}

declare module 'react-inspector/lib/tree-view/pathUtils' {
  declare module.exports: any;
}

declare module 'react-inspector/lib/tree-view/pathUtils.spec' {
  declare module.exports: any;
}

declare module 'react-inspector/lib/tree-view/TreeNode' {
  declare module.exports: any;
}

declare module 'react-inspector/lib/tree-view/TreeView' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-inspector/lib/dom-inspector/DOMInspector.js' {
  declare module.exports: $Exports<
    'react-inspector/lib/dom-inspector/DOMInspector'
  >;
}
declare module 'react-inspector/lib/dom-inspector/DOMNodePreview.js' {
  declare module.exports: $Exports<
    'react-inspector/lib/dom-inspector/DOMNodePreview'
  >;
}
declare module 'react-inspector/lib/dom-inspector/shouldInline.js' {
  declare module.exports: $Exports<
    'react-inspector/lib/dom-inspector/shouldInline'
  >;
}
declare module 'react-inspector/lib/index.js' {
  declare module.exports: $Exports<'react-inspector/lib/index'>;
}
declare module 'react-inspector/lib/object-inspector/ObjectInspector.js' {
  declare module.exports: $Exports<
    'react-inspector/lib/object-inspector/ObjectInspector'
  >;
}
declare module 'react-inspector/lib/object-inspector/ObjectInspector.spec.js' {
  declare module.exports: $Exports<
    'react-inspector/lib/object-inspector/ObjectInspector.spec'
  >;
}
declare module 'react-inspector/lib/object-inspector/ObjectLabel.js' {
  declare module.exports: $Exports<
    'react-inspector/lib/object-inspector/ObjectLabel'
  >;
}
declare module 'react-inspector/lib/object-inspector/ObjectPreview.js' {
  declare module.exports: $Exports<
    'react-inspector/lib/object-inspector/ObjectPreview'
  >;
}
declare module 'react-inspector/lib/object-inspector/ObjectRootLabel.js' {
  declare module.exports: $Exports<
    'react-inspector/lib/object-inspector/ObjectRootLabel'
  >;
}
declare module 'react-inspector/lib/object/ObjectName.js' {
  declare module.exports: $Exports<'react-inspector/lib/object/ObjectName'>;
}
declare module 'react-inspector/lib/object/ObjectName.spec.js' {
  declare module.exports: $Exports<
    'react-inspector/lib/object/ObjectName.spec'
  >;
}
declare module 'react-inspector/lib/object/ObjectValue.js' {
  declare module.exports: $Exports<'react-inspector/lib/object/ObjectValue'>;
}
declare module 'react-inspector/lib/object/ObjectValue.spec.js' {
  declare module.exports: $Exports<
    'react-inspector/lib/object/ObjectValue.spec'
  >;
}
declare module 'react-inspector/lib/styles/base.js' {
  declare module.exports: $Exports<'react-inspector/lib/styles/base'>;
}
declare module 'react-inspector/lib/styles/createStyles.js' {
  declare module.exports: $Exports<'react-inspector/lib/styles/createStyles'>;
}
declare module 'react-inspector/lib/styles/ThemeProvider.js' {
  declare module.exports: $Exports<'react-inspector/lib/styles/ThemeProvider'>;
}
declare module 'react-inspector/lib/styles/themes/chromeDark.js' {
  declare module.exports: $Exports<
    'react-inspector/lib/styles/themes/chromeDark'
  >;
}
declare module 'react-inspector/lib/styles/themes/chromeLight.js' {
  declare module.exports: $Exports<
    'react-inspector/lib/styles/themes/chromeLight'
  >;
}
declare module 'react-inspector/lib/styles/themes/index.js' {
  declare module.exports: $Exports<'react-inspector/lib/styles/themes/index'>;
}
declare module 'react-inspector/lib/styles/unselectable.js' {
  declare module.exports: $Exports<'react-inspector/lib/styles/unselectable'>;
}
declare module 'react-inspector/lib/table-inspector/DataContainer.js' {
  declare module.exports: $Exports<
    'react-inspector/lib/table-inspector/DataContainer'
  >;
}
declare module 'react-inspector/lib/table-inspector/getHeaders.js' {
  declare module.exports: $Exports<
    'react-inspector/lib/table-inspector/getHeaders'
  >;
}
declare module 'react-inspector/lib/table-inspector/getHeaders.spec.js' {
  declare module.exports: $Exports<
    'react-inspector/lib/table-inspector/getHeaders.spec'
  >;
}
declare module 'react-inspector/lib/table-inspector/HeaderContainer.js' {
  declare module.exports: $Exports<
    'react-inspector/lib/table-inspector/HeaderContainer'
  >;
}
declare module 'react-inspector/lib/table-inspector/TableInspector.js' {
  declare module.exports: $Exports<
    'react-inspector/lib/table-inspector/TableInspector'
  >;
}
declare module 'react-inspector/lib/table-inspector/TH.js' {
  declare module.exports: $Exports<'react-inspector/lib/table-inspector/TH'>;
}
declare module 'react-inspector/lib/tree-view/pathUtils.js' {
  declare module.exports: $Exports<'react-inspector/lib/tree-view/pathUtils'>;
}
declare module 'react-inspector/lib/tree-view/pathUtils.spec.js' {
  declare module.exports: $Exports<
    'react-inspector/lib/tree-view/pathUtils.spec'
  >;
}
declare module 'react-inspector/lib/tree-view/TreeNode.js' {
  declare module.exports: $Exports<'react-inspector/lib/tree-view/TreeNode'>;
}
declare module 'react-inspector/lib/tree-view/TreeView.js' {
  declare module.exports: $Exports<'react-inspector/lib/tree-view/TreeView'>;
}
