// flow-typed signature: 64039fd6f8e1db6f434458748b877486
// flow-typed version: <<STUB>>/react-i18next_v4.x.x/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-i18next'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-i18next' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-i18next/dist/amd/react-i18next' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/amd/react-i18next.min' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/commonjs/I18nextProvider' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/commonjs/index' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/commonjs/interpolate' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/commonjs/loadNamespaces' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/commonjs/trans' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/commonjs/translate' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/es/I18nextProvider' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/es/index' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/es/interpolate' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/es/loadNamespaces' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/es/trans' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/es/translate' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/umd/react-i18next' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/umd/react-i18next.min' {
  declare module.exports: any;
}

declare module 'react-i18next/react-i18next' {
  declare module.exports: any;
}

declare module 'react-i18next/react-i18next.min' {
  declare module.exports: any;
}

declare module 'react-i18next/rollup.config' {
  declare module.exports: any;
}

declare module 'react-i18next/src/I18nextProvider' {
  declare module.exports: any;
}

declare module 'react-i18next/src/index' {
  declare module.exports: any;
}

declare module 'react-i18next/src/interpolate' {
  declare module.exports: any;
}

declare module 'react-i18next/src/loadNamespaces' {
  declare module.exports: any;
}

declare module 'react-i18next/src/trans' {
  declare module.exports: any;
}

declare module 'react-i18next/src/translate' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-i18next/dist/amd/react-i18next.js' {
  declare module.exports: $Exports<'react-i18next/dist/amd/react-i18next'>;
}
declare module 'react-i18next/dist/amd/react-i18next.min.js' {
  declare module.exports: $Exports<'react-i18next/dist/amd/react-i18next.min'>;
}
declare module 'react-i18next/dist/commonjs/I18nextProvider.js' {
  declare module.exports: $Exports<
    'react-i18next/dist/commonjs/I18nextProvider',
  >;
}
declare module 'react-i18next/dist/commonjs/index.js' {
  declare module.exports: $Exports<'react-i18next/dist/commonjs/index'>;
}
declare module 'react-i18next/dist/commonjs/interpolate.js' {
  declare module.exports: $Exports<'react-i18next/dist/commonjs/interpolate'>;
}
declare module 'react-i18next/dist/commonjs/loadNamespaces.js' {
  declare module.exports: $Exports<
    'react-i18next/dist/commonjs/loadNamespaces',
  >;
}
declare module 'react-i18next/dist/commonjs/trans.js' {
  declare module.exports: $Exports<'react-i18next/dist/commonjs/trans'>;
}
declare module 'react-i18next/dist/commonjs/translate.js' {
  declare module.exports: $Exports<'react-i18next/dist/commonjs/translate'>;
}
declare module 'react-i18next/dist/es/I18nextProvider.js' {
  declare module.exports: $Exports<'react-i18next/dist/es/I18nextProvider'>;
}
declare module 'react-i18next/dist/es/index.js' {
  declare module.exports: $Exports<'react-i18next/dist/es/index'>;
}
declare module 'react-i18next/dist/es/interpolate.js' {
  declare module.exports: $Exports<'react-i18next/dist/es/interpolate'>;
}
declare module 'react-i18next/dist/es/loadNamespaces.js' {
  declare module.exports: $Exports<'react-i18next/dist/es/loadNamespaces'>;
}
declare module 'react-i18next/dist/es/trans.js' {
  declare module.exports: $Exports<'react-i18next/dist/es/trans'>;
}
declare module 'react-i18next/dist/es/translate.js' {
  declare module.exports: $Exports<'react-i18next/dist/es/translate'>;
}
declare module 'react-i18next/dist/umd/react-i18next.js' {
  declare module.exports: $Exports<'react-i18next/dist/umd/react-i18next'>;
}
declare module 'react-i18next/dist/umd/react-i18next.min.js' {
  declare module.exports: $Exports<'react-i18next/dist/umd/react-i18next.min'>;
}
declare module 'react-i18next/react-i18next.js' {
  declare module.exports: $Exports<'react-i18next/react-i18next'>;
}
declare module 'react-i18next/react-i18next.min.js' {
  declare module.exports: $Exports<'react-i18next/react-i18next.min'>;
}
declare module 'react-i18next/rollup.config.js' {
  declare module.exports: $Exports<'react-i18next/rollup.config'>;
}
declare module 'react-i18next/src/I18nextProvider.js' {
  declare module.exports: $Exports<'react-i18next/src/I18nextProvider'>;
}
declare module 'react-i18next/src/index.js' {
  declare module.exports: $Exports<'react-i18next/src/index'>;
}
declare module 'react-i18next/src/interpolate.js' {
  declare module.exports: $Exports<'react-i18next/src/interpolate'>;
}
declare module 'react-i18next/src/loadNamespaces.js' {
  declare module.exports: $Exports<'react-i18next/src/loadNamespaces'>;
}
declare module 'react-i18next/src/trans.js' {
  declare module.exports: $Exports<'react-i18next/src/trans'>;
}
declare module 'react-i18next/src/translate.js' {
  declare module.exports: $Exports<'react-i18next/src/translate'>;
}
