// flow-typed signature: 9fbdc83f58adce3d7325a25c1f38a287
// flow-typed version: <<STUB>>/react-media_v^1.6.1/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-media'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-media' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-media/Media' {
  declare module.exports: any;
}

declare module 'react-media/es/Media' {
  declare module.exports: any;
}

declare module 'react-media/es/index' {
  declare module.exports: any;
}

declare module 'react-media/umd/react-media' {
  declare module.exports: any;
}

declare module 'react-media/umd/react-media.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-media/Media.js' {
  declare module.exports: $Exports<'react-media/Media'>;
}
declare module 'react-media/es/Media.js' {
  declare module.exports: $Exports<'react-media/es/Media'>;
}
declare module 'react-media/es/index.js' {
  declare module.exports: $Exports<'react-media/es/index'>;
}
declare module 'react-media/index' {
  declare module.exports: $Exports<'react-media'>;
}
declare module 'react-media/index.js' {
  declare module.exports: $Exports<'react-media'>;
}
declare module 'react-media/umd/react-media.js' {
  declare module.exports: $Exports<'react-media/umd/react-media'>;
}
declare module 'react-media/umd/react-media.min.js' {
  declare module.exports: $Exports<'react-media/umd/react-media.min'>;
}
