// flow-typed signature: 192848d60bda473d4c71739bf77774f8
// flow-typed version: <<STUB>>/react-deep-force-update_v^2.0.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-deep-force-update'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-deep-force-update' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-deep-force-update/lib/index' {
  declare module.exports: any;
}

declare module 'react-deep-force-update/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-deep-force-update/lib/index.js' {
  declare module.exports: $Exports<'react-deep-force-update/lib/index'>;
}
declare module 'react-deep-force-update/src/index.js' {
  declare module.exports: $Exports<'react-deep-force-update/src/index'>;
}
