// flow-typed signature: 4ef45392cfb328e69aae8977c25d13f2
// flow-typed version: <<STUB>>/recursive-readdir_v^2.1.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'recursive-readdir'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'recursive-readdir' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'recursive-readdir/test/recursive-readdir-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'recursive-readdir/index' {
  declare module.exports: $Exports<'recursive-readdir'>;
}
declare module 'recursive-readdir/index.js' {
  declare module.exports: $Exports<'recursive-readdir'>;
}
declare module 'recursive-readdir/test/recursive-readdir-test.js' {
  declare module.exports: $Exports<'recursive-readdir/test/recursive-readdir-test'>;
}
