// flow-typed signature: 2be194a7bb41e76a56ca00ede8dbd835
// flow-typed version: <<STUB>>/recursive-readdir_v^2.1.0/flow_v0.43.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'recursive-readdir'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'recursive-readdir' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'recursive-readdir/test/recursive-readdir-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'recursive-readdir/index' {
  declare module.exports: $Exports<'recursive-readdir'>;
}
declare module 'recursive-readdir/index.js' {
  declare module.exports: $Exports<'recursive-readdir'>;
}
declare module 'recursive-readdir/test/recursive-readdir-test.js' {
  declare module.exports: $Exports<'recursive-readdir/test/recursive-readdir-test'>;
}
