// flow-typed signature: c44d809f9ffbe7b8789a3faf42f50fc4
// flow-typed version: <<STUB>>/redbox-react_v^1.3.3/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redbox-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redbox-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redbox-react/dist/redbox' {
  declare module.exports: any;
}

declare module 'redbox-react/dist/redbox.min' {
  declare module.exports: any;
}

declare module 'redbox-react/lib/index' {
  declare module.exports: any;
}

declare module 'redbox-react/lib/lib' {
  declare module.exports: any;
}

declare module 'redbox-react/lib/style' {
  declare module.exports: any;
}

declare module 'redbox-react/src/index' {
  declare module.exports: any;
}

declare module 'redbox-react/src/lib' {
  declare module.exports: any;
}

declare module 'redbox-react/src/style' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redbox-react/dist/redbox.js' {
  declare module.exports: $Exports<'redbox-react/dist/redbox'>;
}
declare module 'redbox-react/dist/redbox.min.js' {
  declare module.exports: $Exports<'redbox-react/dist/redbox.min'>;
}
declare module 'redbox-react/lib/index.js' {
  declare module.exports: $Exports<'redbox-react/lib/index'>;
}
declare module 'redbox-react/lib/lib.js' {
  declare module.exports: $Exports<'redbox-react/lib/lib'>;
}
declare module 'redbox-react/lib/style.js' {
  declare module.exports: $Exports<'redbox-react/lib/style'>;
}
declare module 'redbox-react/src/index.js' {
  declare module.exports: $Exports<'redbox-react/src/index'>;
}
declare module 'redbox-react/src/lib.js' {
  declare module.exports: $Exports<'redbox-react/src/lib'>;
}
declare module 'redbox-react/src/style.js' {
  declare module.exports: $Exports<'redbox-react/src/style'>;
}
