// flow-typed signature: 2a8e4b97c62216c5172f27dfbeecdc82
// flow-typed version: <<STUB>>/redux-saga_v^0.13.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-saga'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-saga' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-saga/dist/redux-saga' {
  declare module.exports: any;
}

declare module 'redux-saga/dist/redux-saga.min' {
  declare module.exports: any;
}

declare module 'redux-saga/effects' {
  declare module.exports: any;
}

declare module 'redux-saga/es/effects' {
  declare module.exports: any;
}

declare module 'redux-saga/es/index' {
  declare module.exports: any;
}

declare module 'redux-saga/es/internal/buffers' {
  declare module.exports: any;
}

declare module 'redux-saga/es/internal/channel' {
  declare module.exports: any;
}

declare module 'redux-saga/es/internal/io' {
  declare module.exports: any;
}

declare module 'redux-saga/es/internal/middleware' {
  declare module.exports: any;
}

declare module 'redux-saga/es/internal/proc' {
  declare module.exports: any;
}

declare module 'redux-saga/es/internal/runSaga' {
  declare module.exports: any;
}

declare module 'redux-saga/es/internal/sagaHelpers' {
  declare module.exports: any;
}

declare module 'redux-saga/es/internal/scheduler' {
  declare module.exports: any;
}

declare module 'redux-saga/es/internal/utils' {
  declare module.exports: any;
}

declare module 'redux-saga/es/utils' {
  declare module.exports: any;
}

declare module 'redux-saga/lib/effects' {
  declare module.exports: any;
}

declare module 'redux-saga/lib/index' {
  declare module.exports: any;
}

declare module 'redux-saga/lib/internal/buffers' {
  declare module.exports: any;
}

declare module 'redux-saga/lib/internal/channel' {
  declare module.exports: any;
}

declare module 'redux-saga/lib/internal/io' {
  declare module.exports: any;
}

declare module 'redux-saga/lib/internal/middleware' {
  declare module.exports: any;
}

declare module 'redux-saga/lib/internal/proc' {
  declare module.exports: any;
}

declare module 'redux-saga/lib/internal/runSaga' {
  declare module.exports: any;
}

declare module 'redux-saga/lib/internal/sagaHelpers' {
  declare module.exports: any;
}

declare module 'redux-saga/lib/internal/scheduler' {
  declare module.exports: any;
}

declare module 'redux-saga/lib/internal/utils' {
  declare module.exports: any;
}

declare module 'redux-saga/lib/utils' {
  declare module.exports: any;
}

declare module 'redux-saga/src/effects' {
  declare module.exports: any;
}

declare module 'redux-saga/src/index' {
  declare module.exports: any;
}

declare module 'redux-saga/src/internal/buffers' {
  declare module.exports: any;
}

declare module 'redux-saga/src/internal/channel' {
  declare module.exports: any;
}

declare module 'redux-saga/src/internal/io' {
  declare module.exports: any;
}

declare module 'redux-saga/src/internal/middleware' {
  declare module.exports: any;
}

declare module 'redux-saga/src/internal/proc' {
  declare module.exports: any;
}

declare module 'redux-saga/src/internal/runSaga' {
  declare module.exports: any;
}

declare module 'redux-saga/src/internal/sagaHelpers' {
  declare module.exports: any;
}

declare module 'redux-saga/src/internal/scheduler' {
  declare module.exports: any;
}

declare module 'redux-saga/src/internal/utils' {
  declare module.exports: any;
}

declare module 'redux-saga/src/utils' {
  declare module.exports: any;
}

declare module 'redux-saga/utils' {
  declare module.exports: any;
}

declare module 'redux-saga/webpack.config.base' {
  declare module.exports: any;
}

declare module 'redux-saga/webpack.config.dev' {
  declare module.exports: any;
}

declare module 'redux-saga/webpack.config.prod' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-saga/dist/redux-saga.js' {
  declare module.exports: $Exports<'redux-saga/dist/redux-saga'>;
}
declare module 'redux-saga/dist/redux-saga.min.js' {
  declare module.exports: $Exports<'redux-saga/dist/redux-saga.min'>;
}
declare module 'redux-saga/effects.js' {
  declare module.exports: $Exports<'redux-saga/effects'>;
}
declare module 'redux-saga/es/effects.js' {
  declare module.exports: $Exports<'redux-saga/es/effects'>;
}
declare module 'redux-saga/es/index.js' {
  declare module.exports: $Exports<'redux-saga/es/index'>;
}
declare module 'redux-saga/es/internal/buffers.js' {
  declare module.exports: $Exports<'redux-saga/es/internal/buffers'>;
}
declare module 'redux-saga/es/internal/channel.js' {
  declare module.exports: $Exports<'redux-saga/es/internal/channel'>;
}
declare module 'redux-saga/es/internal/io.js' {
  declare module.exports: $Exports<'redux-saga/es/internal/io'>;
}
declare module 'redux-saga/es/internal/middleware.js' {
  declare module.exports: $Exports<'redux-saga/es/internal/middleware'>;
}
declare module 'redux-saga/es/internal/proc.js' {
  declare module.exports: $Exports<'redux-saga/es/internal/proc'>;
}
declare module 'redux-saga/es/internal/runSaga.js' {
  declare module.exports: $Exports<'redux-saga/es/internal/runSaga'>;
}
declare module 'redux-saga/es/internal/sagaHelpers.js' {
  declare module.exports: $Exports<'redux-saga/es/internal/sagaHelpers'>;
}
declare module 'redux-saga/es/internal/scheduler.js' {
  declare module.exports: $Exports<'redux-saga/es/internal/scheduler'>;
}
declare module 'redux-saga/es/internal/utils.js' {
  declare module.exports: $Exports<'redux-saga/es/internal/utils'>;
}
declare module 'redux-saga/es/utils.js' {
  declare module.exports: $Exports<'redux-saga/es/utils'>;
}
declare module 'redux-saga/lib/effects.js' {
  declare module.exports: $Exports<'redux-saga/lib/effects'>;
}
declare module 'redux-saga/lib/index.js' {
  declare module.exports: $Exports<'redux-saga/lib/index'>;
}
declare module 'redux-saga/lib/internal/buffers.js' {
  declare module.exports: $Exports<'redux-saga/lib/internal/buffers'>;
}
declare module 'redux-saga/lib/internal/channel.js' {
  declare module.exports: $Exports<'redux-saga/lib/internal/channel'>;
}
declare module 'redux-saga/lib/internal/io.js' {
  declare module.exports: $Exports<'redux-saga/lib/internal/io'>;
}
declare module 'redux-saga/lib/internal/middleware.js' {
  declare module.exports: $Exports<'redux-saga/lib/internal/middleware'>;
}
declare module 'redux-saga/lib/internal/proc.js' {
  declare module.exports: $Exports<'redux-saga/lib/internal/proc'>;
}
declare module 'redux-saga/lib/internal/runSaga.js' {
  declare module.exports: $Exports<'redux-saga/lib/internal/runSaga'>;
}
declare module 'redux-saga/lib/internal/sagaHelpers.js' {
  declare module.exports: $Exports<'redux-saga/lib/internal/sagaHelpers'>;
}
declare module 'redux-saga/lib/internal/scheduler.js' {
  declare module.exports: $Exports<'redux-saga/lib/internal/scheduler'>;
}
declare module 'redux-saga/lib/internal/utils.js' {
  declare module.exports: $Exports<'redux-saga/lib/internal/utils'>;
}
declare module 'redux-saga/lib/utils.js' {
  declare module.exports: $Exports<'redux-saga/lib/utils'>;
}
declare module 'redux-saga/src/effects.js' {
  declare module.exports: $Exports<'redux-saga/src/effects'>;
}
declare module 'redux-saga/src/index.js' {
  declare module.exports: $Exports<'redux-saga/src/index'>;
}
declare module 'redux-saga/src/internal/buffers.js' {
  declare module.exports: $Exports<'redux-saga/src/internal/buffers'>;
}
declare module 'redux-saga/src/internal/channel.js' {
  declare module.exports: $Exports<'redux-saga/src/internal/channel'>;
}
declare module 'redux-saga/src/internal/io.js' {
  declare module.exports: $Exports<'redux-saga/src/internal/io'>;
}
declare module 'redux-saga/src/internal/middleware.js' {
  declare module.exports: $Exports<'redux-saga/src/internal/middleware'>;
}
declare module 'redux-saga/src/internal/proc.js' {
  declare module.exports: $Exports<'redux-saga/src/internal/proc'>;
}
declare module 'redux-saga/src/internal/runSaga.js' {
  declare module.exports: $Exports<'redux-saga/src/internal/runSaga'>;
}
declare module 'redux-saga/src/internal/sagaHelpers.js' {
  declare module.exports: $Exports<'redux-saga/src/internal/sagaHelpers'>;
}
declare module 'redux-saga/src/internal/scheduler.js' {
  declare module.exports: $Exports<'redux-saga/src/internal/scheduler'>;
}
declare module 'redux-saga/src/internal/utils.js' {
  declare module.exports: $Exports<'redux-saga/src/internal/utils'>;
}
declare module 'redux-saga/src/utils.js' {
  declare module.exports: $Exports<'redux-saga/src/utils'>;
}
declare module 'redux-saga/utils.js' {
  declare module.exports: $Exports<'redux-saga/utils'>;
}
declare module 'redux-saga/webpack.config.base.js' {
  declare module.exports: $Exports<'redux-saga/webpack.config.base'>;
}
declare module 'redux-saga/webpack.config.dev.js' {
  declare module.exports: $Exports<'redux-saga/webpack.config.dev'>;
}
declare module 'redux-saga/webpack.config.prod.js' {
  declare module.exports: $Exports<'redux-saga/webpack.config.prod'>;
}
