// flow-typed signature: 020f3cf1934af133d98ceadb7726c174
// flow-typed version: <<STUB>>/reselect_v^2.5.4/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reselect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'reselect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reselect/dist/reselect' {
  declare module.exports: any;
}

declare module 'reselect/es/index' {
  declare module.exports: any;
}

declare module 'reselect/lib/index' {
  declare module.exports: any;
}

declare module 'reselect/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reselect/dist/reselect.js' {
  declare module.exports: $Exports<'reselect/dist/reselect'>;
}
declare module 'reselect/es/index.js' {
  declare module.exports: $Exports<'reselect/es/index'>;
}
declare module 'reselect/lib/index.js' {
  declare module.exports: $Exports<'reselect/lib/index'>;
}
declare module 'reselect/src/index.js' {
  declare module.exports: $Exports<'reselect/src/index'>;
}
