// flow-typed signature: 851e0bc25bbc4a21bb7021a232688066
// flow-typed version: <<STUB>>/run-sequence_v^1.2.2/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'run-sequence'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'run-sequence' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'run-sequence/index' {
  declare module.exports: $Exports<'run-sequence'>;
}
declare module 'run-sequence/index.js' {
  declare module.exports: $Exports<'run-sequence'>;
}
