// flow-typed signature: ed178166b7c1f2bce504047045381269
// flow-typed version: <<STUB>>/script-ext-html-webpack-plugin_v^1.8.8/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'script-ext-html-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'script-ext-html-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'script-ext-html-webpack-plugin/lib/async-chunk-resource-hints' {
  declare module.exports: any;
}

declare module 'script-ext-html-webpack-plugin/lib/common' {
  declare module.exports: any;
}

declare module 'script-ext-html-webpack-plugin/lib/config' {
  declare module.exports: any;
}

declare module 'script-ext-html-webpack-plugin/lib/constants' {
  declare module.exports: any;
}

declare module 'script-ext-html-webpack-plugin/lib/custom-attributes' {
  declare module.exports: any;
}

declare module 'script-ext-html-webpack-plugin/lib/elements' {
  declare module.exports: any;
}

declare module 'script-ext-html-webpack-plugin/lib/initial-chunk-resource-hints' {
  declare module.exports: any;
}

declare module 'script-ext-html-webpack-plugin/lib/plugin' {
  declare module.exports: any;
}

declare module 'script-ext-html-webpack-plugin/lib/resource-hints' {
  declare module.exports: any;
}

// Filename aliases
declare module 'script-ext-html-webpack-plugin/index' {
  declare module.exports: $Exports<'script-ext-html-webpack-plugin'>;
}
declare module 'script-ext-html-webpack-plugin/index.js' {
  declare module.exports: $Exports<'script-ext-html-webpack-plugin'>;
}
declare module 'script-ext-html-webpack-plugin/lib/async-chunk-resource-hints.js' {
  declare module.exports: $Exports<
    'script-ext-html-webpack-plugin/lib/async-chunk-resource-hints'
  >;
}
declare module 'script-ext-html-webpack-plugin/lib/common.js' {
  declare module.exports: $Exports<'script-ext-html-webpack-plugin/lib/common'>;
}
declare module 'script-ext-html-webpack-plugin/lib/config.js' {
  declare module.exports: $Exports<'script-ext-html-webpack-plugin/lib/config'>;
}
declare module 'script-ext-html-webpack-plugin/lib/constants.js' {
  declare module.exports: $Exports<
    'script-ext-html-webpack-plugin/lib/constants'
  >;
}
declare module 'script-ext-html-webpack-plugin/lib/custom-attributes.js' {
  declare module.exports: $Exports<
    'script-ext-html-webpack-plugin/lib/custom-attributes'
  >;
}
declare module 'script-ext-html-webpack-plugin/lib/elements.js' {
  declare module.exports: $Exports<
    'script-ext-html-webpack-plugin/lib/elements'
  >;
}
declare module 'script-ext-html-webpack-plugin/lib/initial-chunk-resource-hints.js' {
  declare module.exports: $Exports<
    'script-ext-html-webpack-plugin/lib/initial-chunk-resource-hints'
  >;
}
declare module 'script-ext-html-webpack-plugin/lib/plugin.js' {
  declare module.exports: $Exports<'script-ext-html-webpack-plugin/lib/plugin'>;
}
declare module 'script-ext-html-webpack-plugin/lib/resource-hints.js' {
  declare module.exports: $Exports<
    'script-ext-html-webpack-plugin/lib/resource-hints'
  >;
}
