// flow-typed signature: 127a45f798738b36fb2490af59c13438
// flow-typed version: <<STUB>>/svg-react-loader_v^0.4.4/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'svg-react-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'svg-react-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'svg-react-loader/lib/component/from-object' {
  declare module.exports: any;
}

declare module 'svg-react-loader/lib/component/stringify' {
  declare module.exports: any;
}

declare module 'svg-react-loader/lib/index' {
  declare module.exports: any;
}

declare module 'svg-react-loader/lib/loader' {
  declare module.exports: any;
}

declare module 'svg-react-loader/lib/options' {
  declare module.exports: any;
}

declare module 'svg-react-loader/lib/sanitize/filters/camel-case-props' {
  declare module.exports: any;
}

declare module 'svg-react-loader/lib/sanitize/filters/convert-style-prop' {
  declare module.exports: any;
}

declare module 'svg-react-loader/lib/sanitize/filters/custom-root' {
  declare module.exports: any;
}

declare module 'svg-react-loader/lib/sanitize/filters/logging' {
  declare module.exports: any;
}

declare module 'svg-react-loader/lib/sanitize/filters/normalize-node' {
  declare module.exports: any;
}

declare module 'svg-react-loader/lib/sanitize/filters/prefix-style-class-id' {
  declare module.exports: any;
}

declare module 'svg-react-loader/lib/sanitize/filters/prop-mapper' {
  declare module.exports: any;
}

declare module 'svg-react-loader/lib/sanitize/filters/remove-xmlns-props' {
  declare module.exports: any;
}

declare module 'svg-react-loader/lib/sanitize/filters/text-content' {
  declare module.exports: any;
}

declare module 'svg-react-loader/lib/sanitize/index' {
  declare module.exports: any;
}

declare module 'svg-react-loader/lib/sanitize/options' {
  declare module.exports: any;
}

declare module 'svg-react-loader/lib/util/camel-case' {
  declare module.exports: any;
}

declare module 'svg-react-loader/lib/util/coerce-to-reg-exp' {
  declare module.exports: any;
}

declare module 'svg-react-loader/lib/util/default-delimiter' {
  declare module.exports: any;
}

declare module 'svg-react-loader/lib/util/index-of-regex' {
  declare module.exports: any;
}

declare module 'svg-react-loader/lib/util/read-file' {
  declare module.exports: any;
}

declare module 'svg-react-loader/lib/util/title-case' {
  declare module.exports: any;
}

declare module 'svg-react-loader/lib/util/upper-case-first' {
  declare module.exports: any;
}

declare module 'svg-react-loader/lib/xml/options' {
  declare module.exports: any;
}

declare module 'svg-react-loader/lib/xml/parse' {
  declare module.exports: any;
}

declare module 'svg-react-loader/lib/xml/processors/attribute-mapper' {
  declare module.exports: any;
}

declare module 'svg-react-loader/lib/xml/xml2js-name-key' {
  declare module.exports: any;
}

// Filename aliases
declare module 'svg-react-loader/lib/component/from-object.js' {
  declare module.exports: $Exports<
    'svg-react-loader/lib/component/from-object'
  >;
}
declare module 'svg-react-loader/lib/component/stringify.js' {
  declare module.exports: $Exports<'svg-react-loader/lib/component/stringify'>;
}
declare module 'svg-react-loader/lib/index.js' {
  declare module.exports: $Exports<'svg-react-loader/lib/index'>;
}
declare module 'svg-react-loader/lib/loader.js' {
  declare module.exports: $Exports<'svg-react-loader/lib/loader'>;
}
declare module 'svg-react-loader/lib/options.js' {
  declare module.exports: $Exports<'svg-react-loader/lib/options'>;
}
declare module 'svg-react-loader/lib/sanitize/filters/camel-case-props.js' {
  declare module.exports: $Exports<
    'svg-react-loader/lib/sanitize/filters/camel-case-props'
  >;
}
declare module 'svg-react-loader/lib/sanitize/filters/convert-style-prop.js' {
  declare module.exports: $Exports<
    'svg-react-loader/lib/sanitize/filters/convert-style-prop'
  >;
}
declare module 'svg-react-loader/lib/sanitize/filters/custom-root.js' {
  declare module.exports: $Exports<
    'svg-react-loader/lib/sanitize/filters/custom-root'
  >;
}
declare module 'svg-react-loader/lib/sanitize/filters/logging.js' {
  declare module.exports: $Exports<
    'svg-react-loader/lib/sanitize/filters/logging'
  >;
}
declare module 'svg-react-loader/lib/sanitize/filters/normalize-node.js' {
  declare module.exports: $Exports<
    'svg-react-loader/lib/sanitize/filters/normalize-node'
  >;
}
declare module 'svg-react-loader/lib/sanitize/filters/prefix-style-class-id.js' {
  declare module.exports: $Exports<
    'svg-react-loader/lib/sanitize/filters/prefix-style-class-id'
  >;
}
declare module 'svg-react-loader/lib/sanitize/filters/prop-mapper.js' {
  declare module.exports: $Exports<
    'svg-react-loader/lib/sanitize/filters/prop-mapper'
  >;
}
declare module 'svg-react-loader/lib/sanitize/filters/remove-xmlns-props.js' {
  declare module.exports: $Exports<
    'svg-react-loader/lib/sanitize/filters/remove-xmlns-props'
  >;
}
declare module 'svg-react-loader/lib/sanitize/filters/text-content.js' {
  declare module.exports: $Exports<
    'svg-react-loader/lib/sanitize/filters/text-content'
  >;
}
declare module 'svg-react-loader/lib/sanitize/index.js' {
  declare module.exports: $Exports<'svg-react-loader/lib/sanitize/index'>;
}
declare module 'svg-react-loader/lib/sanitize/options.js' {
  declare module.exports: $Exports<'svg-react-loader/lib/sanitize/options'>;
}
declare module 'svg-react-loader/lib/util/camel-case.js' {
  declare module.exports: $Exports<'svg-react-loader/lib/util/camel-case'>;
}
declare module 'svg-react-loader/lib/util/coerce-to-reg-exp.js' {
  declare module.exports: $Exports<
    'svg-react-loader/lib/util/coerce-to-reg-exp'
  >;
}
declare module 'svg-react-loader/lib/util/default-delimiter.js' {
  declare module.exports: $Exports<
    'svg-react-loader/lib/util/default-delimiter'
  >;
}
declare module 'svg-react-loader/lib/util/index-of-regex.js' {
  declare module.exports: $Exports<'svg-react-loader/lib/util/index-of-regex'>;
}
declare module 'svg-react-loader/lib/util/read-file.js' {
  declare module.exports: $Exports<'svg-react-loader/lib/util/read-file'>;
}
declare module 'svg-react-loader/lib/util/title-case.js' {
  declare module.exports: $Exports<'svg-react-loader/lib/util/title-case'>;
}
declare module 'svg-react-loader/lib/util/upper-case-first.js' {
  declare module.exports: $Exports<
    'svg-react-loader/lib/util/upper-case-first'
  >;
}
declare module 'svg-react-loader/lib/xml/options.js' {
  declare module.exports: $Exports<'svg-react-loader/lib/xml/options'>;
}
declare module 'svg-react-loader/lib/xml/parse.js' {
  declare module.exports: $Exports<'svg-react-loader/lib/xml/parse'>;
}
declare module 'svg-react-loader/lib/xml/processors/attribute-mapper.js' {
  declare module.exports: $Exports<
    'svg-react-loader/lib/xml/processors/attribute-mapper'
  >;
}
declare module 'svg-react-loader/lib/xml/xml2js-name-key.js' {
  declare module.exports: $Exports<'svg-react-loader/lib/xml/xml2js-name-key'>;
}
