// flow-typed signature: ef9fe750d95e860ed7a71909837700e5
// flow-typed version: <<STUB>>/vue-hot-reload-api_v^2.2.4/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-hot-reload-api'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-hot-reload-api' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-hot-reload-api/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-hot-reload-api/dist/index.js' {
  declare module.exports: $Exports<'vue-hot-reload-api/dist/index'>;
}
