// flow-typed signature: 341046ed758bc5c14ea8336b8a7a0a5e
// flow-typed version: <<STUB>>/vue-template-es2015-compiler_v^1.6.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-template-es2015-compiler'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-template-es2015-compiler' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-template-es2015-compiler/buble' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-template-es2015-compiler/buble.js' {
  declare module.exports: $Exports<'vue-template-es2015-compiler/buble'>;
}
declare module 'vue-template-es2015-compiler/index' {
  declare module.exports: $Exports<'vue-template-es2015-compiler'>;
}
declare module 'vue-template-es2015-compiler/index.js' {
  declare module.exports: $Exports<'vue-template-es2015-compiler'>;
}
