// flow-typed signature: ef88717a62912b17dd16261ccf8e031f
// flow-typed version: <<STUB>>/webpack-manifest-plugin_v^1.3.2/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-manifest-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-manifest-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-manifest-plugin/lib/plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-manifest-plugin/index' {
  declare module.exports: $Exports<'webpack-manifest-plugin'>;
}
declare module 'webpack-manifest-plugin/index.js' {
  declare module.exports: $Exports<'webpack-manifest-plugin'>;
}
declare module 'webpack-manifest-plugin/lib/plugin.js' {
  declare module.exports: $Exports<'webpack-manifest-plugin/lib/plugin'>;
}
