'use strict';
import './editor.all';
import './standalone/browser/accessibilityHelp/accessibilityHelp';
import './standalone/browser/inspectTokens/inspectTokens';
import './standalone/browser/iPadShowKeyboard/iPadShowKeyboard';
// import 'vs/editor/standalone/browser/quickOpen/quickOutline';
// import 'vs/editor/standalone/browser/quickOpen/gotoLine';
// import 'vs/editor/standalone/browser/quickOpen/quickCommand';
// import 'vs/editor/standalone/browser/toggleHighContrast/toggleHighContrast';
// import 'vs/editor/standalone/browser/referenceSearch/standaloneReferenceSearch';
import '../codesandbox/codesandbox.all';
export * from './codesandbox.editor.api';
