// flow-typed signature: 31b4a1766166d30db2d11f9b2ca89b5a
// flow-typed version: <<STUB>>/@cerebral/mobx-state-tree_v^3.0.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@cerebral/mobx-state-tree'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@cerebral/mobx-state-tree' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@cerebral/mobx-state-tree/lib/index' {
  declare module.exports: any;
}

declare module '@cerebral/mobx-state-tree/lib/Model' {
  declare module.exports: any;
}

// Filename aliases
declare module '@cerebral/mobx-state-tree/index' {
  declare module.exports: $Exports<'@cerebral/mobx-state-tree'>;
}
declare module '@cerebral/mobx-state-tree/index.js' {
  declare module.exports: $Exports<'@cerebral/mobx-state-tree'>;
}
declare module '@cerebral/mobx-state-tree/lib/index.js' {
  declare module.exports: $Exports<'@cerebral/mobx-state-tree/lib/index'>;
}
declare module '@cerebral/mobx-state-tree/lib/Model.js' {
  declare module.exports: $Exports<'@cerebral/mobx-state-tree/lib/Model'>;
}
