import { Sandbox } from '../types';
export declare const gitHubRepoPattern: RegExp;
export declare const host: () => string;
export declare const protocolAndHost: () => string;
export declare const newSandboxWizard: () => string;
export declare const newSandboxUrl: () => string;
export declare const parcelSandboxUrl: () => string;
export declare const newReactTypeScriptSandboxUrl: () => string;
export declare const newDojoSandboxUrl: () => string;
export declare const newPreactSandboxUrl: () => string;
export declare const newVueSandboxUrl: () => string;
export declare const importFromGitHubUrl: () => string;
export declare const newSvelteSandboxUrl: () => string;
export declare const newAngularSandboxUrl: () => string;
export declare const newCxJSSandboxUrl: () => string;
export declare const uploadFromCliUrl: () => string;
export declare const sandboxUrl: (sandbox: Sandbox) => string;
export declare const embedUrl: (sandbox: Sandbox) => string;
export declare const frameUrl: (shortid: string, append?: string) => string;
export declare const forkSandboxUrl: (sandbox: Sandbox) => string;
export declare const signInUrl: (extraScopes?: boolean) => string;
export declare const signInZeitUrl: () => string;
export declare const profileUrl: (username: string) => string;
export declare const dashboardUrl: () => string;
export declare const exploreUrl: () => string;
export declare const teamOverviewUrl: (teamId: any) => string;
export declare const profileSandboxesUrl: (username: string, page?: number) => string;
export declare const profileLikesUrl: (username: string, page?: number) => string;
export declare const githubRepoUrl: ({ repo, branch, username, path, }: {
    repo: string;
    branch: string;
    username: string;
    path: string;
}) => string;
export declare const optionsToParameterizedUrl: (options: Object) => string;
export declare const gitHubToSandboxUrl: (githubUrl: string) => string;
export declare const searchUrl: (query: any) => string;
export declare const patronUrl: () => string;
export declare const curatorUrl: () => string;
export declare const tosUrl: () => string;
export declare const privacyUrl: () => string;
