import { Module } from 'cerebral';
import model from './model';
import * as sequences from './sequences';

export default Module({
  model,
  state: {
    settings: {
      livePreviewEnabled: true,
      clearConsoleEnabled: true,
      instantPreviewEnabled: false,
      prettifyOnSaveEnabled: false,
      autoCompleteEnabled: true,
      autoDownloadTypes: true,
      clearConsoleEnabled: true,
      codeMirror: false,
      fontFamily: '',
      fontSize: 14,
      instantPreviewEnabled: false,
      keybindings: {},
      lineHeight: 1.15,
      lintEnabled: true,
      livePreviewEnabled: true,
      newPackagerExperiment: false,
      prettierConfig: {
        printWidth: 80,
        tabWidth: 2,
        useTabs: false,
        semi: true,
        singleQuote: false,
        trailingComma: 'none',
        bracketSpacing: true,
        jsxBracketSameLine: false,
      },
      jsxBracketSameLine: false,
      printWidth: 80,
      semi: true,
      singleQuote: false,
      tabWidth: 2,
      trailingComma: 'none',
      useTabs: false,
      prettifyOnSaveEnabled: true,
      vimMode: false,
      zenMode: false,
    },
    isLoadingPaymentDetails: true,
    paymentDetailError: null,
    paymentDetails: null,
    itemIndex: 0,
    showEditor: true,
    showPreview: true,
  },
  signals: {
    viewModeChanged: sequences.changeViewMode,
    itemIndexChanged: sequences.changeItemIndex,
    preferenceChanged: sequences.setPreference,
    badgeVisibilityChanged: sequences.setBadgeVisibility,
    paymentDetailsRequested: sequences.getPaymentDetails,
    paymentDetailsUpdated: sequences.updatePaymentDetails,
  },
});
