const GREENSOCK_KEYWORDS = [
  'scrolltrigger',
  'scrollsmoother',
  'scrollintent',
  'scrollto',
  'scrolltoplugin',
  'flip',
  'flipplugin',
  'motionpathplugin',
  'motionpathhelper',
  'morphsvg',
  'morphsvgplugin',
  'drawsvg',
  'drawsvgplugin',
  'draggable',
  'inertia',
  'inertiaplugin',
  'cssrule',
  'cssruleplugin',
  'easelplugin',
  'pixiplugin',
  'modifiersplugin',
  'textplugin',
  'scrambletext',
  'scrambletextplugin',
  'splittext',
  'physics2d',
  'physics2dplugin',
  'physicsprops',
  'physicspropsplugin',
  'custombounce',
  'customwiggle',
  'customease',
  'gsdevtools',

  'greensock',
  'gsap',
  'gasp',
  'tween',
  'timeline',
  'animate',
  'animation',
];

export function isGreensockTrialLibrary(name: string) {
  return GREENSOCK_KEYWORDS.includes(name.toLocaleLowerCase());
}
