'use strict';
import './editor.all.js';
import './standalone/browser/accessibilityHelp/accessibilityHelp.js';
import './standalone/browser/inspectTokens/inspectTokens.js';
import './standalone/browser/iPadShowKeyboard/iPadShowKeyboard.js';
// import 'vs/editor/standalone/browser/quickOpen/quickOutline';
// import 'vs/editor/standalone/browser/quickOpen/gotoLine';
// import 'vs/editor/standalone/browser/quickOpen/quickCommand';
// import 'vs/editor/standalone/browser/toggleHighContrast/toggleHighContrast';
// import 'vs/editor/standalone/browser/referenceSearch/standaloneReferenceSearch';
import '../codesandbox/codesandbox.all.js';
export * from './codesandbox.editor.api.js';
