// This component is generated by the build script 🤖
// Please don't modify this file.

import React from 'react';

const Icon = props => (
  <svg width="32" height="32" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path
      d="M23 10.273L21.727 9 16 14.727 10.273 9 9 10.273 14.727 16 9 21.727 10.273 23 16 17.273 21.727 23 23 21.727 17.273 16 23 10.273z"
      fill="currentcolor"
    />
  </svg>
);

export default Icon;
