// This component is generated by the build script 🤖
// Please don't modify this file.

import React from 'react';

const Icon = props => (
  <svg width="32" height="32" xmlns="http://www.w3.org/2000/svg" {...props}>
    <path d="M8 17v-2h16v2H8z" fill="currentcolor" />
  </svg>
);

export default Icon;
